<script lang="ts">
	import MaterialsList from './components/MaterialsList.svelte';
	import ReflectionQuestions from './components/ReflectionQuestions.svelte';
	import AssessmentCriteria from './components/AssessmentCriteria.svelte';
	import CustomSection from './components/CustomSection.svelte';
	import { getSdgColor } from '$lib/utils/sdg-colors';

	interface Props {
		sdgColor?: string;
	}

	let { sdgColor = getSdgColor(3) }: Props = $props();
</script>

<div class="lesson-content">

	<MaterialsList materials={[{"name":"Open space for movement","isOptional":false},{"name":"Audio","isOptional":false},{"name":"Visual Aids","description":"Images or videos showcasing the selected folk dance, or images of the dance's origin country/culture","isOptional":false},{"name":"Whiteboard or large chart paper","isOptional":false},{"name":"Markers","isOptional":false},{"name":"Notebooks or Paper","isOptional":false},{"name":"Pens/Pencils","isOptional":false},{"name":"\\[Optional\\] Colorful scarves for expressive movement","isOptional":true},{"name":"References for chosen folk dance (e.g., \"Mayim Mayim\" Israel,  \"Sirtaki\" Greece, \"The Electric Slide\" USA )","isOptional":false},{"name":"Examples:","isOptional":false},{"name":"\"Mayim Mayim\"","isOptional":false},{"name":"[Reference video for performance](https","description":"//www.youtube.com/watch?v=-xFXr9X5B9I)","isOptional":false},{"name":"[Tutorial video for educator to prep](https","description":"//www.youtube.com/watch?v=ptNBJWxs_nQ)","isOptional":false},{"name":"[Song Example](https","description":"//www.youtube.com/watch?v=TAeuBBW6FZ8)","isOptional":false},{"name":"\"Sirtaki\"","isOptional":false},{"name":"[Reference video for performance](https","description":"//www.youtube.com/watch?v=kG12C1oX5Eo)","isOptional":false},{"name":"[Tutorial video for educator to prep](https","description":"//www.youtube.com/watch?v=_GMEHWx3rEc)","isOptional":false},{"name":"[Song Example](https","description":"//www.youtube.com/watch?v=e_WEjAnslGc&list=RDkG12C1oX5Eo&start_radio=1)","isOptional":false},{"name":"\"The Electric Slide\"","isOptional":false},{"name":"[Reference video for performance](https","description":"//www.youtube.com/watch?v=Sy6O9JKtKXo&list=RDSy6O9JKtKXo&start_radio=1)","isOptional":false},{"name":"[Tutorial video for educator to prep](https","description":"//www.youtube.com/watch?v=4cd9D4z0hrM)","isOptional":false},{"name":"[Song Example](https","description":"//www.youtube.com/watch?v=1vF84LABHm0)","isOptional":false}]} {sdgColor} />

	<CustomSection title={"A Global Dance Party for Wellbeing"} content={"<strong>Introduction</strong><br>Introduce or re-introduce the class to Global Goal 3: Good Health and Well-being.<br><em> This goal aims to make sure everyone, everywhere, has a healthy life and feels good, no matter their age. This means having doctors when you're sick, staying safe, being able to exercise, eating healthy food, and also feeling happy and calm inside your mind.<br></em> It's about caring for our whole selves. Our bodies, our minds, our feelings, and even our friendships.<br>Start a discussion with students about dance: that it is a way people from all over the word celebrate, tell stories, and stay healthy. It helps our bodies move, makes our minds focused, helps us express feelings, and connects us to friends.<br>Let them know that today the class will learn a simple folk dance from another part of the world to see how dance makes us healthy and helps us feel connected."} {sdgColor} />

	<CustomSection title={"Energy Ball Movement"} content={"<p>Begin with an energetic warm-up to get students ready to move their bodies and dance.<br>Have the class stand in a large circle.<br>Instruct the stduents to imagine there's a big, invisible ball of warm, gentle energy in the middle of the circle.<br>Movements begin:<br><em> </em>Teacher starts:<em> I'm going to grab a piece of this energy, make a movement, and pass it to the person next to me.<br></em> (Mimes grabbing energy, does a simple movement like a slow arm circle, and passes the imaginary ball).<br><em> </em>Pass the movement:<em> When you receive the energy, you'll copy the movement, then add your own new simple movement to it, and pass the ball to the next person. Each person adds a new movement, building on the previous one.<br>Examples of movements:<br></em> A gentle sway, a small bounce, a soft clap, a reach, a stretch, a spin in place, a small jump, wiggling fingers, bending knees.<br><em> Let's see how big and complex our Energy Ball can get as we pass it around.<br></em> Remind students to keep it gentle and safe, while also encouraging them to listen with their bodies and mirror accurately before adding their own touch.<br>After a few rounds, guide students to make the Energy Ball get smaller and quieter, bringing it back to stillness.</p>"} {sdgColor} />

	<CustomSection title={"Learning About Our Dance"} content={"<p>Introduce the chosen folk dance. For example:<br><em> Today, we're going to learn \"Mayim Mayim,\" which means \"water, water\" in Hebrew. It's a joyful dance from Israel that celebrates water; something very important for our health.<br></em> <em>Share cultural context:</em> This dance has been done for a long time and helps people feel connected. It reminds us that people all over the world use dance to celebrate important things like water, harvests, or special events.<br><em> </em>Show visual aids:<em> Briefly show a short video clip of the dance being performed. Point out the basic formations (like circles) and the general energy.<br></em> <em>Discuss symbolism:</em> Why do you think people would dance about water? How does dancing in a circle make people feel connected?</p>"} {sdgColor} />

	<CustomSection title={"Basic Steps and Movement Exploration"} content={"<p>Break down the basic steps of the chosen folk dance (e.g., for Mayim Mayim, this would be the basic step-together-step pattern, and the crossing step).<br><em> </em>Demonstrate clearly and slowly:<em> Watch me first. We'll start with a simple step-together-step. Right foot steps out, left foot comes to meet it. Now the left foot steps out, right foot meets it. (Repeat slowly, facing away from students to make mirroring easier).<br></em> <em>Practice individually:</em> Try it in your own space. How does this movement feel in your legs? What happens if you try to make it bouncy or smooth?<br><em> </em>Practice in groups/circles:<em> Now, let's try it together. We'll form a circle and hold hands (or just put hands on shoulders). We'll try the steps moving together. Remember, it's okay if it's not perfect. The fun is in trying and moving together. (Focus on group unison and encouragement).<br></em> <em>Connect to health:</em> Ask guiding questions like:<br><em> How does moving our bodies like this make us feel physically healthy? (e.g., gets our hearts pumping, makes our muscles stronger, helps our balance).<br></em> How does dancing with friends make us feel happy and connected? (e.g., makes us smile, helps us to laugh and get along, feel like part of a team, less lonely).</p>"} {sdgColor} />

	<CustomSection title={"My Dance & My Health Brainstorm"} content={"<p>Explain that the class will now create a Movement Web on the board/large paper.<br><em> We'll connect our dance to different ways we stay healthy and well. In our bodies, minds, feelings, and with our friends.<br>Write \"My Healthy Self (Through Dance)\" in a central bubble on the whiteboard/paper.<br>Draw four branches coming from the center, and ask students to brainstorm how the dance they just learned connects to each type of health:<br></em> <em>Body Health:</em> How does learning this dance help your body?<br>Examples:<br><em> Makes muscles stronger, helps coordination, gets heart pumping, improves balance, gives energy.<br></em> <em>Mind Health:</em> How does learning new steps in this danace help your brain?<br>Examples:<br><em> Helps focus, memory, problem solving, makes brain feel active, calms us down.<br></em> <em>Feelings Health:</em> How does dancing make your feelings feel healthy?<br>Examples:<br><em> Makes me happy, feel joyful, helps me get out anxious feelings, feel peaceful, proud when I get a step right.<br></em> <em>Friendship Health:</em> How does doing this dance with others help your friendships?<br>Examples:\n<ul>\n<li>We work as a team, we laugh together, we help each other, feel connected, feel like part of a group, meet new people.</li>\n</ul><br>Briefly summarize: Our dance helps us in so many ways. It's like a full body, full mind, full heart workout for good health.</p>"} {sdgColor} />

	<CustomSection title={"Group Creation: Health Dance Freeze Frames"} content={"<p>Divide students into small groups (3-4 students).<br>Explain that each group will create a short sequence of two to three frozen poses (like still pictures) that show our the folk dance (or dance in general) helps with one type of health from the Movement Web (body, mind, feelings, or friendship health).<br>Give groups 3-5 minutes to plan their sequence of poses.<br>Encourage students to think about:<br><em> </em>Clear Message:<em> Which type of health are they showing?<br></em> <em>Body Language:</em> How do their bodies show the action or feeling?<br><em> </em>Facial Expressions:<em> How do their faces tell the story?<br></em> <em>Levels and Interaction:</em> Can they use different levels (high, low) or interact with each other to show connection?<br>Circulate, offering support. Ask guiding questions like:<br><em> How can you show \"strong body\" with these poses?<br></em> How can you faces show \"happy feelings?</p>"} {sdgColor} />

	<CustomSection title={"Performance: Our Health Dance Stories"} content={"<p>Have each group briefly present their two to three poses in sequence to the class. Encourage the audience to guess which type of health they are showing.<br>After each group, invite a few students to share what they saw and felt from the poses, and which type of health they think was shown.<br>Finally, invite the presenting group to confirm the intended health focus:\n<ul>\n<li>Our poses showed \\[body/mind/feelings/friendship\\] health beacuse \\[reason\\].</li>\n</ul></p>"} {sdgColor} />

	<ReflectionQuestions questions={["How did dancing and creating poses help you understand Global Goal 3: Good Health and Well-being in a new way?","What did you lean about how our bodies, minds, feelings, and friendships all work together for our health?","Which movements or ideas from our Movement Web made you think or feel the most about good health, and why?","What does our Dancing for Health activity tell us about how people from different cultures use dance to celebrate well-being?","What's one small thing you can do this week to take care of your own body, mind, or feelings, inspired by our dance today?"]} {sdgColor} />

	<AssessmentCriteria criteria={["Consistent and enthusiastic involvement in all phases of the lesson, including the warm-up, folk dance learning, brainstorm, group pose creation, and class discussions.","Understanding of the core concept of Global Goal 3 (Good Health and Well-being, covering body, mind, feelings, and social health), as demonstrated through movement choices, poses, and verbal contributions during discussions.","Originality and effectiveness in using bodies to convey emotions and ideas related to health. Look for clear effort in expressing the feeling and concept.","Ability to work effectively within the small groups during the pose creation, contributing ideas, respecting diverse interpretations, and collaborating cohesively.","Ability to articulate learning and personal connections during the reflection and summary discussion."]} {sdgColor} />

</div>
