<script lang="ts">
	import Introduction from './components/Introduction.svelte';
	import DiscussionPrompts from './components/DiscussionPrompts.svelte';
	import ReflectionQuestions from './components/ReflectionQuestions.svelte';
	import AssessmentCriteria from './components/AssessmentCriteria.svelte';
	import CustomSection from './components/CustomSection.svelte';
	import { getSdgColor } from '$lib/utils/sdg-colors';

	interface Props {
		sdgColor?: string;
	}

	let { sdgColor = getSdgColor(12) }: Props = $props();
</script>

<div class="lesson-content">

	<CustomSection title={"Absurdist Drama For Responsible Consumption"} content={"<strong>(30-60 MINUTES)</strong>"} {sdgColor} />

	<CustomSection title={"Materials:"} content={"<p>Simple props: Chairs, hats, everyday objects that can be used symbolically and recycled materials can be incorporated if desired<br>Whiteboard or large chart paper<br>Markers<br>Notebooks or paper<br>Pens/Pencils<br><a href=\"https://docs.google.com/document/d/1Yp31tX4M-W3hwKiP7rW2R3jHf8VevbsQBJSJwvNz06E/edit?usp=sharing\" target=\"_blank\" rel=\"noopener noreferrer\">Junk Pile Generator Cards</a></p>"} {sdgColor} />

	<Introduction content={"<p>`\t`Welcome students to an exciting drama class. Explain that they will use acting and imagination to explore a really important idea: Global Goal 12, Responsible Consumption and Production.<br>`\t`Clarify that Global Goal 12 is like a huge promise the world has made: a promise to be smarter about the things we use and make. Emphasize that this means:\n<ul>\n<li><em>Being mindful:</em> Thinking about what we buy and if we really need it.</li>\n<li><em>Reducing waste:</em> Using less, and throwing away less.</li>\n<li><em>Reusing and recycling:</em> Finding new lives for old things.</li>\n</ul><br>`\t`It’s about making things in a way that’s good for the planet and making sure we don’t use up all our planet’s resources, so there’s enough for a long time.<br>`\t`Introduce the Theater of the Absurd. Explain that this is a type of theater that shows a world that is illogical, silly, and strange, almost like a weird dream. Clarify that playwrights used funny, nonsensical actions and dialogue to make people laugh and also to make them think about something serious. Tell students that you will use this kind of dream-like humor to show how strange our world can be when we don’t think about what we use and throw away.<br>`\t`Show a short video clip or read a short excerpt from an age-appropriate absurdist story.<br>`\t`Examples:\n<ul>\n<li><a href=\"https://www.youtube.com/watch?v=BzXpvmvhZkQ\" target=\"_blank\" rel=\"noopener noreferrer\">The Amazing World of Gumball - The Job</a></li>\n<li><a href=\"https://www.youtube.com/watch?v=q-lA3aBSPPY\" target=\"_blank\" rel=\"noopener noreferrer\">Regular Show - Wall Buddy</a></li>\n<li><a href=\"https://www.youtube.com/watch?v=wqnIQOPtW2o\" target=\"_blank\" rel=\"noopener noreferrer\">Spongebob Squarepants - Squidward the Maniac</a></li>\n<li><a href=\"https://www.youtube.com/watch?v=6VxSygedTY4\" target=\"_blank\" rel=\"noopener noreferrer\">Adventure Time - Choose Goose</a></li>\n</ul><br>Discuss, with guiding questions like:\n<ul>\n<li>What is strange or illogical about this story/clip?</li>\n<li>How do the characters act in a funny or confusing way?</li>\n<li>Do you think the funny part is trying to make us think about a serious idea?</li>\n</ul></p>"} />

	<CustomSection title={"Exploring Absurdist Techniques"} content={"<p>`\t`<em>Illogical Actions:</em> Explain that in absurdist theater, characters do things that make no sense.\n<ul>\n<li>Have two students pair up in front of the class.</li>\n<li>One student should announce a normal action that they will do:</li>\n<li>“I’m going to read a book”</li>\n<li>The second student then must perform/act out a totally illogical action:</li>\n<li>Pretends to paddle a canoe OR juggles an apple.</li>\n<li>Have a few pairs of students demonstrate this, then ask some guiding questions like:</li>\n<li>What makes that so funny and weird?</li>\n<li>How can this show how absurd it is when we waste things for no reason?</li>\n</ul><br>`\t`<em>Repetition:</em> Explain that repetition of words or actions that  make no sense can be funny.\n<ul>\n<li>Have a small group of students come to the front of the class.</li>\n<li>Ask them to act out a scene where they are trying to charge a phone, but students from the group keep saying things like “This isn’t a phone!” “The charging cable is a snake!” “That charger is an ice cream cone!” to make the simple action absurd and change the action.</li>\n<li>Have the group practice with more illogical action and dialogue, emphasizing the humor in repetition. This will show how funny and strange simple actions and items can become when they don’t follow their expected path and purpose.</li>\n</ul><br>`\t`Conclude by affirming that they will use these funny and illogical actions and dialogue to tell stories about consumption and production.</p>"} {sdgColor} />

	<CustomSection title={"Warm Up: Reduce, Reuse, Recycle!"} content={"<p>`\t`Instruct the class to stand in a circle, facing each other.<br>`\t`<em>The Basic Pass</em>\n<ul>\n<li>Start the game by passing an imaginary object to the student next to you, making eye contact and yelling “Reduce!”</li>\n<li>The student who receives the “object” will then pass it to another student (anyone in the circle), yelling “Reuse!”</li>\n<li>The next student will then pass to another student, yelling “Recycle!”</li>\n<li>The sequence continues, challenging the students to maintain a quick pace and reminding them that making eye contact will help to communicate clearly with their classmates and keep the circuit moving.</li>\n</ul><br>`\t`<em>[Optional] Add an Absurdity</em>\n<ul>\n<li>If desired, the group can add an absurdity to the game, instructing students that when they say their passing word, they have to act out an absurd movement.</li>\n</ul><br>`\t`Conclude warm up by affirming the quick thinking and focus, explaining that this simple exercise prepared them for thinking about the absurd situations that can arise from our consumption habits.</p>"} {sdgColor} />

	<CustomSection title={"The Junk Pile Generator"} content={"<p>`\t`Explain that the class will now brainstorm ideas for their absurd skits.<br>`\t`Divide students into small groups (3-4 students). Provide each group with one Junk Pile Generator Card. <a href=\"https://docs.google.com/document/d/1Yp31tX4M-W3hwKiP7rW2R3jHf8VevbsQBJSJwvNz06E/edit?usp=sharing\" target=\"_blank\" rel=\"noopener noreferrer\">Examples</a>\n<ul>\n<li>Each card will have a list of 3-5 random objects and one Problem prompt.</li>\n</ul><br>`\t`Instruct groups to read their card. Then, explain that they will use the information on their card to create a short, illogical, absurd skit.<br>`\t`Ask guiding questions to help spark thinking like:\n<ul>\n<li>Who will play each character listed on the card?</li>\n<li>What is the most absurd or illogical way to show the problem?</li>\n<li>How will you use repetition or strange dialogue to show the silliness of the situation?</li>\n<li>What is the serious point hiding underneath the silliness?</li>\n</ul><br>`\t`Give groups 5-7 minutes to quickly discuss their skit and decide on a few actions and lines to show the problem.</p>"} {sdgColor} />

	<CustomSection title={"Absurd Skit Creation: A World Gone Mad"} content={"<p>`\t`Explain that each group will now create a short, improvised skit based on the Junk Pile Generator Card and/or the other ideas brainstormed. The skit should show a world gone mad with illogical solutions, repetitive actions, and funny dialogue.<br>`\t`Instruct groups to:\n<ul>\n<li><em>Embrace the Absurdity:</em> Use illogical actions and dialogue from the brainstorm.</li>\n<li><em>Use Repetition:</em> Repeat a line or action that is funny or nonsensical.</li>\n<li><em>Show, Don’t Just Tell:</em> Use exaggerated actions and voices to show the emotions and the silly situation.</li>\n</ul><br>`\t`Provide starting lines or dialogue prompts if needed. Examples:\n<ul>\n<li>I cannot recycle this banana peel; it must be used as a hat!</li>\n<li>Why must we all stand on one foot?  Because the box demands it!</li>\n<li>This old sock has declared itself king, and now it wants to rule the world!</li>\n<li>We have to build a house out of this one plastic straw!</li>\n<li>The bottle cap has declared itself King, and now it wants to rule the world!</li>\n<li>I’m so sorry, but this empty box has told me I am not allowed to eat lunch.</li>\n<li>We must whisper to the broken toy, but only with our mouths closed.</li>\n<li>I cannot throw this away, its the very last paperclip in the world!</li>\n<li>This old newspaper has instructed us to do nothing but run in circles and shout!</li>\n</ul><br>`\t`Circulate, offering guidance and encouragement, asking guiding questions like:\n<ul>\n<li>How can you make the dialogue sound extra ridiculous?</li>\n<li>What action can you repeat to make the audience laugh?</li>\n<li>What’s the serious message hiding under the funny part?</li>\n</ul></p>"} {sdgColor} />

	<CustomSection title={"Performance and Discussion"} content={"<p>`\t`Have each group perform their skit for the class. Remind the audience to be respectful, enjoy the absurdity, and pay attention to the serious point hiding within the humor.<br>`\t`After each skit, facilitate a brief discussion, asking guiding questions like:\n<ul>\n<li>What was the most absurd or illogical part of the skit?</li>\n<li>What was funny about the repetition or the strange dialogue?</li>\n<li>What serious point about Global Goal 12 do you think the skit was trying to make?</li>\n<li>What did the humor make you think about your own habits of consumption and waste?</li>\n</ul></p>"} {sdgColor} />

	<CustomSection title={"Reflection & Summary"} content={"<p>Have students reflect on their learning experience through discussion or writing.<br>Ask guiding questions like:\n<ul>\n<li>How did using the Theater of the Absurd, with its illogical plots and heightened reality, help you to explore and express ideas about responsible consumption and production?</li>\n<li>What new insights did you gain about Global Goal 12 and the urgency of addressing unsustainable consumption and productioin patterns through this theatrical exploration?</li>\n<li>How can drama, particularly absurdist theater, act as a mirror reflecting societal problems in a way that is both entertaining and thought-provoking?</li>\n<li>What is one key takeaway about responsible consumption and the power of creative expression that you will remember from this lesson?</li>\n</ul></p>"} {sdgColor} />

	<CustomSection title={"Assessment"} content={"<ul>\n<li>Consistent and enthusiastic involvement in all phases of the lesson, including the warm up, brainstorm, group skit creation, and class discussions.</li>\n<li>Understanding of the core concept of responsible consumption and production (reducing waste, reusing, recycling), as demonstrated through the thematic content and underlying message of the performance and verbal explanations.</li>\n<li>Originality and effectiveness in applying absurdist elements (e.g., illogical situations, repetition, distorted language, physical comedy, humor) to convey the message about responsible consumption and production. Look for clear effort in expressing the ideas.</li>\n<li>Ability to work effectively within the groups, contributing ideas, respecting diverse interpretations, and collaborating cohesively during the rehearsal and performance processes.</li>\n<li>Ability to articulate learning and personal connections during the reflection and summary discussion.</li>\n</ul>"} {sdgColor} />

</div>
