<script lang="ts">
	import Introduction from './components/Introduction.svelte';
	import DiscussionPrompts from './components/DiscussionPrompts.svelte';
	import ReflectionQuestions from './components/ReflectionQuestions.svelte';
	import AssessmentCriteria from './components/AssessmentCriteria.svelte';
	import CustomSection from './components/CustomSection.svelte';
	import { getSdgColor } from '$lib/utils/sdg-colors';

	interface Props {
		sdgColor?: string;
	}

	let { sdgColor = getSdgColor(12) }: Props = $props();
</script>

<div class="lesson-content">

	<CustomSection title={"Absurdia: Sustainable Consumption in a World Gone Mad"} content={"<strong>(30-60 MINUTES)</strong>"} {sdgColor} />

	<CustomSection title={"Materials:"} content={"<p>Simple props (chairs, hats, everyday objects that can be used symbolically). Recycled materials can be incorporated if desired.<br>Whiteboard or large chart paper<br>Markers<br>Notebooks or paper<br>Pens/Pencils<br>[Optional] Basic and simple costume pieces (fabric scraps, simple clothing items) to suggest characters.</p>"} {sdgColor} />

	<Introduction content={"<p>Begin with introducing students to the theater of the Absurd.<br>Explain its origins in the mid-20th century, its response to the horrors of WWII and the perceived meaninglessness of existence.<br>Highlight its key characteristics:\n<ul>\n<li>Illogical plots and situations.</li>\n<li>Meaningless dialogue and repetition.</li>\n<li>Characters trapped in absurd circumstances.</li>\n<li>Exploration of themes like alienation, anxiety, and the breakdown of communication.</li>\n<li>Often uses humor and satire to critique societal norms.</li>\n</ul>\n<ul>\n<li><a href=\"https://www.youtube.com/watch?v=YfQUIy7TNIk\" target=\"_blank\" rel=\"noopener noreferrer\">A Video History of the theater of the Absurd</a></li>\n<li><a href=\"https://www.youtube.com/watch?v=C6QW_jOuLEc\" target=\"_blank\" rel=\"noopener noreferrer\">Acting Class: What is Theatrical Absurdism A 2 Minute Guide</a></li>\n</ul><br>Facilitate a brief discussion:\n<ul>\n<li>What are your initial reactions to Absurdist theater?</li>\n<li>Why do you think playwrights might choose to portray the world in this way?</li>\n<li>How can absurd situations reveal truths about human behavior or societal problems?</li>\n</ul><br>Introduce or reintroduce Global Goal 12: Responsible Consumption and Production.<br>Emphasize the urgency of addressing unsustainable consumption patterns and the need for a shift towards more sustainable practices.<br>Briefly review the key targets and indicators of Goal 12 if needed.<br>Connect absurdism and Global Goal 12 by engaging students in a discussion about how theater of the Absurd can be used to explore themes of consumption and production. Ask questions like:\n<ul>\n<li>How can the absurdity of our current consumption patterns be portrayed through Absurdist theater?</li>\n<li>Can the illogical situations and idalogue of Absurdism highlight the irrationality of unsustainable practices?</li>\n<li>How can humor and satire be used to critique consumerism and corporate greed?</li>\n<li>Can Absurdist theater help us to see the world in a new way and inspire us to create a more sustainable future?</li>\n</ul></p>"} />

	<CustomSection title={"Script Work and Rehearsal"} content={"<p>Divide students into groups and assign each group one of the provided short scripts.<br>Groups analyze their assigned script, focusing on:\n<ul>\n<li>Identifying the connection to Global Goal 12 and its specific targets.</li>\n<li>Understanding the characters, their motivations, and their relationships.</li>\n<li>Exploring the use of Absurdist elements (e.g., illogical situations, repetitive dialogue, distorted language).</li>\n<li>Determining the overall message or commentary of the script.</li>\n</ul><br>Groups rehearse their scripts, focusing on:\n<ul>\n<li>Character development and physicalization.</li>\n<li>Vocal delivery and pacing.</li>\n<li>Use of props and staging.</li>\n<li>Emphasis on the Absurdist elements.</li>\n<li>Clear communication of the message.</li>\n</ul></p>"} {sdgColor} />

	<CustomSection title={"Performances"} content={"<p>Groups perform their short plays for the class. Encourage students to:\n<ul>\n<li>Embrace the absurdity of the situations and characters.</li>\n<li>Use their creativity and imagination to bring the scripts to life.</li>\n<li>Engage the audience and communicate the underlying message.</li>\n</ul><br>Facilitate a supportive and encouraging environment for performance.<br>Provide brief, constructive feedback after each performance.</p>"} {sdgColor} />

	<CustomSection title={"Discussion"} content={"<p>After all plays have been performed, facilitate a class discussion to reflect on the performances and their connection to Global Goal 12. Ask questions like:\n<ul>\n<li>How did the different plays portray the themes of consumption and production?</li>\n<li>Which Absurdist elements were most effective in conveying the message?</li>\n<li>What did you learn about the challenges and absurdities of our current system?</li>\n<li>How can theater be used to raise awareness and promote change?</li>\n</ul></p>"} {sdgColor} />

	<CustomSection title={"Reflection and Summary"} content={"<p>Have students reflect on their learning experience through discussion or writing.<br>Ask guiding questions like:\n<ul>\n<li>How did using the theater of the Absurd - with its illogical plots and heightened reality - help you to explore and express ideas about responsible consumption and production?</li>\n<li>What did you learn about the power of humor, satire, and exaggeration to draw attention to serious issues like unsustainable consumption patterns?</li>\n<li>Did performing or witnessing these “absurb” scenes change your perspective on the irrationality or contradictions inherent in some of our current consumption habits?</li>\n<li>What did you discover about the effectiveness of using unexpected situations and dialogue to spark new ways of thinking about global challenges?</li>\n<li>How can drama, particularly Absurdist theater, act as a mirror reflecting societal problems in a way that is both entertaining and thought-provoking?</li>\n<li>What new insights did you gain about Global Goal 12 and the urgency of addressing unsustainable consumption and production patterns through this theatrical exploration?</li>\n<li>How did the different plays, through their absurd scenarios, highlight specific challenges or consequences related to targets of Global Goal 12 (e.g., waste, resource depletion, corporate practices)?</li>\n<li>Did the theatrical experience make you think differently about your own consumer choices or the larger systems of production and consumption?</li>\n<li>How does framing these issues through an Absurdist lens help to reveal underlying truths about our relationship with materials and the environment?</li>\n<li>Did participating in or watching these plays spark any personal connections or reflections on your own experiences with consumption or waste?</li>\n<li>What emotions did you connect with during this lesson, and how might those emotions motivate you to take action related to Global Goal 12?</li>\n<li>What is one key takeaway about responsible consumption and the power of creative expression that you will remember from this lesson?</li>\n</ul></p>"} {sdgColor} />

	<CustomSection title={"Assessment"} content={"<ul>\n<li>Consistent and enthusiastic involvement in all phases of the lesson, including the introduction to Absurdist theater, script analysis, rehearsals, performances, and class discussions.</li>\n<li>Comprehension of Global Goal 12, targets and core concepts, as demonstrated through the thematic content and underlying message of their performance and their verbal explanations.</li>\n<li>Originality and effectiveness in applying Absurdist elements (e.g., illogical situations, repetition, distorted language, physical comedy, satire) to convey their message about responsible consumption and production.</li>\n<li>How clearly and powerfully the finished scene(s) communicated its intended message about Global Goal 12. Did the performance successfully evoke thought or emotion in the audience, or effectively highlight the absurdist of unsustainable practices?</li>\n<li>How well students portrayed characters within the absurd context, showing motivations and reactions, even if illogical, and connecting them to the scene’s commentary on Global Goal 12.</li>\n<li>Ability to work effectively within their groups, contributing ideas, respecting diverse interpretations, and collaborating cohesively during the rehearsal and performance processes.</li>\n<li>Nuance and insight demonstrated in reflections, particularly concerning the role of theater in addressing social change and the complexities of achieving sustainable consumption patterns.</li>\n</ul>"} {sdgColor} />

</div>
