<script lang="ts">
	import Introduction from './components/Introduction.svelte';
	import DiscussionPrompts from './components/DiscussionPrompts.svelte';
	import ReflectionQuestions from './components/ReflectionQuestions.svelte';
	import AssessmentCriteria from './components/AssessmentCriteria.svelte';
	import CustomSection from './components/CustomSection.svelte';
	import { getSdgColor } from '$lib/utils/sdg-colors';

	interface Props {
		sdgColor?: string;
	}

	let { sdgColor = getSdgColor(11) }: Props = $props();
</script>

<div class="lesson-content">

	<CustomSection title={"Acting Our City Stories With Playback Theater"} content={"<strong>(30-60 MINUTES)</strong>"} {sdgColor} />

	<CustomSection title={"Materials:"} content={"<p>Large open space<br>Simple props (scarves, chairs, hats, etc.)<br>Whiteboard or large chart paper<br>Markers and pens<br>Notebooks or paper<br>Pens/Pencils<br>Story Idea Cards: Prepared slips of paper or cards with prompts that help students think of a short story. Each card will have a character, a place, and a feeling/event. <a href=\"https://docs.google.com/document/d/1SjChJLGg-sP5Pj5J4dx5p0C9m2Av8GtCsHvs9pN-j6c/edit?usp=sharing\" target=\"_blank\" rel=\"noopener noreferrer\">Examples</a></p>"} {sdgColor} />

	<Introduction content={"<p>Welcome students to an exciting drama class. Explain that they will use acting and imagination to explore a really important idea: Global Goal 11, Sustainable Cities and Communities.<br>Clarify that Global Goal 11 is like a huge promise the world has made; a promise to build cities and towns that are great places to live for everyone. Emphasize that this means cities that are:\n<ul>\n<li><em>Inclusive:</em> Welcoming and fair for all people.</li>\n<li><em>Safe:</em> Places where everyone feels secure.</li>\n<li><em>Resilient:</em> Strong enough to handle challenges like bad weather or problems.</li>\n<li><em>Sustainable:</em> Good for the planet and for people for a long time.</li>\n</ul><br>Introduce the concept of Playback Theater. Explain that playback theater is a special kind of improvisation where the audience shares a real, personal story or experience, and a group of actors quickly acts it back to them. Clarify taht the actors don’t use the storyteller’s exact words, but they use their bodies, voices, and emotions to show the story’s feeling.<br>Emphasize that the goal is to show the storyteller that their story was truly heard and understood. Tell students that this is a powerful way to build empathy and community, by showing how our personal stories are connected.</p>"} />

	<CustomSection title={"Warm Up: The Living City Soundscape"} content={"<p>Instruct students to spread out in the space available.<br><em>Creating City Sounds</em>\n<ul>\n<li>Tell students that, on your signal, everyone should make a quiet sound of a city or community. It could be the sound of a bike, a car, a person walking, a bird, a happy hum, or a soft laugh.</li>\n<li>Model a few sounds, and then signal for the class to begin.</li>\n<li>Instruct students to listen to the sounds around them, and make sure their sound is a part of the whole.</li>\n</ul><br><em>Introducing a Problem</em>\n<ul>\n<li>Now, tell students that when you hold your arm up, they should change their sound to a sound representing a problem in a city or community. This could be a car horn blaring, a frustrated sigh, the sound of a crumbling building, etc.)</li>\n<li>Additionally, instruct students to watch for when your arm lowers. This indicates that they should go back to their initial, happy city or community sound.</li>\n<li>Repeat this back and forth a few times, having students move between their city sound and problem sound.</li>\n</ul><br><em>Building a Solution</em>\n<ul>\n<li>Now, let students know that when they see your arm in the air, they will change to the sound of a solution (e.g., a cheering crowd, a sound of a tool fixing something, the sound of a new invention).</li>\n<li>When your arm lowers, they should go back to the initial, happy city or community sound.</li>\n<li>Repeat this back and forth if time allows.</li>\n</ul><br>Conclude warm up by affirming the responsiveness and creativity, explaining that they just told a story about a city’s challenges and solutions with only sounds.</p>"} {sdgColor} />

	<CustomSection title={"My Community Story"} content={"<p>Explain that today the class will share short, personal stories about the community. Clarify that they don’t have to be big dramatic stories; they can be a moment, a memory, or a feeling. Ensure students know the stories should be about something that happened in their city or community that relates to a safe, inclusive, or sustainable community, connecting with Global Goal 11.<br>Have students break into small groups (3-4 groups total).<br>If needed, use Story Idea Cards to help students think of a short, personal memory. Set them out for students to view and use as inspiration.<br><a href=\"https://docs.google.com/document/d/1SjChJLGg-sP5Pj5J4dx5p0C9m2Av8GtCsHvs9pN-j6c/edit?usp=sharing\" target=\"_blank\" rel=\"noopener noreferrer\">Story Card Examples</a><br>Explain that you will invite a volunteer from the class to be the “Storyteller.”\n<ul>\n<li><em>The Storytellers Role:</em> The storyteller will tell a short, true story from their life (it can be as simple as “I saw someone help a neighbor with their groceries.”). The Storyteller should focus on one moment or strong feeling in the story.</li>\n<li><em>The Actors’ Role:</em> Each group will have a chance to be the actors. Instruct them to listen carefully to the story and get ready to act it back.</li>\n</ul><br>Ask for a volunteer to be the first storyteller. Remind them that their story can be short and simple.</p>"} {sdgColor} />

	<CustomSection title={"Playback Performance: Echoes of the City"} content={"<em>Playback Forms:</em> Explain two simple playback forms that the actors can use (or, for simplicity, choose one for the entire lesson).\n<ul>\n<li><em>Sound Echoes:</em> After the storyteller is done, the actors will say a keyword or phrase from the story, echoing the feeling they heard.</li>\n<li><em>Body Echoes:</em> After the storyteller is done, the actors will create a single, frozen pose or body shape that shows a key moment or feeling from the story.</li>\n</ul><br>Tell the actors to decide which form they will use before they hear each story (if they are choosing between the two).<br><em>Story and Playback:</em> Invite the storyteller to share their short story.<br><em>The Performance</em>\n<ul>\n<li>Once the storyteller is finished, the actors take a moment to think together as a group.</li>\n<li>Then, instruct them to perform the playback.</li>\n<li><em>Sound Echoes:</em> The actors choose a keyword or phrase from or inspired by the story and say it back to the storyteller and audience, echoing the feeling they heard and reflecting the emotional core of the story.</li>\n<li><em>Body Echoes:</em> The actors create their pose, holding it for a few seconds to show the story’s key feeling.</li>\n<li>Then, ask the storyteller some clarifying questions like:</li>\n<li>Did the actors capture the feeling of your story?</li>\n<li>What did it feel like to see them act it back?</li>\n</ul><br>Affirm that the performance showed they were listening carefully."} {sdgColor} />

	<CustomSection title={"Discussion"} content={"<p>Invite actors to share, asking guiding questions like:\n<ul>\n<li>What keyword or moment in the story did you choose to show with your voice or body?</li>\n<li>How did you use your voice, body, and/or face to show that part of the story?</li>\n<li>How did you feel while acting back the story? What was it like to use your voice or body to reflect someone else’s feelings?</li>\n</ul><br>Repeat the process with 1-2 more volunteers who want to be storytellers.</p>"} {sdgColor} />

	<CustomSection title={"Playing it Back"} content={"<p>Ask students to think about how these small personal stories that were acted out connect to the bigger idea of Global Goal 11. Ask guiding questions like:\n<ul>\n<li>What feelings or insights did you gain from seeing your classmates’ stories being acted back?</li>\n<li>What were some of the common themes you heard?</li>\n<li>What did you learn about the power of storytelling and acting to help us understand each other’s experiences?</li>\n<li>How can these personal stories about our community’s challenges and solutions connect to the big promise of Global Goal 11?</li>\n<li>How did the actors’ performances show us something about what it means to build an inclusive, safe, or sustainable city or community?</li>\n<li>What did these stories make you think about your own community?</li>\n</ul></p>"} {sdgColor} />

	<CustomSection title={"Reflection & Summary"} content={"<p>Have students reflect on their learning experience through discussion or writing.<br>Ask guiding questions like:\n<ul>\n<li>How did the experience of hearing and seeing personal stories played back in real-time deepen your understanding of the human impact of urban challenges related to Global Goal 11?</li>\n<li>What did you learn about the power of Playback Theater as a tool for communication and understanding?</li>\n<li>What new insights did you gain about Global Goal 11 and the importance of creating inclusive, safe, resilient, and sustainable cities and communities?</li>\n<li>What is one key takeaway about sustainable cities and the power of the individual and collective action that you will remember from this lesson?</li>\n<li>What specific action, big or small, are you inspired to take after this lesson to contribute to achieving Global Goal 11?</li>\n</ul></p>"} {sdgColor} />

	<CustomSection title={"Assessment"} content={"<ul>\n<li>Consistent and enthusiastic involvement in all phases of the lesson, including the warm up, story gathering, participation as storytellers and/or actors, and active listening during discussions.</li>\n<li>Ability to listen attentively and respond emphathetically to shared personal stories, both as a participant and as an observer in the playback performances.</li>\n<li>Understanding of the core concept of sustainable cities (inclusive, safe, resilient), as demonstrated through the story contributions, playback interpretations, and verbal explanations during discussions.</li>\n<li>Originality and effectiveness of playback performances, including the use of simple forms (e.g., sound echoes, body echoes) to capture the essence and emotion of the shared narratives. Look for clear effort in expressing the feeling through voice and body.</li>\n<li>Ability to work effectively and respectfully with fellow actors, responding spontaneously and collaboratively to the storyteller’s narrative.</li>\n<li>Ability to articulate learning and personal connections during the reflection and summary discussion.</li>\n</ul>"} {sdgColor} />

</div>
