<script lang="ts">
	import MaterialsList from './components/MaterialsList.svelte';
	import Introduction from './components/Introduction.svelte';
	import ReflectionQuestions from './components/ReflectionQuestions.svelte';
	import AssessmentCriteria from './components/AssessmentCriteria.svelte';
	import CustomSection from './components/CustomSection.svelte';
	import { getSdgColor } from '$lib/utils/sdg-colors';

	interface Props {
		sdgColor?: string;
	}

	let { sdgColor = getSdgColor(4) }: Props = $props();
</script>

<div class="lesson-content">

	<MaterialsList materials={[{"name":"Open space for movement and improvisation","isOptional":false},{"name":"Whiteboard or large chart paper","isOptional":false},{"name":"Markers","isOptional":false},{"name":"Notebooks or Paper","isOptional":false},{"name":"Pens/Pencils","isOptional":false},{"name":"\"School Place Cards\"","description":"Slips of paper with common school locations. Prepare enough for each group to draw one. [EXAMPLES](https://docs.google.com/document/d/1nEbz5KyQJSLXRxcoBd245K7eroR4I6bP3dV5ZHDozLg/edit?usp=sharing)","isOptional":false},{"name":"\"School Activity Cards\"","description":"slips of paper with common school activities. Prepare enough for each group to draw one. [EXAMPLES](https://docs.google.com/document/d/1pUeY0PGz6MTl84gQM-5yKx0g6jK7QbYKHpNyLsjDnEw/edit?usp=sharing)","isOptional":false},{"name":"\\[Optional\\] Simple Props","description":"Scarves, hats, oversized objects, funny glasses, empty boxes, chairs, small toys (easily accessible classroom items, encouraging imaginative use).","isOptional":true}]} {sdgColor} />

	<CustomSection title={"Classroom Capers: Drama for Education"} content={"<strong>(30-60 MINUTES)</strong>"} {sdgColor} />

	<Introduction content={"<p>Welcome students to an exciting drama class. Explain that you will use acting skills and imagination to explore a really important idea: Global Goal 4: Quality Education.<br>Emphasize that this means ensuring everyone, everywhere, has a chance to get a great education by going to good schools, learning important and interesting things, and getting ready for the future, from little kids to grown-ups.<br>Explain that today, you will focus on a super important part of quality education: having safe, welcoming, and effective places to learn for everyone. Connect this to Global Goal 4 by explaining that this means a school where:<br><em> Students feel safe and secure, like no one will hurt or bully them.<br></em> Everyone feels welcomed and included, no matter who they are or what they need.<br><em> The classrooms and spaces make learning exciting and fun.<br></em> Every student feels comfortable and ready to learn.<br>Explain to students that sometimes, the best way to understand big ideas, like making schools safe and welcoming for everyone, is to show them. Clarify that drama is a powerful way to show feelings, problems, and amazing solutions.<br>Tell students that today, we will explore what happens when things go a little bit \"silly\" or \"wrong\" in a school, and then how we can use smart ideas to make everything right again.<br>Introduce the idea of exaggeration in drama \\- making movements, voices, and feelings much bigger and funnier than in real life, like in many cartoons or funny movies.<br>Examples (can show if desired):<br><em> Spongebob Squarepants: <a href=\"https://www.youtube.com/watch?v=S6Ky8mmot-I\" target=\"_blank\" rel=\"noopener noreferrer\">Every Time Spongebob Goes Nuts</a> (multiple examples/clips)<br></em> Despicable Me: <a href=\"https://www.youtube.com/watch?v=r-YjmXt15sg\" target=\"_blank\" rel=\"noopener noreferrer\">Fart Gun</a> (starts at \\~:24)<br><em> Mr. Bean: <a href=\"https://www.youtube.com/watch?v=lW6R9kSGV2Q\" target=\"_blank\" rel=\"noopener noreferrer\">At The Dentist</a><br></em> The Amazing World of Gumball: <a href=\"https://www.youtube.com/watch?v=Ri5ED3377nU\" target=\"_blank\" rel=\"noopener noreferrer\">Funny Moments</a> <a href=\"https://www.youtube.com/watch?v=6ZAJxSkrqdU\" target=\"_blank\" rel=\"noopener noreferrer\">The Secret Life of Objects</a><br>Emphasize that we will use this humor to highlight problems in a lighthearted way and then find smart, helpful solutions.</p>"} />

	<CustomSection title={"Warm-Up: Exaggerated School Actions"} content={"<p>Explain that the class will perform common school actions, but with exaggerated emotions and movements. Instruct students to copy your exaggerated actions.<br>Examples:<br><em> </em>Action 1: Super Excited to Learn\\!<em><br></em> Demonstrate taking notes or listening with comically wide eyes, huge nods, rapid-fire scribbling, and a ridiculously eager smile.<br><em> </em>Action 2: Super Confused by Homework\\!<em><br></em> Demonstrate scratching yoru head furiously, brow furrowed dramatically, sighing loudly, looking at imaginary paper upsidedown, and shrugging shoulders to your ears.<br><em> </em>Action 3: Super Happy at Recess\\!<em><br></em> Demonstrate an over-the-top skip, a giant laugh, swinging imaginary arms wildly, and a huge, goofy smile.<br><em> </em>Action 4: Super Bored in Class\\!<em><br></em> Demonstrate a slow, dramatic yawn, eyes rolling to the ceiling, head slowly slumping, and tapping an imaginary pencil with exaggerated slowness.<br><em> </em>Action 5: Super Ready to Help\\!<em><br></em> Demonstrate standing tall with an enormous grin, arms outstretched in a \"can do\\!\" pose, and a big, determined nod.<br>Conclude the warm-up by affirming their fantastic exaggerated acting and explaining that they will continue to use this \"super-sizing\" of actions in their upcoming skits.</p>"} {sdgColor} />

	<CustomSection title={"Our Awesome School Skits"} content={"<p>Explain that the class will create some ideas for silly school problems and then find smart solutions. Each group will start by getting two cards: a School Place and a School Activity.<br>Divide students into small groups (3-4 students).<br>Give each group (or have them pick randomly) one School Place Card, and one School Activity Card.<br><em> </em>Part 1, The Silly Problem<em><br></em> Instruct groups to brainstorm how their chosen \"Place\" and \"Activity\" could go comically wrong in a way that relates to school being unsafe, unwelcoming, or making it hard to learn. Tell them to think of funny exaggerations.<br>Examples:<br><em> </em>Place:<em> Library </em>Activity:<em> Reading a book </em>Silly Problem:<em> All the books in the library loudly sing show tunes, making it impossible to concentrate and read OR The chairs in the library randomly bounce you to the ceiling, making it very hard to read.<br></em> <em>Place:</em> Cafeteria <em>Activity:</em> Eating lunch <em>Silly Problem:</em> The cafeteria food tries to eat YOU OR All the lunch trays suddenly turn into rabbits.<br><em> </em>Place:<em> Classroom </em>Activity:<em> Listening to a lesson </em>Silly Problem:<em> The teacher keeps turning into a squirrel every five minutes OR The classroom walls randomly change colors to make everyone feel quite dizzy.<br></em> <em>Place:</em> Playground <em>Activity:</em> Playing a game <em>Silly Problem:</em> The swings try to launch you into space OR The basketball hoop has a mind of its own and steals the ball.<br><em> </em>Place:<em> Hallway </em>Activity:<em> Walking to class </em>Silly Problem:<em> The hallway keeps changing into a giant slippery slide OR Invisible walls keep popping up to block your way.<br></em> Instruct groups to write down their chosen Silly Problem idea.<br><em> </em>Part 2, The Smart Solution<em><br></em> Instruct groups to brainstorm a smart and helpful solution (doesn't have to be completely realistic) for their silly problem. You tell them to think about how they could make the school safe, welcoming, or good for learning again.<br>Examples (based on the above problems):<br><em> </em>For singing books:<em> Students invent special \"quiet helmets\" for reading.<br></em> <em>For teacher turning into a squirrel:</em> Students create a \"squirrel-to-teacher translator app\"<br><em> </em>For walls changing color:<em> Students design a \"calm color\" remote control for the walls.<br></em> <em>For swings launching:</em> Students create new rules for safe swinging and create a soft landing pit.<br><em> Instruct groups to write down their Smart Solution idea.<br></em> Circulate, offering guidance. Ask guiding questions like:<br><em> How can you make that problem super silly?<br></em> What's a smart and helpful solution that could help that problem in a school?</p>"} {sdgColor} />

	<CustomSection title={"Silly Problem, Smart Solution Skits"} content={"<p>Explain that each group will now bring their brainstormed ideas to life\\! Each group will create a short, silent scene (like a mini-play without words) that lasts about 60 seconds. Each scene will have two parts:<br><em> </em>Part 1, Silly Problem:<em> Exaggerated and humorous. Show the crazy challenge from your brainstorm<br></em> <em>Part 2, Smart Solution:</em> Still may be silly, but a positive scene showing how that challenge is solved in a meaningful (for the challenge) way.<br>Encourage groups to think about:<br><em> </em>Characters:<em> Who are the people in the scene (e.g., students, a teacher, a principal, a helpful friend).<br></em> <em>Exaggeration:</em> How can they use big movements, silly faces, and funny noises (but no full sentences) in Part 1?<br><em> </em>Clarity:<em> How can they make their message clear without words in both parts?<br></em> <em>Teamwork:</em> How does everyone in the group contribute to both parts of the scene?<br><em> </em>Props (Optional):<em> If available, can they use any simple classroom props imaginatively?<br>Circulate, offering support and encouragement. Ask guiding questions like:<br></em> How are you making the problem look super silly and exaggerated?<br><em> What key action shows the moment the solution happens?<br></em> Are you thinking about the transition from the silly part to the smart solution part?<br><em> How can your faces show the funny frustration, and then the happy relief?<br></em> Waht's one funny sound or gesture your group can add to your silly problem?</p>"} {sdgColor} />

	<ReflectionQuestions questions={["How did acting out silly problems and smart solutions help you think about what makes a great education for everyone?","What did you learn about the importance of schools being safe, welcoming, and fun places to learn, even if we explored it with humor?","What does this activity tell us about how we can all work towards Global Goal 4: Quality Education?","What's one small thing you can do this week to make your own classroom or school a more safe, welcoming, or fun place to learn?"]} {sdgColor} />

	<AssessmentCriteria criteria={["Consistent and enthusiastic involvement in all phases of the lesson, including the warm-up, brainstorm, group scene creation, and class discussions (both performing and observing).","Understanding of the core concept of safe, welcoming, and effective learning environments within Global Goal 4, as demonstrated through the scene content and verbal explanations.","Originality and effectiveness in using dramatic techniques (e.g., exaggeration in the problem scene, clear physical actions, facial expressions) to vividly represent a school challenge and a corresponding realistic solution. Look for clear effort in expressing the ideas.","Ability to work effectively within the small groups, contributing ideas, respecting diverse interpretations, and collaborating cohesively to create and peform the scenes.","Ability to articulate learning and personal connections during the reflection and summary discussion."]} {sdgColor} />

</div>
