<script lang="ts">
	import MaterialsList from './components/MaterialsList.svelte';
	import Introduction from './components/Introduction.svelte';
	import ReflectionQuestions from './components/ReflectionQuestions.svelte';
	import AssessmentCriteria from './components/AssessmentCriteria.svelte';
	import CustomSection from './components/CustomSection.svelte';
	import { getSdgColor } from '$lib/utils/sdg-colors';

	interface Props {
		sdgColor?: string;
	}

	let { sdgColor = getSdgColor(7) }: Props = $props();
</script>

<div class="lesson-content">

	<MaterialsList materials={[{"name":"Open space for movement","isOptional":false},{"name":"Whiteboard or large paper","isOptional":false},{"name":"Markers","isOptional":false},{"name":"Index cards or slips of paper","isOptional":false},{"name":"Paper or notebooks","isOptional":false},{"name":"Pens/pencils","isOptional":false},{"name":"\\[Optional\\] Small props (e.g., scarf, book, toy, pretend flashlight, etc.)","isOptional":true},{"name":"\\[Optional\\] Audio and sound effects (e.g., sound of power outage, busy city, wind chimes, gentle hum, etc.)","isOptional":true}]} {sdgColor} />

	<CustomSection title={"Energy Spotlight: Forum Theater for Clean Power"} content={"<strong>(30-60 MINUTES)</strong>"} {sdgColor} />

	<Introduction content={"<p>Welcome students to an exciting drama and theater class. Explain that they will use acting and imagination to explore a really important topic: Global Goal 7, Affordable and Clean Energy.<br>This goal focuses on making sure everyone, everywhere, has access to energy that is affordable (not too expensive), reliable (always there when you need it), and clean (good for the planet). You emphasize that this means lights for homes and schools, clean ways to cook food, and power for our devices, all without harming the Earth.</p>"} />

	<CustomSection title={"Warm Up: Energy All Around Us"} content={"<p>Ask students to close or rest their eyes for a moment.<br>Ask: Think about your morning today. What’s one thing you used that needed electricity or energy?<br>Have students quickly share responses. Examples:<br><em> Alarm clock/phone<br></em> Toaster<br><em> Tablet<br></em> Lights<br><em> Television<br></em> Car<br>Affirm their answers: Wow, look at all the ways energy powers our lives before we even get to school. It’s everywhere.<br>Ask: Imagine if one day, your alarm didn’t go off because there was no power, you couldn’t toast your bread, or your tablet wouldn’t charge. How would that make you feel? What would be different?<br>Listen to responses, drawing out feelings of frustration, inconvenience, or even sadness.<br>Gently guide students: For many people around the world, this is actually their everyday life. They don’t have reliable electricity. Or the energy they use makes the air dirty. That’s why Global Goal 7 is so important \\- to make sure everyone has access to the right kind of energy.</p>"} {sdgColor} />

	<CustomSection title={"Brainstorm: Energy Character Challenge"} content={"<p>Divide the class into groups of 4-6 students. Provide each group with one pre-written Energy Scene Starter Slip.<br><a href=\"https://docs.google.com/document/d/1-EvEuYFkRnLjpVeQVsQaWyZ0Ml-a0j-OxaK3WZQdhNQ/edit?usp=drive_link\" target=\"_blank\" rel=\"noopener noreferrer\">Examples</a><br>Instruct each group to look at their scene starter, the characters, and the problem. Challenge them to quickly discuss and prepare a very short scene (1-2 minutes long) about this problem. Have them focus on showing the characters’ feelings and the challenge clearly.<br>Clarify that no script needs to be written, they can improvise based on the scene starter or have planned dialogue, whatever works best for their group.<br>Example discussion points for groups:<br><em> Who will play each character listed?<br></em> What are the most important lines or actions to show the problem?<br><em> How will you show the characters’ feelings (frustration, tiredness, worry, confusion)?<br></em> What simple props (optional) could be used to make the scene clearer?\n<ul>\n<li>What are some possible ways you might try to solve this problem if you were the audience intervening? (This preps for audience interventions).</li>\n</ul><br>Give groups 5-7 minutes to quickly discuss the scene starter, assign roles, and decide on a few lines or actions to show their problem.<br>Circulate, offering guidance and encouragement, prompting them to think about hw they will clearly show the problem for the audience.</p>"} {sdgColor} />

	<CustomSection title={"Forum Theater Performance"} content={"<p>Bring the class back together. Explain that each group will perform their short scene, and the audience will be ready to “STOP\\!” and offer solutions.<br>Invite the first group to perform (volunteer or you choose). Remind the audience of the “STOP\\!” and “What Else Could Happen?” rules.<br>The group performs their short scene, depicting the challenge or conflict related to energy.<br>Example Scenario Played Out:<br><em> </em>Student 1:<em> “Oh no, not again\\! Our project is due tomorrow, and I can’t even see my notes\\!”<br></em> <em>Student 2:</em> “Why is it always dark when we need to work? This is impossible\\!”<br><em> </em>Student 3:<em> “Forget it, I can’t do this in the dark. I’m giving up.”<br></em> <em>Teacher:</em> “I can’t find a flashlight anywhere. This power outage is making things very difficult.”<br><em> </em>AUDIENCE MEMBER YELLS “STOP\\!”<em><br></em> Freeze the actors. Say: Great stop\\! What else could the characters do or say here to help with the dark? or What new idea could we try in this scene to get light?<br>Example Audience Suggestions:<br><em> Maybe the teacher could suggest using phone flashlights?<br></em> See if anyone has a solar lamp?<br><em> Ask the original actors: Would you like to try that? Or would someone from the audience like to jump in and show us?<br></em>REPLAY<em><br></em> <em>Teacher (either original or spect-actor):</em> “Wait\\! I have my phone? And hey \\[Student 1\\], didn’t you mention your family has a solar powered lamp? Maybe you could bring it tomorrow\\!.”<br><em> </em>Student 1:<em> “Yes\\! I forgot\\! We could totally use that\\!”<br>You might ask for another “STOP\\!” to explore different solutions, or prompt the students yourself if they need a little help.<br>Repeat this process for the rest of the groups, depending on time and engagement. For each scenario, encourage at least one STOP and replay with a new idea.<br>Key points to facilitate during intervention:<br></em> Guide students to suggest actions or dialogue that change the scene.<br><em> Remind them to focus on positive changes that align with Global Goal 7\\.<br></em> After each replay ask questions like: Did that help? Why or why not? What was different?\n<ul>\n<li>Connect suggested solutions back to Global Goal 7 concepts (e.g., That’s a great example of using clean, reliable energy. or That shows how important affordable energy is for learning.).</li>\n</ul></p>"} {sdgColor} />

	<ReflectionQuestions questions={["How did acting out scenes and trying to change them in Forum Theater help you understand Global Goal 7: Affordable and Clean Energy in a new way?","What did you learn about how our choices, even small ones, can affect energy problems or solutions?","Which scene or spect-actor intervention made you think the most, and why?","What do these activities tell us about how we can all work towards Global Goal 7?","What’s one small action you feel inspired to take this week to save energy or promote clean energy, perhaps because you now feel more confident in finding solutions?"]} {sdgColor} />

	<AssessmentCriteria criteria={["Consistent and enthusiastic involvement in all phases of the lesson, including the warm up, brainstorm, group scene creation, Forum Theater performances (as actors and spect-actors), and class discussions.","Understanding of the core concepts of affordable and clean energy (challenges, solutions, access, efficiency), as demonstrated through the relevance and accuracy of the scenarios created and performed, ability to improvise and adapt within the Forum Theater format, quality and thoughtfulness of the solutions proposed (as audience members or spect-actors), and verbal explanations during discussions.","Ability to collaborate effectively within small groups to develop a short scene from the starter slip, clearly depict a challenge or conflict related to energy within the performance, respond thoughtfully and creatively to audience interventions, incorporating new ideas into the scene, demonstrate understanding of the STOP and What Else Could Happen mechanics, and use voice, body, and facil expressions to convey character and emotion.","Ability to identify key problems within the presented scenarios, brainstorm diverse and creative solutions, and consider the potential impact of different choices.","Ability to articulate learning and personal connections during the reflection and summary discussion, particularly concerning the power of drama as a tool for understanding and addressing real-world issues."]} {sdgColor} />

</div>
