<script lang="ts">
	import MaterialsList from './components/MaterialsList.svelte';
	import Introduction from './components/Introduction.svelte';
	import ReflectionQuestions from './components/ReflectionQuestions.svelte';
	import AssessmentCriteria from './components/AssessmentCriteria.svelte';
	import CustomSection from './components/CustomSection.svelte';
	import { getSdgColor } from '$lib/utils/sdg-colors';

	interface Props {
		sdgColor?: string;
	}

	let { sdgColor = getSdgColor(3) }: Props = $props();
</script>

<div class="lesson-content">

	<MaterialsList materials={[{"name":"Open space for movement","isOptional":false},{"name":"Audio","isOptional":false},{"name":"Whiteboard or large chart paper","isOptional":false},{"name":"Markers","isOptional":false},{"name":"Notebooks or Paper","isOptional":false},{"name":"Pens/Pencils","isOptional":false},{"name":"\\[Optional\\] Props for particular chosen folk dance","isOptional":true}]} {sdgColor} />

	<CustomSection title={"Exploring Global Goal 3 Through Folk Dance"} content={"<strong>(45-70 MINUTES)</strong>"} {sdgColor} />

	<Introduction content={"<p>Briefly introduce the UN's Global Goal 3: \"Ensure healthy lives and promote well-being for all ages.\"<br>Explain that dance and movement are integral to human expression and well-being, connecting us to our bodies, emotions, and cultures.<br>Highlight the role of folk dance in preserving cultural heritage and promoting community cohesion, both vital aspects of well-being.<br>Introduce the specific folk dance that students will be learning and experiencing in this lesson. Examples:<br><em> </em>Mayim Mayim (Israel):<em> A circle dance celebrating water, symbolizing life and health.<br></em> <a href=\"https://www.youtube.com/watch?v=nsY3WWlK46A\" target=\"_blank\" rel=\"noopener noreferrer\">Reference Video</a><br><em> <a href=\"https://www.youtube.com/watch?v=YYEk0qalvsU\" target=\"_blank\" rel=\"noopener noreferrer\">Tutorial</a><br></em> <a href=\"https://www.youtube.com/watch?v=kxA4YKhHcWw\" target=\"_blank\" rel=\"noopener noreferrer\">Song Example</a><br><em> </em>Tinikling (Philippines):<em> A lively bamboo dance requiring agility and coordination, promoting physical fitness and teamwork.<br></em> <a href=\"https://www.youtube.com/watch?v=kckR6wf5xe8\" target=\"_blank\" rel=\"noopener noreferrer\">Reference Video</a><br><em> <a href=\"https://www.youtube.com/watch?v=1u-DJRCYwnI\" target=\"_blank\" rel=\"noopener noreferrer\">Tutorial</a><br></em> <a href=\"https://www.youtube.com/watch?app=desktop&amp;v=X4xXwJgiqNM\" target=\"_blank\" rel=\"noopener noreferrer\">Song Example</a><br><em> </em>Kolo (Balkans):<em> A circle dance with intricate footwork and patterns, encouraging focus, coordination, and community connection.<br></em> <a href=\"https://www.youtube.com/watch?v=QsP04zcZXys\" target=\"_blank\" rel=\"noopener noreferrer\">Reference Video</a><br><em> <a href=\"https://www.youtube.com/watch?v=HdcACqkWwg4\" target=\"_blank\" rel=\"noopener noreferrer\">Tutorial</a><br></em> <a href=\"https://www.youtube.com/watch?v=AAaZGsbbdsY\" target=\"_blank\" rel=\"noopener noreferrer\">Song Example</a></p>"} />

	<CustomSection title={"Learning About the Folk Dance"} content={"<p>Share the origin and cultural context of the chosen folk dance.<br><em> Dance and cultural traditions contribute to a sense of identity and belonging which are key components of mental and social well being.<br>Show images or videos of the dance being performed, highlighting key movements and formations.<br></em> The physicality of the dance \\- its energy, rhythm, and patterns \\- can promote physical fitness and coordination, contributing to overall health.<br>Discuss any symbolism or meaning behind the dance steps, costumes, or music.<br><em> These elements reflect cultural values and beliefs related to health, healing, and community celebrations.<br>Explain the cultural significance of the dance and its role in the community.<br></em> Dance can bring people together, fostering social connections and a sense of belonging, which are important for health and well being.</p>"} {sdgColor} />

	<CustomSection title={"Warm-up and Movement Exploration"} content={"<p>Lead students through a gentle warm-up, incorporating stretches and simple movements inspired by the chosen folk dances. Examples:<br><em> </em>Circle Stretches:<em> Have students form a circle, holding hands. Gentlys way side to side, mimicking the swaying motion often seen in folk dances. Then, raise arms overhead and reach for the sky, feeling a stretch in the sides of the body.<br></em> <em>Footwork Prep:</em> With feet shoulder-width apart, practice stepping side to side, then add a heel-toe tap in front. This mimics basic steps seen in dances like Irish jigs or the Kolo.<br><em> </em>Grapevine:<em> Teach the basic grapevine step (step side, cross behind, step side) and have students practice it moving across the room. This is a common step in various folk dances.<br></em> <em>Partnered Folk Dances:</em> In pairs, students face each other and gently swing their joined hands back and forth, or try a simple do-si-do (passing each other right shoulder to right shoulder, then back to back, then left to left). This warms up the body and builds connection for partnered folk dances<br>Play examples of the music that will accompany the chosen dance to familiarize students with the rhythms and styles.</p>"} {sdgColor} />

	<CustomSection title={"Learning Basic Steps"} content={"<p>Break down the basic steps and patterns of the folk dance, demonstrating them clearly and slowly.<br><em> Encourage students to focus on their body awareness and coordination, highlighting the benefits of physical activity for overall health.<br>Provide opportunities for students to practice the steps individually and in pairs, and potentially in a group.<br></em> Emphasize the importance of teamwork, cooperation, and mutual support, key aspects of social well-being.<br>Offer modifications or variations if needed.<br>Use positive reinforcement and encouragement to create a fun and inclusive learning environment.\n<ul>\n<li>Celebrate the joy of movement and the positive impact it can have on health and well being.</li>\n</ul></p>"} {sdgColor} />

	<CustomSection title={"Connecting Dance to Global Goal 3"} content={"<p>Divide students into three groups.<br><em> Each group will focus one one aspect of well being: Physical, Mental/Emotional, and Social.<br>Guide the groups to analyze how the folk dance they learned connects to their assigned aspect of well-being.<br></em> <em>Physical:</em> Focus on muscle groups used, energy expenditure, balance/coordination required.<br><em> </em>Mental/Emotional:<em> Discuss the mood of the music, any symbolism in the steps, and how the dance makes them feel.<br></em> <em>Social:</em> Examine how the dance structure (partnering, group formations, etc.) promotes connection, and how learning a dance from another culture fosters understanding.</p>"} {sdgColor} />

	<CustomSection title={"Creative Expression and Performance"} content={"<p>Each group will create a short movement phrase (30-60 seconds) highlighting their assigned well-being aspect, using elements from the folk dance.<br>Groups can add their own flair, change the music tempo, or use levels (high/low) to further express the theme.</p>"} {sdgColor} />

	<ReflectionQuestions questions={["How did learning and performing the folk dance make you feel physically, mentally, and emotionally?","What did you notice about the connection between the movements, the music, and the cultural context of the dance?","Did performing the dance with the group create a sense of connection or community? How did that contribute to your overall experience?","What emotions or ideas did the dance evoke in you in relation to the concept of a \"healthy life\" and \"wellbeing for all\"?","How did learning a dance from another culture broaden your understanding of different perspectives on health and wellbeing?","What aspects of the culture associated with the dance might reflect their values or beliefs about health, healing, or community?","How can appreciating and learning about cultural traditions like folk dance contribute to a sense of global citizenship and understanding the diverse ways people pursue wellbeing?","How can the preservation and sharing of cultural traditions like folk dance contribute to the overall wellbeing of communities?","What are some ways you can incorporate movement and/or dance into your own life to promote your physical, mental, and emotional wellbeing?","How might the collaborative and community-oriented nature of folk dance inspire you to connect with others and promote wellbeing in your own community?","How can we use dance and movement to promote well-being for ourselves and others?"]} {sdgColor} />

	<AssessmentCriteria criteria={["Consistent and enthusiastic involvement in all phases of the lesson, including the warm-up, learning basic folk dance steps, creative expression, group performance, and class discussions.","Comprehension of Global Goal 3 and its targets and core concepts (e.g., physical, mental/emotional, social wellbeing, cultural health) as demonstrated through the symbolism and intention within the movement pieces and verbal explanations.","Originality and effectiveness in using basic folk dance elements (e.g., formations, footwork patterns, group dynamics) to convey messages about health and wellbeing.","How clearly and powerfully the finished movement piece communicated its intended message about health and wellbeing. Did the dance successfully evoke thought or emotion in the audience?","Ability to work effectively within the small groups or pairs, contributing ideas, respecting diverse interpretations, and collaborating cohesively during choreography and performance.","Understanding and respectful portrayal of the cultural context of the chosen folk dance, and the ability to connect its traditional significance to modern concepts of health and wellbeing.","Nuance and depth of understanding demonstrated in reflections, particularly concerning the role of dance and cultural expression in promoting health."]} {sdgColor} />

</div>
