<script lang="ts">
	import MaterialsList from './components/MaterialsList.svelte';
	import ReflectionQuestions from './components/ReflectionQuestions.svelte';
	import AssessmentCriteria from './components/AssessmentCriteria.svelte';
	import CustomSection from './components/CustomSection.svelte';
	import { getSdgColor } from '$lib/utils/sdg-colors';

	interface Props {
		sdgColor?: string;
	}

	let { sdgColor = getSdgColor(3) }: Props = $props();
</script>

<div class="lesson-content">

	<MaterialsList materials={[{"name":"Open space for movement and improvisation","isOptional":false},{"name":"Whiteboard or large chart paper","isOptional":false},{"name":"Markers","isOptional":false},{"name":"[Emotion/Feeling Cards](https","description":"//docs.google.com/document/d/1L1rX21BDvhpnR2JYjt6oQY4KWMOv67ybiZqAErTOwpw/edit?usp=drive_link): Slips of paper with simple emotions that can be challenging (see attached examples that can be used, or create your own). Prepare enough for each group to draw one.","isOptional":false},{"name":"[Action Cards](https","description":"//docs.google.com/document/d/1C8f1BcXelnafb0-YkSn1Sx27Aam-befi92rshBOdj8w/edit?usp=drive_link): Slips of paper with simple, positive actions for supporting well-being (see attached examples that can be used, or create your own). Prepare enough for each group to draw one.","isOptional":false},{"name":"Notebooks or Paper","isOptional":false},{"name":"Pens/Pencils","isOptional":false},{"name":"\\[Optional\\] Simple props","description":"Scarves, hats, balls, notebooks, empty water bottles, etc. Easily accessible classroom items.","isOptional":true}]} {sdgColor} />

	<CustomSection title={"Feeling Strong: Drama for our Hearts and Minds"} content={"<strong>Introduction</strong><br>Introduce/re-introduce students to Global Goal 3: Good Health and Well-being.<br><em> This goal aims to make sure everyone, everywhere, has a healthy life and feels good, no matter their age. This means taking care of our bodies, but it also means taking care of our minds and hearts. It's okay to have big feeligns like worries or sadness, and it's super important to know how to manage them and how to help our friends.<br></em> That's what a big part of Global Goal 3 is about, promoting mental health and well-being.<br>Tell students that actors are incredible storytellers. They can use their voices, bodies, and imaginations to show feelings, problems, and amazing ways to feel strong and healthy inside.<br>Today, we will be actors, showing what it's like to have different feelings and how we can use helpful actions to feel good and support each other."} {sdgColor} />

	<CustomSection title={"Warm-Up: Emotion Sculptors"} content={"<p>Begin with a fun, active emotional warm-up to get everyone ready to act and explore feelings.<br><em> Let's get our bodies and faces ready to show feelings. When I call out an emotion, quickly freeze with your body and face in a way that shows feeling. Hold still\\! Then relax.<br></em> There's no right or wrong way to show a feeling, just try your best.<br><em> Examples of emotions to call out:<br></em> <em>Happy</em>: e.g. big smile, open arms, light jump, head held high, bouncy posture.<br><em> </em>Sad:<em> e.g. slumped shoulders, head down, quiet sigh, slow movement, a tearful face.<br></em> <em>Surprised:</em> e.g. wide eyes, open mouth, jumping back slightly, hands over mouth, stiff body.<br><em> </em>Confused:<em> e.g. furrowed brow, head tilted, shrugging shoulders, scratching head, slow uncertain steps.<br></em> <em>Excited:</em> e.g., bouncy steps, big smile, quick movements, clapping hands, jumping up and down.<br><em> </em>Worried:<em> e.g., worried face, hands clasped, shoulders hunched, looking down, fidgeting.<br></em> <em>Brave:</em> e.g., standing tall, chest out, firm stance, strong gaze, confident walk.<br><em> </em>Calm:<em> e.g., slow smooth movements, gentle smile, relaxed shoulders, soft breathing, peaceful expression.<br></em> Encourage full body expression and clear facial gestures. Keep it quick and fun.</p>"} {sdgColor} />

	<CustomSection title={"Emotion-Action Brainstorm"} content={"<p>Explain that we will be thinking about tricky feelings, and then the helpful actions that can make us feel better, or help our friends feel better.<br>Draw a large circle in the center of your whiteboard/paper and write \"My Feelings\".<br>Draw two main branches from the center:<br><em> </em>Tricky Feelings<em><br></em> Ask students: What are some tricky feelings that we sometimes have? How do they make us feel? Write these ideas using one color marker (e.g., red)<br>Examples:<br><em> Worried (like a knot in your stomach)<br></em> Sad (like a gray cloud)<br><em> Frustrated (like wanting to stomp your feet)<br></em> Shy (like wanting to disappear)<br><em> Confused (like a puzzle you can't solve)<br></em> Lonely (like no one's around)<br><em> Nervous (like butterflies are in your stomach)<br></em> Disappointed (like a popped balloon)<br><em> </em>Helpful Feelings<em><br></em> Ask students: What are some feelings that make us feel good and strong? Write these ideas using a different color marker (e.g., blue).<br>Examples:<br><em> Calm (like smooth water)<br></em> Happy (like sunshine)<br><em> Brave (like a superhero)<br></em> Peaceful (like a quiet forest)<br><em> Joyful (like jumping up and down with excitement)<br></em> Proud (like standing tall)<br><em> Loved (like a warm hug)<br></em> Confident (like you can do anything)<br><em> Now, for both types of feelings, draw lines from the feeling words to a new bubble: Actions to Help.<br></em> Ask students: When we have tricky feelings, or when we want to keep a helpful feeling strong, what are some actions we can take? What can we do to help a friend who has a tricky feeling?<br>Examples:<br><em> Talk to a grown-up<br></em> Talk to a friend<br><em> Take deep breaths<br></em> Draw/write about feelings<br><em> Ask for help<br></em> Spend time in nature (go outside)<br><em> Help someone else<br></em> Listen quietly<br><em> Share a laugh<br></em> Get a hug<br><em> Do something creative (sing/draw/dance/etc.)<br></em> Exercise/play<br><em> Read a good book<br></em> Get enough sleep<br><em> Eat healthy snacks<br></em> Do something kind for someone<br><em> Think happy thoughts<br></em> Ask a question to understand<br><em> Add these action items to the web.<br></em> Summarize: Our web shows that all feelings are okay, and there are many helpful actions we can take to feel strong and support each other's well-being.</p>"} {sdgColor} />

	<CustomSection title={"Group Scene Creation: Feeling Stories in Motion"} content={"<p>Divide students into small groups (3-4 students).<br>Each group will draw one <a href=\"https://docs.google.com/document/d/1L1rX21BDvhpnR2JYjt6oQY4KWMOv67ybiZqAErTOwpw/edit?usp=drive_link\" target=\"_blank\" rel=\"noopener noreferrer\">Feeling Card</a> and one <a href=\"https://docs.google.com/document/d/1C8f1BcXelnafb0-YkSn1Sx27Aam-befi92rshBOdj8w/edit?usp=drive_link\" target=\"_blank\" rel=\"noopener noreferrer\">Action Card</a>.<br>Explain that each group will create a short, mini play without words (like an old silent film) that lasts about 30 seconds to one minute.<br>Each scene needs to show:<br><em> </em>The Feeling:<em> Show a character experiencing the tricky feeling from the card chosen.<br></em> <em>The Helping Action:</em> Show how someone, or the character themselves, takes the helping action from the card chosen, and how it makes things better or shows support.<br>Encourage groups to think about:<br><em> </em>Characters:<em> Who are the people in the scene? What are their stories? Do they have names?<br></em> <em>Body Language and Facial Expressions:</em> How can they use their bodies and faces to show the feeling and the action clearly without words?<br><em> </em>Action:<em> What simple actions can they use to show the feeling and then theaction?<br></em> <em>Teamwork:</em> How does everyone in the group contribute to the scene and work together?<br><em> </em>Props \\[Optional\\]:<em> Can they use any simple classroom props?<br>Circulate among groups, offering guidance and encouragement. Ask guiding questions like:<br></em> How are you showing \\[feeling\\] with your body and face?<br><em> What simple actions can you use to show \\[action\\]?<br></em> Does your scene show a change from the feeling to feeling better?<br><em> How can your characters interact to show kindness and support?<br></em> Are you thinking about the beginning (feeling) and the end (action) of your short play/story?</p>"} {sdgColor} />

	<CustomSection title={"Our Feeling Stories"} content={"<p>Have each group perform their short scene for the class. Remind the audience to be respectful and quiet, focusing on the story and feelings being told.<br>After each performance, invite the audience to share and discuss. Ask guiding questions like:<br><em> What tricky feeling did you see the character having?<br></em> What helping action did you see happening?<br><em> What story or message about feelings did their scene tell?<br></em> What emotions did the scene make you feel?<br>Invite the peforming group to quickly explain the intended message.</p>"} {sdgColor} />

	<ReflectionQuestions questions={["How did acting out scenes about tricky feelings and helpful actions help you understand what it means to be healthy and well inside your mind and heart?","What did you learn about how our feelings can change, and how we can use different actions to feel better or help our friends feel better?","Which scenes or ideas from your classmates made you think or feel the most about mental well-being, and why?","What does our \"Feeling Strong\" activity tell us about how we can all work towards Global Goal 3, especially by supporting each other's feelings?","What's one small thing you can do this week to take care of your own mind or feelings, or to help a friend do the same, inspired by our drama today?"]} {sdgColor} />

	<AssessmentCriteria criteria={["Consistent and enthusiastic involvement in all phases of the lesson, including the warm-up, brainstorm, group scene creation, and active participation in class discussions (both performing and observing).","Understanding of the core concept of mental and emotional well-being within Global Goal 3, as demonstrated through the content and message of the scenes and verbal explanations.","Originality and effectiveness in using dramatic techniques (e.g., character portrayl, body language, facial expressions, clear actions) to vividly represent a tricky feeling and a corresponding helping action. Look for clear effort in expressing feelings and concepts without words.","Ability to work effectively within the small groups, contributing ideas, respecting diverse interpretations, and collaborating cohesively to create and perform the scenes.","Ability to articulate learning and personal connections during the reflection and summary discussion."]} {sdgColor} />

</div>
