<script lang="ts">
	import MaterialsList from './components/MaterialsList.svelte';
	import Introduction from './components/Introduction.svelte';
	import ReflectionQuestions from './components/ReflectionQuestions.svelte';
	import AssessmentCriteria from './components/AssessmentCriteria.svelte';
	import CustomSection from './components/CustomSection.svelte';
	import { getSdgColor } from '$lib/utils/sdg-colors';

	interface Props {
		sdgColor?: string;
	}

	let { sdgColor = getSdgColor(1) }: Props = $props();
</script>

<div class="lesson-content">

	<MaterialsList materials={[{"name":"Slips of Paper with Themes (examples below)","isOptional":false},{"name":"Optional Props","description":"chairs, tables, scarves/blankets/cloth, cardboard, books, pens/pencils, bowls/plates, signs, etc.","isOptional":true},{"name":"Whiteboard or large chart paper","isOptional":false},{"name":"Markers","isOptional":false},{"name":"Notebooks or Paper","isOptional":false},{"name":"Pens/Pencils","isOptional":false},{"name":"Prepared Theme Slips","description":"Write out pairs of ideas (one challenge \\+ one hope) each one one slip of paper. For example:","isOptional":false},{"name":"Pair 1","description":"A child can't go to school / Children learning together happily","isOptional":false},{"name":"Pair 2","description":"Someone feeling hungry / Friends sharing a meal","isOptional":false},{"name":"Pair 3","description":"A family needing a home / Neighbors helping to build a home","isOptional":false},{"name":"Pair 4","description":"Someone feeling lonely / A community welcoming new friends","isOptional":false},{"name":"Pair 5","description":"Someone needing clean water / A community sharing clean water","isOptional":false},{"name":"Pair 6","description":"Feeling unsafe in a neighborhood / Friends playing safely together","isOptional":false},{"name":" Prepare enough pair so each group gets one set.","isOptional":false}]} {sdgColor} />

	<CustomSection title={"Freeze Frame for Fairness: Creating Living Pictures for Global Goal 1"} content={"<strong>(15-30 MINUTES)</strong>"} {sdgColor} />

	<Introduction content={"<p>Welcome students to a drama activity. Explain that today, they are going to become \"living pictures\" to explore a really important idea: Global Goal 1: No Poverty.<br><em> Discuss how Global Goal 1 is a commitment to work towards everyone, everywhere, having what they need to live a healthy and happy life.<br></em> This means having enough food, a safe home, clean water, clothes, and a chance to go to school and feel healthy and happy. It's about fairness and making sure no one is left behind.<br>Introduce Tableau Vivant:<br><em> A fancy French term to \"living picture.\"<br></em> It means you'll work in small groups to create a frozen scene \\- like a photograph \\- using only your bodies, facial expressions, and any props you find.<br><em> You won't use any words.<br></em> This is a powerful way to tell a story or show a feeling without speaking.\n<ul>\n<li>Think of it as a silent movie where you are the actors, showing big ideas with just one powerful moment.</li>\n</ul></p>"} />

	<CustomSection title={"Our Living Pictures"} content={"<p>Explain to students:<br><em> We're going to make a list of things every person needs, and then think about what happens when they don't have them, and how people can help. This will give us some great ideas for our \"living pictures\"\\!<br>Draw two columns on the whiteboard or paper. Label the first column \"Things Everyone Needs\" and the second column \"When Needs Aren't Met (Challenges) / How People Help (Solutions).<br>Ask:<br></em> What are some of the most important things every person needs to be happy and healthy?<br>Write these ideas under \"Things Everyone Needs\" using one color marker (e.g., blue).<br><em> </em>Examples:<em> Food, clean water, a safe home, clothes, school/learning, feeling safe, kindness/friends, doctors/medicine.<br>Now, for each item in the \"Things Everyone Needs\" column, ask two questions about record the answers in the second column using different colors (e.g., red for challenges, green for solutions).<br></em> For \"Food\":<br><em> What does it look, sound, or feel like if someone doesn't have enough food? (e.g., empty fridge tummy rumbling, feeling tired, looking sad, can't focus).<br></em> What does it look, sound, or feel like when people help someone get food? (e.g., sharing a meal, a food drive, a community garden, smiles, full tummies, happy sounds).<br><em> For \"Safe Home\":<br></em> What does it look, sound, or feel like if someone doesn't have a safe home? (e.g., cold, scared, nowhere to sleep, leaky roof, noisy, no privacy).<br><em> What does it look, sound, or feel like when people help someone find a safe home? (e.g., building together, warm blankets, welcoming hands, smiling faces, quiet, safe space).<br></em> For \"School/Learning\":<br><em> What does it look, sound, or feel like if a child doesn't get to go to school? (e.g., empty classroom, sad child, no books, feeling left out, can't learn new things).<br></em> What does it look, sound, or feel like when people help a child go to school? (e.g., books, smiling teacher, happy friends,  learning, sharing ideas, feeling smart).<br><em> For \"Feeling Safe\":<br></em> What does it look, sound, or feel like if someone doesn't feel safe? (e.g., hiding, scared, worried, looking around nervously, dark, loud noises).\n<ul>\n<li>What does it look, sound, or feel like when people help someone feel safe? (e.g., huge, strong hands, friends protecting, calm, peaceful, smiling faces).</li>\n</ul><br>This dual listing provides a direct vocabulary for creating contrasting tableaux.</p>"} {sdgColor} />

	<CustomSection title={"Creating Our Tableaux"} content={"<p>Divide students into small groups (3-4 students per group).<br>Each group will draw one slip of paper. Explain that the slip has two tableau ideas on it.<br><em> Idea 1: \"The Challenge\"<br></em> This will be a frozen picture showing a problem or a need that someone might have (drawing inspiration from the \"Challenges\" part of our brainstorm).<br><em> Idea 2: \"The Hope/Action\"<br></em> This will be a different frozen picture showing how that challenge can be met with kindness, sharing, or community support (drawing inspiration from the \"Solutions\" part of our brainstorm).<br>Give groups 5-10 minutes to plan and practice their two tableaux.<br>Encourage students to think about:<br><em> </em>Bodies:<em> How can their bodies show the emotion or situation? (e.g., slumped shoulders for sadness, open arms for welcome, hands reaching out for help).<br></em> <em>Facial Expressions:</em> How can their faces show what the characters are feeling? (e.g., worried, hopeful, tired, happy).<br><em> </em>Levels:<em> Can they use different levels (standing tall, crouching low, sitting)?<br></em> <em>Props (Optional):</em> Can they use any classroom props to make their picture clearer? (e.g., a chair for home, a book for school, a scarf as a blanket).<br>Remind students that the pictures are silent.<br>Circulate among groups, offering encouragement and guidance. Ask guiding questions like:<br><em> What big idea about Global Goal 1 are you trying to show in this picture?<br></em> How are your bodies showing the feeling of (hunger/hope/sharing)?<br><em> What message do you want the audience to understand without you speaking?<br></em> How is everyone in the group contributing to the picture?<br><em> How can your facial expressions make the feeling even stronger?<br></em> Are you thinking about what the audience will see when they look at your frozen picture?\n<ul>\n<li>How do your two pictures show a \"before\" and \"after\" or a \"problem\" and a \"solution\"?</li>\n</ul></p>"} {sdgColor} />

	<CustomSection title={"Presenting Our Living Pictures"} content={"<p>Gather the class to watch each group's tableaux. Remind the audience to be silent and focus on what they see.<br>Have each group present their first tableau (\"The Challenge\") silently, holding the pose for about 5-10 seconds.<br>Then, have them immediately transition to their second tableau (\"The Hope/Action\"), holding that pose silently for another 5-10 seconds.<br>After both tableaux, invite the audience to share their observations. Ask guiding questions like:<br><em> What did you see in the first picture? What feelings did it show?<br></em> What did you see in the second picture? What changed? What feelings did it show?<br><em> How did the two pictures tell a story together, without words?<br>The presenting group can also be invited to explain their intended message and artistic choices. Ask guiding questions like:<br></em> What was the challenge your group wanted to show in the first picture?<br><em> What was the hope or action you showed in the second picture?<br></em> Why did you choose those body positions or facial expressions?\n<ul>\n<li>How does your \"living picture\" connect to Global Goal 1: No Poverty?</li>\n</ul></p>"} {sdgColor} />

	<CustomSection title={"Cool Down"} content={"<p>Lead a gentle cool-down, encouraging students to focus on their breathing and release any tension. Play calming music.<br>Examples of cool-down movements with guiding prompts:<br><em> </em>Deep Breathing:<em> Lie down or sit comfortably. Take a slow, deep brath in, feeling your belly rise. Now, breathe out slowly, letting all your worries and tensions go. Imagine breathing in calm and peace, feeling your body relax. (Focus on diaphragmatic breathing, deep sighs).<br></em> <em>Gentle Stretching:</em> Slowly stretch your arms up towards the sky, then gently reach for your toes. Feel your body release any tightness or stiffness. Imagine your body becoming light and relaxed, like a soft cloud. (Simple stretches for arms, legs, back, neck rolls).<br><em> </em>Mindfulness Walk:<em> Gently walk around the space, noticing each step. Feel your feet on the ground. Be present in this moment, noticing the quiet and calm around you. What does it feel like to move slowly and peacefully? (Quiet, slow walking, focusing on footfalls).<br></em> <em>Tree Post (Modified):</em> Stand tall and strong like a tree, rooted to the ground. Feel your balance. Imagine being strong and resilient, just like a tree that can weather any storm, stable and peaceful. (Balance on one foot, other foot resting on ankle or calf, arms extended or at prayer position, focus on stillness).<br><em> </em>Visualization:* Close your eyes (if comfortable). Imagine a world where everyone has what they need, where people are kind and helpful to one another. See happy faces, hear joyful sounds. Feel the warmth of a peaceful and fair world all around you, knowing you can be a part of it. (Guided visualization, focusing on positive imagery).</p>"} {sdgColor} />

	<ReflectionQuestions questions={["How did creating and watching these \"living pictures\" help you understand Global Goal 1: No Poverty in a new way?","What did you learn about how people might feel when they need help, or when they are helping others, through our silent scenes?","Which tableaux made you think or feel the most, and why?","What does our \"Freeze Frame for Fairness\" activity tell us about how we can all work together to make sure everyone has what they need?","What's one small thing you can do in your own life today to show kindness or help someone who might need something?"]} {sdgColor} />

	<AssessmentCriteria criteria={["Consistent and enthusiastic involvement in all phases of the lesson, including the brainstorming, group tableau creation, and active participation in class discussions (both presenting and observing).","Understanding of the core concept of Global Goal 1, as demonstrated through the symbolism and intention in the two tableaux and verbal explanations.","Originality and effectiveness in designing and performing frozen pictures that vividly representing a challenge and a corresponding hope/action related to \"No Poverty,\" using only bodies, facial expressions, and props. Look for clear effort in expressing the feeling and concept without words.","Ability to work effectively within the small groups, contributing ides, respecting diverse interpretations, adn colalboratin cohesively to crate the tableaux.","Ability to articulate learning and personal connections during the reflection and summary discussion."]} {sdgColor} />

</div>
