<script lang="ts">
	import MaterialsList from './components/MaterialsList.svelte';
	import Introduction from './components/Introduction.svelte';
	import ReflectionQuestions from './components/ReflectionQuestions.svelte';
	import AssessmentCriteria from './components/AssessmentCriteria.svelte';
	import CustomSection from './components/CustomSection.svelte';
	import { getSdgColor } from '$lib/utils/sdg-colors';

	interface Props {
		sdgColor?: string;
	}

	let { sdgColor = getSdgColor(8) }: Props = $props();
</script>

<div class="lesson-content">

	<MaterialsList materials={[{"name":"Paper or notebooks","isOptional":false},{"name":"Pens/pencils","isOptional":false},{"name":"Whiteboard or large chart paper","isOptional":false},{"name":"Markers","isOptional":false},{"name":"\\[Optional\\] Images or videos related to various jobs (e.g., a farmer, a builder, a teacher, a doctor, someone creating new tech, a healthy bustling market, etc.)","isOptional":true}]} {sdgColor} />

	<CustomSection title={"Haiku for Humans: Tiny Words for Big Work"} content={"<strong>(30-60 MINUTES)</strong>"} {sdgColor} />

	<Introduction content={"<p>Welcome students to an exciting creative writing class. Explain that they will use their words and imagination to explore a really important idea: Global Goal 8, Decent Work and Economic Growth.<br>Clarify that Global Goal 8 is like a huge promise the world has made: a promise to make sure everyone, everywhere, has a good job \\- one that is fair, safe, and where they are treated with respect. Emphasize that it's also about helping communities and countries grow stronger in a way that helps everyone and doesn't harm our planet. This means jobs that are safe, pay fairly, and help the world be a better place.<br>Introduce the art of Haiku poetry.<br><em> Explain that Haiku is a special kind of short poem that comes from Japan.<br></em> Haiku has three lines, and each line has a specific number of syllables: 5 in the first line, 7 in the second line, and 5 in the third. (5-7-5)<br><em> Clarify that even though Haiku is short, it can capture a big idea or a strong feeling, like a snapshot with words.<br>Model a few Haiku examples related to common experiences or simple observations to illustrate the 5-7-5 structure and the \"snapshot\" idea.<br>Examples:<br></em> <em>About Nature (Traditional Inspiration)</em><br><em> Green grass softly grows </em>(5)<em><br>Sun shines on the gentle breeze </em>(7)<em><br>Warm summer day now </em>(5)<em><br></em> <em>About School (Relatable)</em><br><em> Pencils quickly write </em>(5)<em><br>New ideas fill up my brain </em>(7)<em><br>Learning feels so good </em>(5)<em><br></em> <em>About Global Goal 8</em><br><em> Hard work fills the day </em>(5)<em><br>Fair pay makes a happy smile </em>(7)<em><br>Growth for everyone </em>(5)<em><br></em> Safe tools in my hands <em>(5)</em><br>Building strong things for our town <em>(7)</em><br>Proud of what we do <em>(5)</em><br><em> Green factories hum </em>(5)<em><br>Clean jobs health the Earth grow strong </em>(7)<em><br>Future shines so bright </em>(5)*<br>Explain that even short poems like haikus can hold big messages about important topics like jobs and growth.</p>"} />

	<CustomSection title={"Warm Up: Word Count Challenge"} content={"<p>Introduce the Word Count Challenge to warm up for Haiku. In this warm up, students will be given a simple topic, and they will have to describe it using exactly 5 or 7 words.<br>Instruct students to take a piece of scrap paper and a pen/pencil, and that they will have to be ready to quickly write down words for each challenge.<br><em>Challenge 1: Describe a Sunny Day</em><br><em> Say: In exactly 5 words, describe a sunny day.<br></em> E.g., Bright, warm sun shines down.<br><em>Challenge 2: Describe a Favorite Food</em><br><em> Say: In exactly 7 words, describe your favorite food.<br></em> E.g., Cheesy, warm pizza tastes so good.<br><em>Challenge 3: Describe a Sport/Game: In exactly 5 words, describe a sport or game.</em><br><em> Say: In exactly 5 words, describe a sport or game.<br></em> E.g., Running fast with friends.<br>Have a few students share their responses after each challenge.<br>Conclude the warm up by affirming the students' conciseness and creativity, as the skills they just used are key for Haiku.</p>"} {sdgColor} />

	<CustomSection title={"Haiku Idea Shuffle"} content={"<p>On the whiteboard/large paper, make two columns.<br><em>Column 1: Job Aspects (What parts of a job or growth are you thinking about?)</em><br>Examples of ideas for this column<br><em> The worker feels…<br></em> The workplace looks…<br><em> Our community grows…<br></em> The challenge is…<br><em> The solution is…<br></em> A good job has…<br><em> The Earth's work…<br></em> New ideas bloom…<br><em>Column 2: Focus Words (What feelings or ideas about good jobs/growth do you want to show?)</em><br>Examples of ideas for this column<br><em> Strong<br></em> Fair<br><em> Busy<br></em> Clean<br><em> Problem<br></em> Hope<br><em> Together<br></em> Safe<br><em> Proud<br></em> Learn<br><em> Grow<br></em> Help<br><em> Kind<br></em> New<br><em> Bright<br></em> Planet<br><em> Future<br></em> Everyone<br><em> Respect<br>Instruct students (either individually or in pairs) to choose one phrase from the Job Aspects column, and one word from the Focus Words column that they think fit or are interesting together. These are their spark words.<br>Now, have students use those words to brainstorm a short phrase that is either 5 or 7 syllables long (their choice).<br>Examples<br></em> Student chooses: \"The worker feels…\" and \"Proud\".<br><em> </em>5 Syllables:<em> Worker feels so proud.<br></em> <em>7 Syllables:</em> Proud worker helps our town.<br><em> Student chooses: \"The challenge is…\" and \"Problem\".<br></em> <em>5 Syllables:</em> Jobs are a problem.<br><em> </em>7 Syllables:<em> Unfair problems make jobs hard.<br></em> Student chooses: \"The Earth's work…\" and \"Clean\".<br><em> </em>5 Syllables:<em> Earth needs clean jobs now.<br></em> <em>7 Syllables:</em> A cleaner Earth works for us.<br><em> Student chooses: \"New ideas bloom…\" and \"Bright\".<br></em> <em>5 Syllables:</em> Bright ideas bloom fast.<br><em> </em>7 Syllables:<em> New bright ideas bloom now.<br></em> Student chooses: \"The workplace looks…\" and \"Safe\".<br><em> </em>5 Syllables:<em> Workplace looks so safe.<br></em> <em>7 Syllables:</em> Safe workplace helps us grow.<br><em> Student chooses: \"A good job has…\" and \"Respect\".<br></em> <em>5 Syllables:</em> Good job has respect.<br><em> </em>7 Syllables:<em> Respect in good job always.<br>Emphasize that the goal is to generate many short, themed phrases quickly.<br>Circulate, offering guidance and asking guiding questions like:<br></em> How can you make that line exactly 5 syllables?<br><em> What Focus Word helps show the feeling of \\[Job Aspect\\]?<br></em> Can you think of an action word for your line?</p>"} {sdgColor} />

	<CustomSection title={"Haiku Creation: Our Decent Work Haikus"} content={"<p>Explain that each student will write a Haiku poem about Global Goal 8, using ideas from and inspired by the Haiku Idea Shuffle brainstorm.<br>Encourage students to pick a specific \"snapshot\" or feeling about jobs and growth that they want to capture. They can write about:<br><em> What a good, fair job looks/feels like.<br></em> A challenge at work or with growth.<br><em> A solution or hope for better work/growth.<br></em> How everyone works together for growth.<br>Remind students of the 5-7-5 structure. Encourage them to:<br><em> </em>Use vivid words:<em> Make the reader see or feel the Haiku.<br></em> <em>Be concise:</em> Every word counts.<br><em> </em>Count syllables carefully:<em> Tap your chin or count on your fingers for each syllable.<br>Provide specific writing prompts if needed. Examples:<br></em> Write a Haiku about…<br><em> a farmer working safely in the sun.<br></em> a challenge in a factory, or a solution.<br><em> a child who can finally go to school instead of work.<br></em> new ideas making jobs better.<br><em> how everyone helps a business grow.<br></em> a busy, fair marketplace.<br><em> a job that helps the environment.<br></em> how fair pay makes a difference.<br>Circulate, offering support and guidance as the class writes. Ask guiding questions like:<br><em> Are you counting your syllables?<br></em> How can you make this feeling stronger with fewer words?\n<ul>\n<li>What Job Action can you describe in 7 syllables?</li>\n</ul></p>"} {sdgColor} />

	<CustomSection title={"Gallery Walk: Haiku Showcase"} content={"<p>Have students post their Haiku poems around the classroom, on the walls or on tables/desks.<br>Explain the purpose of the gallery walk: to appreciate each other's concise writing and gain different perspectives on Global Goal 8\\.<br>Instruct students to quietly walk around, reading the Haikus.<br>Instruct students to pay attention to:<br><em> Which Haiku captures a strong picture or feeling about jobs/growth?<br></em> Does the Haiku follow the 5-7-5 rhythm? Can you hear it when you read it quietly?<br><em> What message about Global Goal 8 does the Haiku give you?<br></em> Does the Haiku make you think about a job you know, or a new type of job?<br><em> What kind of person do you imagine wrote this Haiku? What feelings do they have about work?<br></em> How does such a short poem make you think about a big idea?<br>Invite volunteers to share one Haiku they saw (not their own) that resonated with them. Have the student read that Haiku aloud and explain why it stood out or what message they interpreted.<br>Facilitate a class discussion, asking guiding questions like:<br><em> What common ideas or feelings about decent work and economic growth did you find in the Haiku?<br></em> Did any Haiku surprise you or make you think about a job or a problem in a new way?<br><em> Hoe did using such short poems make the message about Global Goal 8 powerful?<br></em> What did you learn about putting big ideas into small packages?<br><em> How did the Haikus show both the challenges and the hopes for jobs and growth?<br></em> Were there any Haikus that showed both a problem and solution?</p>"} {sdgColor} />

	<CustomSection title={"Cool Down: Collective Haiku Reflection"} content={"<p>Explain that the students will write one last Haiku (or two depending on class size) about Global Goal 8, this time as a class.<br>The class will go around the room (or circle) and each student will add one word to build the poem's lines. The poem can be written on the board/large paper while it is being created so the class can remember what they just made together.<br>Emphasize that listening and counting syllables is very important.<br><em>Line 1 (5 syllables):</em> Start by saying the first word (e.g. \"Good\"), or let a student start. Then go around the class, each student adding one word until the line has exactly 5 syllables. Count the syllables aloud if helpful.<br><em> </em>Example: Starter Word:<em> Good → </em>Student 1:<em> jobs → </em>Student 2:<em> help → </em>Student 3:<em> us → </em>Student 4: grow.<em><br></em>Line 2 (7 syllables):<em> Then move to the next student in sequence. They will add one word to start the second line, and the class continues adding one word each, building to 7 syllables.<br></em> <em>Example: Student 5:</em> Fair → <em>Student 6:</em> work → <em>Student 7:</em> makes → <em>Student 8:</em> people → <em>Student 9:</em> proud —\\&gt; <em>Student 10:</em> each → <em>Student 11:</em> day.<br><em>Line 3: (5 syllables):</em> Move to the next student. They add one word to start the third line, and the class continues adding words to reach 5 syllables, completing the Haiku.<br><em> </em>Example: Student 12:<em> earth → </em>Student 13:<em> shines → </em>Student 14:<em> so → </em>Student 15:<em> bright.<br>Read the completed class Haiku aloud. Create a second one if needed and time allows.<br>Example:<br></em> Good jobs help us grow<br>Fair work makes people proud each day<br>Earth shines so bright.</p>"} {sdgColor} />

	<ReflectionQuestions questions={["How did writing short Haiku poems help you understand Global Goal 8: Decent Work and Economic Growth in a new way?","What did you learn about how jobs and economies can be complex, and how Haiku can capture big ideas in small ways?","Which Haikus or ideas from your classmates made you think or feel the most about jobs and growth, and why?","What do these activities tell us about how we can all work towards Global Goal 8?","What's one small action you feel inspired to take this week to be fair in your own work (like homework or chores or support good work in your community?"]} {sdgColor} />

	<AssessmentCriteria criteria={["Consistent and enthusiastic involvement in all phases of the lesson, including the warm up, brainstorm, individual Haiku writing, and class discussions.","Understanding of the core concept of decent work and economic growth (fair jobs, safe workplaces, sustainable growth), as demonstrated through the thematic content and concise imagery in the Haiku poems and verbal explanations.","Originality and effectiveness in crafting Haiku poems. Look for evidence of adherence to structure (does the Haiku follow the 5-7-5 syllable count accurately?), connection to Global Goal 8 (does the Haiku clearly capture an idea related to decent work or economic growth?), and conciceness and imagery (does the Haiku use precise words to create a vivid \"snapshot\" or feeling?).","Ability to articulate learning and personal connections during the reflection and summary discussion."]} {sdgColor} />

</div>
