<script lang="ts">
	import MaterialsList from './components/MaterialsList.svelte';
	import ReflectionQuestions from './components/ReflectionQuestions.svelte';
	import AssessmentCriteria from './components/AssessmentCriteria.svelte';
	import CustomSection from './components/CustomSection.svelte';
	import { getSdgColor } from '$lib/utils/sdg-colors';

	interface Props {
		sdgColor?: string;
	}

	let { sdgColor = getSdgColor(3) }: Props = $props();
</script>

<div class="lesson-content">

	<MaterialsList materials={[{"name":"Simple instruments (based on the class and skill level, can be 100% simple percussion or even improvised instruments).","isOptional":false},{"name":"Audio","isOptional":false},{"name":"Whiteboard or large chart paper","isOptional":false},{"name":"Markers","isOptional":false},{"name":"Notebooks or Paper","isOptional":false},{"name":"Pens/Pencils","isOptional":false},{"name":"[Health Challenge Cards](https","description":"//docs.google.com/document/d/1fomgXcuLAT8jncOhaTmQ9jMhUYCkd_VP-LaJuf8xihM/edit?usp=drive_link): Slips of paper with simple health challenges to spark the beginning of a story. (see attached examples that can be used, or create your own). Prepare enough for each group to draw one.","isOptional":false}]} {sdgColor} />

	<CustomSection title={"Healthy Beats"} content={"<strong>Introduction</strong><br>Welcome students to an exciting music lesson \\- we're going to use the power of music and rhythm to explore the important idea of Global Goal 3: Good Health and Well-being.<br><em> This goal aims to make sure everyone, everwhere, has a healthy life and feels good, no matter their age. Today, we're going to focus on a super important part of staying healthy: everyone getting the care they need.<br></em> This means that when you're sick or hurt, you can get help from doctors and nurses, and get the medicine you need, no matter where you live or how much money your family might have.\n<ul>\n<li>It's about making sure health care is fair and available for everyone.</li>\n</ul><br>Talk to students about how music can make us feel strong, determined, or even help us understand big challenges. Today, we'll use sound, music, and rhythms to create musical stories that show what it's like to need help and how we can find musical ways to show solutions for a healthier world where everyone gets care\\!"} {sdgColor} />

	<CustomSection title={"Sound and Movement Mirror"} content={"<p>Introduce the Sound and Movement Mirror to the class.<br><em> Make a sound and a simple movement. The students will then copy or \"mirror\" that sound and movement exactly.<br></em> Then, the next person will create their own sound and movement for the class to mirror. (Or, can continue to mirror multiple sound and movement from the educator).</p>"} {sdgColor} />

	<CustomSection title={"Care Access Chord Chart Brainstorm"} content={"<p>Explain the activity:<br><em> We're going to create a Care Access Chord Chart on the board/paper. We'll think about musical sounds and rhythms for different parts of a story about getting healthcare \\- from needing help to getting well.<br>Draw three large, connected bubbles or boxes on the whiteboard/paper, like a flow chart:<br></em> <em>Needing Care/Challenge Sounds:</em><br><em> What sounds or rhythms would you use to show someone needing medical help but maybe not getting it easily? What does that feel like musically? Write these ideas in the correct section using one color marker (e.g., red).<br>Examples:<br></em> Slow, dragging rhythm<br><em> Quiet, worried whispers<br></em> A single, long held note that feels sad<br><em> A quiet cough sound (vocals)<br></em> A fast, shaky beat<br><em> A \"no\" sound (vocals)<br></em> A feeling of slowness or quietness in the music<br><em> A heavy thud<br></em> A worried sigh<br><em> A searching sound with shakers<br></em> <em>Journey to Care/Action Sounds:</em><br><em> What sounds or rhythms show someone trying to get help, or people working to bring help? What's the journey sound? Write these ideas in the correct section using a neutral color marker (e.g., black).<br>Examples:<br></em> A steady, walking beat (like someone traveling)<br><em> A determined drum rhythm<br></em> Sounds of searching (shakers)<br><em> A calling sound<br></em> Sounds of a vehicle<br><em> A knocking sound<br></em> A getting ready or preparing sound (using various instruments)<br><em> </em>Recieving Care/Solution Sounds:<em><br></em> What sounds or rhythms happen when someone gets the help they need and starts to feel better? What does geting care and feeling well sound like? Write these ideas in the correct section using a positive color marker (e.g., blue).<br>Examples:<br><em> A steady, strong heartbeat (drum)<br></em> Gentle, calm hums<br><em> Cheerful laughter<br></em> Light, bouncy rhythms<br><em> A clear, high \"ding\" (like a bell)<br></em> Sounds of playing<br><em> A happy \"yes\\!\" sound<br></em> Bright energetic music\n<ul>\n<li>Joyful harmonies</li>\n</ul></p>"} {sdgColor} />

	<CustomSection title={"Songs of Care and Connection"} content={"<p>Explain that music can tell powerful stories, and that the class is going to listen to a couple of songs that talk about helping others, being strong, or finding connections.<br>Have students notice how the music makes them feel, and how the words, sounds, and rhythm tell a story.<br>Play one to two age appropriate songs with themes of kindness, community, or overcoming challenges. Focus on simple positive messages.<br>Examples:<br><em> <a href=\"https://www.youtube.com/watch?v=6k8cpUkKK4c\" target=\"_blank\" rel=\"noopener noreferrer\">\"Count on Me\" by Bruno Mars</a> (friendship, support)<br></em> <a href=\"https://www.youtube.com/watch?v=0hG-2tQtdlE\" target=\"_blank\" rel=\"noopener noreferrer\">\"You've Got a Friend in Me\" by Randy Newman</a> (friendship, care)<br><em> <a href=\"https://www.youtube.com/watch?v=HNBCVM4KbUM\" target=\"_blank\" rel=\"noopener noreferrer\">\"Three Little Birds\" by Bob Marley</a> (hope, positivity)<br></em> <a href=\"https://www.youtube.com/watch?v=fOZ-MySzAac\" target=\"_blank\" rel=\"noopener noreferrer\">\"Lean on Me\" by Bill Withers</a> (support, community)<br>After the song(s), facilitate a brief discussion. Ask guiding questions like:<br><em> What was the main message of this song about helping or caring?<br></em> How did the music make you feel?\n<ul>\n<li>Did any words or sounds in the song remind you of our Chord Chart?</li>\n</ul></p>"} {sdgColor} />

	<CustomSection title={"Our Health Anthem Verse"} content={"<p>Divide students into small groups (3-4 students). Provide each group with a few simple percussion instruments (or different instruments if available and appropriate for skill set), or remind them they can use body percussion/improvised instruments.<br>Explain that each group will create a short musical verse (about 30-45 seconds long) that tells a story about Global Goal 3, using sounds and rhythms from our Care Access Chord Chart.<br>The verse will show:<br><em> </em>A Challenge:<em> Start with sounds from Needing Care.<br></em> <em>The Journey:</em> Show sounds from Journey to Care.<br><em> </em>The Solution:<em> End with sounds from Receiving Care.<br>Distribute Health Challenge Cards to each group (one card per group). This gives a specific challenge to start their story. They then create their own \"journey\" and \"solution.\"<br>Encourage groups to think about:<br></em> <em>Their story:</em> How will they show the challenge on the card, the journey and the solution?<br><em> </em>Instruments/sound:<em> Which sounds from the brainstorm best fit each part of their story?<br></em> <em>Musical Elements:</em> How cna they use changes in dynamics (loud/soft), tempo (fast/slow), and rhythm (steady/uneven), to show the progression from challenge to solution?<br><em> </em>Collaboration:<em> How will everyone in the group contribute to all parts of the musical story?<br>Circulate among groups, offering guidance and encouraging creativity. Ask guiding questions like:<br></em> How can you use \\[instrument\\] to make the sound of \\[insert sound here\\]?<br><em> Can you make your rhythm sound more \\[worried/determined/joyful/etc.\\]?<br></em> How can your group's sounds blend together to create a feeling of help and healing?\n<ul>\n<li>What's one special sound your group can make with your voices or bodies that fits your stories solution?</li>\n</ul></p>"} {sdgColor} />

	<CustomSection title={"Performances: Our Health Anthems"} content={"<p>Have each group perform their musical piece for the class. Remind the audience to listen carefully and try to hear the story and feelings being told.<br>Before each group performs, invite the performing group to share their intended message.<br>After each performance, invite the audience to share in discussion. Ask guiding questions like:<br><em> What challenges did you hear in the first part of their music?<br></em> What journey did you hear in the middle?<br><em> What solution or positive change did you hear in the last portion?<br></em> What emotions did their music make you feel?</p>"} {sdgColor} />

	<ReflectionQuestions questions={["How did making music and sounds help you understand what it means for everyone to have access to doctors and medicine?","What did you learn about how different sounds and rhythms can show big feelings like worry, hope, or getting well?","Which musical pieces today made you think or feel the most about access to healthcare for everyone, and why?","What does our Healthy Beats activity tell us about how we can all work together to make sure everyone has waht they need to stay healthy?","What's one small thing you can do in your own life today to help with healthy living or supporting others' health, perhaps inspired by the music we made or heard?"]} {sdgColor} />

	<AssessmentCriteria criteria={["Consistent and and enthusiastic involvement in all phases of the lesson, including the warm-up, brainstorm, group music creation, and class discussions.","Understanding of the core concept of access to healthcare within Global Goal 3, as demonstrated through the sounds, rhythms, and message in the musical pieces (showing challenge/journey/solution) and the verbal contributions during discussions.","Originality and effort in crafting musical pieces. Look for evidence of connection to Global Goal 3.8 (does the music clearly relate to the challenge of getting care, the journey, and the solution?), and use of elements (are there attempts to use musical elements like rhythm, dynamics, sound choices, and simple vocalizations, to convey the chosen story?).","Ability to work effectively within the small groups, contributing ideas, respecting diverse musical choices, and collaborating cohesively to create the piece.","Abilikty to articulate learning and personal connections during the reflection and summary discussion."]} {sdgColor} />

</div>
