<script lang="ts">
	import MaterialsList from './components/MaterialsList.svelte';
	import ReflectionQuestions from './components/ReflectionQuestions.svelte';
	import AssessmentCriteria from './components/AssessmentCriteria.svelte';
	import CustomSection from './components/CustomSection.svelte';
	import { getSdgColor } from '$lib/utils/sdg-colors';

	interface Props {
		sdgColor?: string;
	}

	let { sdgColor = getSdgColor(3) }: Props = $props();
</script>

<div class="lesson-content">

	<MaterialsList materials={[{"name":"Paper or notebook","isOptional":false},{"name":"Pens/pencils","isOptional":false},{"name":"Whiteboard or large chart paper","isOptional":false},{"name":"Markers","isOptional":false},{"name":"Small slips of paper for \"Character\" and \"Situation\" draws","isOptional":false}]} {sdgColor} />

	<CustomSection title={"Health Tales: Stories for a Healthy World"} content={"<strong>Introduction</strong><br>Introduce students to Global Goal 3: Good Health and Well-Being.<br><em> This goal aims to make sure everyone, everywhere, has a healthy life and feels good, no matter their age. This means having doctors when you're sick, staying safe, being able to exercise, eating healthy food, and also feeling happy and calm inside your mind.<br></em> It's about caring for our whole selves, our bodies, our minds, our feelings, and even our friendships.<br>Discuss how writers can use their words to paint pictures in people's minds, make them feel emotions, and even inspire them to help make the world a better place.<br>Present that today, the class will be these storytellers, creating Health Tales that show what good health and well-being look like, and how we can help everyone achieve it."} {sdgColor} />

	<CustomSection title={"Health Word Association Chain"} content={"<p>Begin with a word association warm-up to get everyone thinking about health.<br>Explain that the entire class will play this association chain game.<br><em> I'll say a word related to health, and the next person quickly says a new word that comes to their mind when they hear by word. We'll go around the room (or in a circle), building a chain of ideas.<br>Example:<br></em> <em>Teacher:</em> Health<br><em> </em>Student 1:<em> Strong<br></em> <em>Student 2:</em> Muscles<br><em> </em>Student 3:<em> Exercise<br></em> <em>Student 4:</em> Running<br><em> </em>Student 5:<em> Happy<br></em> <em>Student 6:</em> Smile<br><em> </em>Student 7:<em> Friends<br></em> <em>Student 8:</em> Sharing<br><em> </em>Student 9: Kindness<em><br></em> <em>Student 10:</em> Peace<br><em> </em>Student 11:<em> Quiet<br></em> <em>Student 12:</em> Sleeping<br><em> </em>Student 13:<em> Energy<br></em> <em>Student 14:</em> Food<br><em> </em>Student 15:<em> Yummy<br></em> <em>Student 16:</em> Healthy<br><em> </em>Student 17:<em> Doctors<br></em> <em>Student 18:</em> Hospitals<br><em> </em>Student 19:<em> Medicine<br></em> <em>Student 20:</em> Feeling better<br><em> </em>Student 21:<em> Sunshine<br></em> <em>Student 22:</em> Outside<br><em> </em>Student 23:<em> Play<br></em> <em>Student 24:</em> Laughter<br><em> </em>Student 25:<em> Calm<br></em> <em>Student 26:</em> Books<br><em> </em>Student 27:<em> Learning<br></em> <em>Student 28:</em> Brain<br><em> </em>Student 29:<em> Thinking<br></em> <em>Student 30:</em> Mind<br>Encourage quick thinking and don't worry if a word repeats. The goal is to get lots of ideas flowing.</p>"} {sdgColor} />

	<CustomSection title={"Writing Our Health Tales"} content={"<p>Explain that the students will now get some specific ideas for their stories.<br>The class will brainstorm two different categories: \"Health Heroes\" (characters) and \"Health Challenges or Solutions\" (situations). From there each student will choose a pair to be their story's spark.<br>On the whiteboard/paper, create two the two columns: Health Heroes, and Health Challenges/Solutions.<br>Ask:<br><em> Who are some people, real or imaginary, who might be part of a story about health and well-being?<br></em> Have students think about different ages, roles, or even animals.<br>Examples:<br><em> A child who loves to play<br></em> A wise grandparent<br><em> A busy doctor<br></em> A kind nurse<br><em> A super athlete<br></em> A quiet reader<br><em> A friendly neighbor<br></em> A new kid in town<br><em> A shy artist<br></em> A curious scientist<br><em> A little puppy<br></em> A talking tree<br><em> A worried parent<br></em> A funny clown<br><em> A brave explorer<br></em> A speedy runner<br><em> Write these ideas under Health Heroes.<br>Ask: What are some situations related to health? Problems people might face, or amazing ways people get healthy or help others? Think about body health, mind health, feelings health, or friendship health.<br>Examples of Challenges:<br></em> Someone feels lonely<br><em> A friend gets sick<br></em> A character has a bad day and feels sad<br><em> A new food tastes bad<br></em> A character feels worried about something<br><em> Trouble falling asleep<br></em> Feeling left out of a game<br><em> A scraped knee<br></em> A tricky math problem making their brain feel fuzzy<br><em> A loud noise that makes them feel jumpy<br>Examples of Solutions:<br></em> A friend invites someone to play<br><em> Getting a good night's sleep<br></em> Eating a yummy healthy meal<br><em> Someone shares a smile<br></em> A character learns how to calm down<br><em> A doctor helps someone feel better<br></em> Finding a fun way to exercise<br><em> Learning something new that makes their brain happy<br></em> A community builds a safe park<br><em> Helping someone who feels sad<br></em> Sharing a laugh</p>"} {sdgColor} />

	<CustomSection title={"Write Your Health Tale"} content={"<p>Explain that each student will choose one Health Hero and one Challenge AND Solution (three choices total). Ask students to think about how they connect.<br>Have students use their chosen pieces to write their own short story. Ensure the writing shows what happens, what the character sees, thinks, and feels.<br>If helpful, offer these creative writing prompts based on the chosen sparks:<br><em> A Day in the Life of My Health Hero:<br></em> Write a story about your chosen Health Hero and how they experience their challenge and solution situation in one day. What do they see? What do they hear? What do they think in their mind? How do they feel in their body and heart?<br><em> The Journey to Well-being:<br></em> Write a story about your Health Hero's journey through a challenge to find a solution. How do they feel at the beginning? What steps do they take? How do they feel at the end when good health or well-being is found or shared?<br><em> A Health Lesson Shared<br></em> Write a story where your Health Hero helps someone else understand an important lesson about being healthy and well. What is the lesson? How do they share it?<br>Encourage students to use vivid details and strong action words. Remind them to think about how their character experiences the world (what they see, hear, smell, touch, feel inside).<br>Circulate, offering support and guidance as they write. Ask guiding questions like:<br><em> How can you show us that your character is worried without saying \"they were worried\"?<br></em> What sounds would your character hear in that situation?\n<ul>\n<li>What specific colors or shapes come to your mind when you think about their feelings?</li>\n</ul></p>"} {sdgColor} />

	<CustomSection title={"Sharing Our Health Tales"} content={"<p>Organize students into pairs or small groups (3-4 students).<br>Instruct them to take turns reading their writing aloud to their group or partner.<br>As they listen, encourage students to offer kind and helpful comments. Guide them with questions like:<br><em> What did you see or feel when you heard this story?<br></em> What was your favorite part, and why?<br><em> How did this story connect to Global Goal 3?<br></em> What did you learn about your character's feelings or experience?<br>After group sharing, invite a few volunteers to share their writing with the whole class.<br>Facilitate a supportive discussion about the different ideas and feelings expressed in the writing.</p>"} {sdgColor} />

	<CustomSection title={"Gratitude for Wellness Quick List"} content={"<p>Have students think about all the ways they feel healthy and well today, in their bodies, minds, feelings, and friendships.<br>Ask students: What are you thankful for?<br>Have students quickly jot down 1-3 things they are grateful for related to their health and well-being on a piece of paper or their journals. They can be single words or small symbols/drawings.<br>Have students briefly share one idea aloud, or internally reflect on one idea that means the most to them.</p>"} {sdgColor} />

	<ReflectionQuestions questions={["How did writing a stgory or poem about health heroes and challenges/solutions help you understand Global Goal 3: Good Health and Well-being in a new way?","Waht did you learn about the power of using words to show how characters feel, think, and experience health challenges or solutions?","Which stories or ideas from your classmates made you think or feel the most about good health, and why?","What does our Health Tales activity tell us about how we can all work towards Global Goal 3, for ourselves and for everyone?","What's one small thing you can do this week to take care of your own body, mind, or feelings, inspired by the stories we wrote today?"]} {sdgColor} />

	<AssessmentCriteria criteria={["Consistent and enthusiastic involvement in all phases of the lesson, including the warm-up, brainstorm, creative writing, partner/group sharing, and class discussions.","Understanding of the core concept of Global Goal 3 (Good Health and Well-being, covering body, mind, feelings, and social health), as demonstrated through the content and message of the written piece and verbal contributions.","Originality and effort put into the story. Look for evidenced of connection to Global Goal 3 (does the writing clearly relate to aspects of good health and well-being?), use of details (are there attempts to use sensory details and descriptive words from the brainstorm to make the writing vivid?), does it follow a basic story arc?","Ability to respectfully share the writing with peers and offer kind and helpful comments during the sharing sessions.","Ability to articulate learning and personal connections during the reflection and summary discussion."]} {sdgColor} />

</div>
