<script lang="ts">
	import MaterialsList from './components/MaterialsList.svelte';
	import Introduction from './components/Introduction.svelte';
	import ReflectionQuestions from './components/ReflectionQuestions.svelte';
	import AssessmentCriteria from './components/AssessmentCriteria.svelte';
	import CustomSection from './components/CustomSection.svelte';
	import { getSdgColor } from '$lib/utils/sdg-colors';

	interface Props {
		sdgColor?: string;
	}

	let { sdgColor = getSdgColor(1) }: Props = $props();
</script>

<div class="lesson-content">

	<MaterialsList materials={[{"name":"Fabric scraps of various colors, textures, and patterns (pre","description":"cut into small manageable pieces for students, and some larger squares as bases for groups, e.g., 10x10 inches)","isOptional":false},{"name":"Yarn","isOptional":false},{"name":"Fabric glue sticks or liquid fabric glue (e.g., Tacky Glue or school glue that dries clear and holds fabric).","isOptional":false},{"name":"Scissors","isOptional":false},{"name":"Paper","isOptional":false},{"name":"Pencils or markers","isOptional":false},{"name":"Whiteboard or large paper","isOptional":false},{"name":"Markers","isOptional":false},{"name":"Notebooks or Paper","isOptional":false},{"name":"Pens/Pencils","isOptional":false},{"name":"\\[Optional\\] If stitching, blunt tip tapestry needles or plastic yarn needles","isOptional":true}]} {sdgColor} />

	<CustomSection title={"Helping Hands: Our Collaborative Quilt for a World Without Poverty"} content={"<strong>(30-60 MINUTES)</strong>"} {sdgColor} />

	<Introduction content={"<p>Welcome students to an art exploration about an important idea: Global Goal 1: No Poverty.<br><em> Explain that this goal is all about making sure everyone, everywhere, has what they need to live a good life. It means making sure families have enough food, safe homes, and that kids can go to school. This is a huge goal, and it takes everyone working together\\!<br>Introduce the idea of the project today: creating a collaborative quilt.<br></em> This quilt is made of many different pieces of fabric, stitched or glued together, to make one big, warm, and beautiful blanket.<br><em> Emphasize that just like each piece of fabric is important to the quilt, every person and every community has a special part to play in helping others and making the world better.<br></em> Explain that fabric will be used because it reminds us of how different people and communities are connected, like threads woven into strong fabric. When threads come together, they make something strong and beautiful, just like when people work together to help each other overcome challenges.</p>"} />

	<CustomSection title={"Stitching Stories of Support"} content={"<p>Start a gentle discussion about what \"having what you need\" means.<br><em> Ask students: What are some things that </em>everyone<em> needs to live well?<br></em> Guide them towards food, water, a safe place to live, clothes, healthcare, going to school/education, feeling safe.)<br><em> Show a few age-appropriate images that illustrate the diverse daily lives or simple acts of kindness.<br>Examples of images:<br></em> <a href=\"https://convoyofhope.org/wp-content/uploads/2023/09/02-27-24-Sudan-DS-Conflict-6-scaled.jpg\" target=\"_blank\" rel=\"noopener noreferrer\">Convoy of Hope</a><br><em> <a href=\"https://www.unitedwaygw.org/application/files/4715/3421/8498/uwgw_internal_image_template_basic_needs.jpg\" target=\"_blank\" rel=\"noopener noreferrer\">United Way</a><br></em> <a href=\"https://en.operando.org/wp-content/uploads/2020/08/people-helping-people.jpg\" target=\"_blank\" rel=\"noopener noreferrer\">People Helping People</a><br><em> <a href=\"https://s3.amazonaws.com/cms.ipressroom.com/173/files/20233/6441cd252cfac278e888eb2d_Helping+someone+get+up+Annie+Spratt+Unsplash/Helping+someone+get+up+Annie+Spratt+Unsplash_49d20648-4035-49ac-acb7-56f660c19fc8-prv.jpg\" target=\"_blank\" rel=\"noopener noreferrer\">Small Acts of Kindness</a><br></em> Ask guiding questions like:<br><em> What do you notice in these pictures?<br></em> How do you think these people are helping each other?<br><em> What do you think it feels like to help someone else?<br></em> What does it mean for everyone to have a fair chance?<br><em> Introduce the concept that sometimes, people don't have all these basic needs, and that's what \"poverty\" means. Emphasize that it's a big challenge, but people all over the world are working together to fix it.<br></em> Connect this to the fabric: There are different types of fabric, some soft, some bumpy, some colorful.\n<ul>\n<li>Ask how these different fabrics might remind them of different feelings or situations people face, or how we can all come together to help? (e.g., rough fabric for hard times, bright colors for hope and happiness, soft fabric for showing care and comfort.)</li>\n</ul></p>"} {sdgColor} />

	<CustomSection title={"Designing Our Quilt Squares"} content={"<p>Divide students into small groups of 3-4. Give each group a large square of plain fabric (their \"quilt square\") as a base, along with a selection of smaller fabric scraps, yarn, fabric glue, and needles (if applicable).<br>Explain that each group will create a mini-artwork on their fabric square. Their artwork should show ideas about Global Goal 1: No Poverty. They can show:<br><em> What a world without poverty looks like (e.g., people sharing food, kids in school, happy families in safe homes).<br></em> How people help each other to end poverty (e.g., outstretched hands, people working together, symbols of community support).<br><em> Feelings of hope, kindness, fairness, or togetherness.<br>Encourage students to think about the colors and textures of the fabric scraps. Ask questions like:<br></em> How can a bright yellow fabric show hope?<br><em> How can a dark blue make you think of peace or quiet?<br></em> How can something rough and bumpy make you think about challenges we overcome?<br><em> If something is smooth and soft, what does it tell you about feeling safe or calm?<br></em> How can many small pieces glued together show people working as a team?<br><em> How can a strong, durable piece of fabric show the resilience of people working to overcome poverty?<br></em> How can many diverse fabric pieces together represent communities and/or people supporting each other?<br>Before students begin with the fabric, have each group quickly sketch their ideas on paper. Remind them that the goal is the message, not a perfect drawing.<br>Guide students to arrange and layer their fabric scraps onto their quilt square base. They can glue them down, or use simple stitches with yarn and blunt needles to attach pieces (depending on class).<br>Emphasize that it is okay if it's not perfect, the creativity and message are most important.<br>Circulate among groups, offering encouragement and guidance. Ask guiding questions like:<br><em> What part of Global Goal 1 are you showing here?<br></em> How does this color help tell your story?<br><em> If someone looked at your quilt square, what big idea about helping people would you want them to get?<br></em> How does your quilt square show that everyone deserves to have food, or a home, or go to school?\n<ul>\n<li>How does gluing/stitching/layering these pieces together remind you of people helping each other?</li>\n</ul></p>"} {sdgColor} />

	<CustomSection title={"Quilt Square Sharing and Connecting"} content={"<p>Once the groups have finished their quilt squares, have each group briefly present their artwork to the class.<br>Ask guiding questions like:<br><em> What ideas about \"No Poverty\" did your group want to show?<br></em> Why did you choose these colors or shapes?\n<ul>\n<li>How did working together as a team make your quilt square special?</li>\n</ul><br>As each group shares, affirm their creativity and connection to Global Goal 1\\.<br>Collect all the finished quilt squares. Explain that these individual squares will eventually be joined together to create on beautiful \"Helping Hands Quilt\" (or similar title) that symbolizes the class's commitment to Global Goal 1\\. (Note: They can either be physically joined later, or simply displayed together to symbolize the larger quilt.)</p>"} {sdgColor} />

	<ReflectionQuestions questions={["What was one new thing you learned about Global Goal 1: No Poverty today?","How did using fabric and working together help you think about this big goal?","What does our class's quilt show about how people can help each other?","What's one small thing you can do in your own life to show kindness or help someone who might need something?"]} {sdgColor} />

	<AssessmentCriteria criteria={["Consistent and active involvement in all phases of the lesson, including discussions, material exploration, and collaborative art creation.","Ability to grasp the core concept of Global Goal 1 and its connection to basic needs and helping others, as demonsgtrated through the verbal contributions and symbolism in the textile artwork.","Originality and effort put into the group's quilt square, and how effectively fabric was used (through gluing, stitching, or layering) to convey ideas related to ending poverty or showing support.","Ability to work effectively within the small groups, contributing ideas, respecting diverse artistic choices, sharing tasks, and collaborating cohesively to create the shared textile piece.","Ability to articulate the learning and personal connections during the reflection and summary discussion."]} {sdgColor} />

</div>
