<script lang="ts">
	import MaterialsList from './components/MaterialsList.svelte';
	import Introduction from './components/Introduction.svelte';
	import ReflectionQuestions from './components/ReflectionQuestions.svelte';
	import AssessmentCriteria from './components/AssessmentCriteria.svelte';
	import CustomSection from './components/CustomSection.svelte';
	import { getSdgColor } from '$lib/utils/sdg-colors';

	interface Props {
		sdgColor?: string;
	}

	let { sdgColor = getSdgColor(6) }: Props = $props();
</script>

<div class="lesson-content">

	<MaterialsList materials={[{"name":"Whiteboard or large chart paper","isOptional":false},{"name":"Markers","isOptional":false},{"name":"Simple percussion instruments (e.g., hand drums, shakers, tambourines, rhythm sticks, claves. If instruments are limited, encourage students to find improvised instruments safely from the classroom, e.g., clapping hands, stomping feet, tapping on desks, plastic container shakers, snapping fingers, etc.)","isOptional":false},{"name":"Audio","isOptional":false},{"name":"Paper or notebooks","isOptional":false},{"name":"Pens/pencils","isOptional":false}]} {sdgColor} />

	<CustomSection title={"Making Music to Remember Clean Water"} content={"<strong>(30-60 MINUTES)</strong>"} {sdgColor} />

	<Introduction content={"<p>Welcome students to an exciting music class. Explain that they will use the power of rhythm, rhyme, and sound to explore a really important idea: Global Goal 6, Clean Water and Sanitation.<br>Clarify that Global Goal 6 means everyone, everywhere, has access to clean water for drinking, washing, and playing, and safe ways to keep our environments clean (like good restrooms and trash disposal). Emphasize that this means healthy rivers, lakes, and clean hands for all.<br>Explain to students that music and rhythm have a special power: they can help us remember things easily. Ask students to think about how they remember catchy jingles from commercials, or hwo they can sing along to their favorite song without even trying. Explain that today, they will all become memory musicians, creating their own catchy rhymes and rhythms to help remember important ideas about clean water and sanitation.</p>"} />

	<CustomSection title={"Warm Up: Rhythm Patterns and Energy Flow"} content={"<p>Explain that the class will explore how rhythms can transform and flow, just like water. Instruct students to sit or stand comfortably in a circle.<br><em>Foundation Pulse</em>\n<ul>\n<li>Initiate a simple, steady pulse using your feet (e.g., a quiet foot tap or stomp). Instruct students to join in, feeling the steady beat.</li>\n</ul><br><em>Layered Pattern</em>\n<ul>\n<li>Over the foot pulse, add a contrasting body percussion pattern with your hands (e.g., a consistent hand clap, or gentle hand rub). Instruct students to join this second layer, keeping both the feet and hand rhythms going.</li>\n</ul><br><em>Transforming Pattern</em>\n<ul>\n<li>Explain that a short, specific rhythmic pattern will be created (e.g. clap-clap-snap-rest) and perform it for the class. Instruct the student next to you to echo that exact pattern.</li>\n<li>Then, the student next to them will echo the pattern, but change one small part of it (e.g., changing a clap to a stomp, a snap to a vocal sound, or changing the timing slightly). The transformation should make sense but be a clear change.</li>\n<li>Mention to students that if they feel stuck, they can always echo the exact pattern, and then the next student will continue to pick up the change.</li>\n</ul><br>Example Sequence:\n<ul>\n<li><em>Teacher:</em> clap-clap-snap-rest (perform pattern once)</li>\n<li><em>Student 1:</em> clap-clap-snap-rest (echoes the pattern)</li>\n<li><em>Student 2:</em> clap-clap-stomp-rest (echoes, but changes snap to stomp)</li>\n<li><em>Student 3:</em> clap-clap-stomp-tap (echoes, but changes rest to tap)</li>\n<li><em>Student 4:</em> clap-clap-stomp-tap (this student echoes exactly, perhaps wasn't prepared to make a change)</li>\n<li><em>Student 5:</em> clap-clap-vocal-tap (echoes, changes stomp to vocal sound.</li>\n<li>Guide students to keep the transformation going around the circle, one change at a time, for 2-3 rounds.</li>\n</ul><br><em>Energy Flow</em>\n<ul>\n<li>Instruct students to combine any sounds and rhythms they've explored and let their collective rhythm flow, getting louder and more energetic (like a powerful river), then gradually getting softer and calmer (like water settling), until it fades to silence.</li>\n</ul><br>Conclude by affirming their rhythmic creativity and adaptability.</p>"} {sdgColor} />

	<CustomSection title={"Making Music to Remember"} content={"<p>Explain that the class will create a Water Word Web to help brainstorm key ideas about clean water and sanitation.<br>On the board/paper, draw a large central circle and write: \"Clean Water and Sanitation\" inside of the circle.<br>Then, draw several branches coming from the center, each representing a key aspect of Global Goal 6. Explain that these are the main ideas students should remember.\n<ul>\n<li><em>Clean Water for All</em> (Access to safe drinking water)</li>\n<li><em>Wash and Be Healthy</em> (Sanitation and hygiene)</li>\n<li><em>Stop Pollution</em> (Keeping water clean)</li>\n<li><em>Save Water Wisely</em> (Using water efficiently)</li>\n<li><em>Work Together</em> (Community and global cooperation)</li>\n</ul><br>For each brand, ask students to shout out answers to questions about:\n<ul>\n<li><em>Key Words/Phrases:</em> What are the most important words or short phrases for this idea?</li>\n</ul><br>Examples for\n<ul>\n<li><em>Clean Water for All:</em> Drink safe, pure, fresh, tap, everyone, clear, healthy, water well, flowing, clean glass, sip, clean spring.</li>\n<li><em>Wash and Be Healthy:</em> Soap, hands, clean, germs, flush, private, healthy, tidy, scrub, bubbles, sparkling, fresh, feel good.</li>\n<li><em>Stop Pollution:</em> No trash, clean up, recycle, no chemicals, pure, healthy rivers, sparkling lakes, pick up, filters, careful.</li>\n<li><em>Save Water Wisely:</em> Turn off faucet, fix leaks, short showers, reuse, precious drops, no waste, drips, careful, only what we need, conserving, smart use.</li>\n<li><em>Work Together:</em> Team, community, share, help, global, unite, strong, listen, together, cooperation, joining hands, group effort, building.</li>\n<li><em>Matching Sounds/Rhythms:</em> What kind of sound or rhythm would help you remember this idea? What instrument or body percussion would fit?</li>\n</ul><br>Examples for\n<ul>\n<li><em>Clean Water for All:</em> Clear bell sound, steady flowing rhythm, happy hum, gentle splash, soft \"glug-glug\" of drinking water.</li>\n<li><em>Wash and Be Healthy:</em> Rubbing hands sound, quick \"swish swish\" rhythm, cheerful vocals, bubbly sounds.</li>\n<li><em>Stop Pollution:</em> A \"stop\" beat, a NO vocal sound, a strong and determined rhythm.</li>\n<li><em>Save Water Wisely:</em> A quiet and careful rhythm, a shhh sound, a slow and deliberate beat, a tiny drip drip.</li>\n<li><em>Work Together:</em> Many different instruments playing together, a steady marching beat, a we can chant, interlocking claps, a building sound.</li>\n<li>Write these ideas on the branches of the web, connecting words to sounds/rhythms.</li>\n</ul></p>"} {sdgColor} />

	<CustomSection title={"Creating Catchy Anthems"} content={"<p>Divide students into small groups (3-4 students). Provide each group with simple percussion instruments or remind them they can use body percussion/improvised instruments.<br>Explain that each group will choose one of the main ideas from the Water Word Web brainstorm (e.g., Clean Water for All or Stop Pollution). Instruct them to create a super catchy and memorable rhyme or short jingle (about 4-8 lines long) that helps everyone remember that idea.<br>Instruct groups to:\n<ul>\n<li><em>Simplify the idea:</em> Think about how you would explain your chosen idea to a younger student.</li>\n<li><em>Brainstorm rhymes:</em> Find words that rhyme and fit your idea</li>\n<li><em>Add a beat:</em> Create a simple, repetitive rhythm using the instruments or body percussion that makes your rhyme catchy.</li>\n<li><em>Add a simple melody:</em> If comfortable, add a simple and easy to remember tune to your rhyme.</li>\n<li><em>Practice:</em> Make sure everyone in the group knows their part and can perform it clearly.</li>\n</ul><br>Provide examples/prompts for inspiration if needed:\n<ul>\n<li><em>Clean Water for All:</em></li>\n<li>Water clear, water bright / Makes us healthy, day and night / Drink it up, feel so grand / Clean water for every land!</li>\n<li><em>Wash and Be Healthy:</em></li>\n<li>Wash your hands, scrub with soap / Germs away, full of hope / Use the loo, keep it neat / Healthy bodies, happy feet!</li>\n<li><em>Stop Pollution:</em></li>\n<li>No more trash / No more junk / Keep our rivers from a funk / Recycle reuse, play your part / Clean water from the very start!</li>\n<li><em>Save Water Wisely:</em></li>\n<li>Turn off the tap don't let it run / Saving water's lots of fun / Every drop is precious see / For you for me for all to be!</li>\n<li><em>Work Together:</em></li>\n<li>Hand in hand across the land / For clean water take a stand / Work as a team strong and true / Clean water for me and you!</li>\n</ul><br>Circulate among groups, offering guidance and encouraging creativity. Ask guiding questions like:\n<ul>\n<li>How can you make that rhyme even catchier?</li>\n<li>What rhythm makes it easy to remember?</li>\n<li>Does your jingle clearly tell us about your idea?</li>\n</ul></p>"} {sdgColor} />

	<CustomSection title={"Sound Gallery Walk"} content={"<p>Have each group perform their rhyme/jingle for the class.<br>After each performance, ask the audience:\n<ul>\n<li>What was the main idea or message of the jingle? What were they trying to help us remember about clean water and/or sanitation?</li>\n<li>What specific words or rhymes did you hear that helped you remember their message?</li>\n<li>What was catchy about their rhythm or melody? Did it make you want to tap your feet or sing along?</li>\n<li>How did their music help you understand the importance of their idea?</li>\n</ul><br>[Optional] After all groups have performed, challenge the class to remember as many of the different jingles/rhythms as they can, trying to recall the key message for each one.</p>"} {sdgColor} />

	<CustomSection title={"Reflection & Summary"} content={"<p>Have students reflect on their learning experience through discussion or writing.<br>Ask guiding questions like:\n<ul>\n<li>How did creating catchy rhymes and rhythms help you remember the important messages of Global Goal 6: Clean Water and Sanitation?</li>\n<li>What did you learn about the power of music to help us learn and remember big ideas?</li>\n<li>Which jingles or ideas from your classmates made you think or feel the most about clean water and sanitation, and why?</li>\n<li>What does our activity tell us about how we can all work towards Global Goal 6?</li>\n<li>What's one small action you feel inspired to take this week to help keep water clean or save water?</li>\n</ul></p>"} {sdgColor} />

	<CustomSection title={"Assessment"} content={"<ul>\n<li>Consistent and enthusiastic involvement in all phases of the lesson, including the warm up, brainstorm, group music creation, and class discussions.</li>\n<li>Understanding of the core concepts of clean water and sanitation (access, hygiene, pollution prevention, water saving, coopeation), as demonstrated through the accuracy and clarity of the rhymes/jingles and verbal contributions during discussions.</li>\n<li>Originality and effectiveness in crafting catchy rhymes/jingles that accurately reflect the chosen idea from the brainstorming. Look for evidence that rhythm and simple melody were used to enhance memorability.</li>\n<li>Ability to work effectively within the small groups, contributing ideas, respecting diverse musical choices, and collaborating cohesively to create the piece.</li>\n<li>Ability to articulate learning and personal connections during the reflection and summary discussion.</li>\n</ul>"} {sdgColor} />

</div>
