<script lang="ts">
	import Introduction from './components/Introduction.svelte';
	import DiscussionPrompts from './components/DiscussionPrompts.svelte';
	import ReflectionQuestions from './components/ReflectionQuestions.svelte';
	import AssessmentCriteria from './components/AssessmentCriteria.svelte';
	import CustomSection from './components/CustomSection.svelte';
	import { getSdgColor } from '$lib/utils/sdg-colors';

	interface Props {
		sdgColor?: string;
	}

	let { sdgColor = getSdgColor(14) }: Props = $props();
</script>

<div class="lesson-content">

	<CustomSection title={"Mime for Marine Life"} content={"<strong>(30-60 MINUTES)</strong>"} {sdgColor} />

	<CustomSection title={"Materials:"} content={"<p>Audio<br>Open space suitable for movement<br>Whiteboard or large chart paper<br>Markers<br>Paper<br>Pens/pencils<br>A collection of “mime props” (e.g., scarf, small ball, piece of rope, etc.)</p>"} {sdgColor} />

	<Introduction content={"<p>`\t`Begin by introducing the concept of mime. Explain that a mime is an artist who tells a story without any words at all. They use their bodies, gestures, and facial expressions to create an illusion. The goal is to make the audience believe they are seeing an invisible object or feeling a real emotion.<br>`\t`Demonstrate a few simple mime techniques and have students mime along:\n<ul>\n<li><em>Invisible Wall:</em> Pretend to push against an invisible wall. Show the resistance and force in your hands and body.</li>\n<li><a href=\"https://www.youtube.com/watch?v=V4d7RVK2W9U\" target=\"_blank\" rel=\"noopener noreferrer\">How to Mime a Wall</a></li>\n<li><em>Pulling a Rope:</em> Show the weight and tension of pulling on an invisible rope. Let your body lean back to show the effort.</li>\n<li><a href=\"https://www.youtube.com/watch?v=bENQdUcFffE\" target=\"_blank\" rel=\"noopener noreferrer\">Learn the basic mime technique for pulling a mime rope</a></li>\n<li><em>Passing an Object:</em> Show the shape and size of an invisible ball as you pass it to an imaginary friend. Is it a small marble or a heavy bowling ball?</li>\n<li><a href=\"https://www.youtube.com/watch?v=hQZBKF2kqAc\" target=\"_blank\" rel=\"noopener noreferrer\">How to Throw a Ball in Mime</a></li>\n<li><a href=\"https://www.youtube.com/watch?v=5wiCb_h_PLs\" target=\"_blank\" rel=\"noopener noreferrer\">How to Catch a Ball in Mime</a></li>\n<li><em>Facial Expressions:</em> Practice showing emotions with just your face. Show surprise, sadness, happiness, and confusion without making a sound.</li>\n<li><a href=\"https://www.youtube.com/watch?v=hVmqyt60ydk\" target=\"_blank\" rel=\"noopener noreferrer\">Mime Facial Expressions</a></li>\n</ul><br>`\t`These quick demonstrations will help students understand the basic principles of mime.</p>"} />

	<CustomSection title={"The Ocean’s Story in Four Acts"} content={"<p>`\t`Tell the class they will use a collaborative approach to build a physical story about the ocean, where they will physically embody different concepts related to Global Goal 14.<br>`\t`<em>Act 1, The Healthy Ocean</em>\n<ul>\n<li><em>Objective:</em> To embody the beauty and life of a healthy ocean.</li>\n<li><em>Prompt Example:</em> Imagine you are a sea creature swimming in a beautiful, clean ocean. What are you? A tiny, darting fish? A slow, graceful jellyfish? A giant, powerful whale? Use your body to show how you move. What does the water feel like? Is it gentle and flowing, or fast and powerful?</li>\n<li><em>Focus:</em> Encourage students to use smooth, fluid movements. Have some students act as the “water” with flowing arms while others act as “fish” darting through them.</li>\n</ul><br>`\t`<em>Act 2, The Problem</em>\n<ul>\n<li><em>Objective:</em> To physically show the impact of pollution.</li>\n<li><em>Prompt Example:</em> Imagine a piece of pollution enters the water - a plastic bag, a fishing net, etc. How would you, as a sea creature, react? Can you use your body to show that you are stuck or tangled? Show the feeling of struggle, of being unable to move freely. How would the expression on your face communicate this?</li>\n<li><em>Focus:</em> Have students practice showing “resistance” as if they are pushing against a plastic bag or pulling against a rope. This helps students to physically feel the restriction.</li>\n</ul><br>`\t`<em>Act 3, The Rescue</em>\n<ul>\n<li><em>Objective:</em> To show people taking action.</li>\n<li><em>Prompt Example:</em> People on land are starting to notice the problem. Imagine you are a person who wants to help the ocean. How would you show yourself picking up trash on the beach? How would you show yourself recycling a plastic bottle instead of throwing it off of a boat? Show us the feeling of working hard and being determined to make a difference.</li>\n<li><em>Focus:</em> This is where students can practice showing the weight and effort of lifting and moving things. Encourage them to use strong, purposeful movements.</li>\n</ul><br>`\t`<em>Act 4, The Hopeful Future</em>\n<ul>\n<li><em>Objective:</em> To show the result on our actions.</li>\n<li><em>Example Prompt:</em> Because of our hard work, the ocean is getting healthier. How would a sea creature move now? How would you, as the water, move to show that you are clean and healthy again? What would the expression on your face be when you see a clean ocean? Show the feeling of hope and of a brighter future.</li>\n<li><em>Focus:</em> Bring back the flowing, happy movements from Act 1, but this time with a sense of triumph and purpose.</li>\n</ul><br>`\t`This activity breaks down a complex issue into understandable, physical parts. By embodying both the problem and solution in a dramatic way, students will gain a deeper understanding of the entire story.</p>"} {sdgColor} />

	<CustomSection title={"Creative Mime Scenes"} content={"<p>`\t`Break the class up into small groups (3-4 students) to create their own short mime scenes (1-2 minutes).\n<ul>\n<li>Each group will choose one of the “Acts” just explored in the brainstorming activity.</li>\n<li>Task the groups with creating a short, silent story that clearly communicates their chosen theme.</li>\n<li>Encourage students to use the mime techniques practiced: resistance, weight, clear gestures, and facial expressions.</li>\n</ul><br>`\t`Give groups time to plan their scenes and rehearse. Remind them that a good mime scene tells a story without any words, so they should focus on making their actions very clear.<br>`\t`If desired, play ambient ocean sounds in the background to set the mood and help with focus.<br>`\t`Examples:\n<ul>\n<li><a href=\"https://www.youtube.com/watch?v=P_SeZhpqbvE\" target=\"_blank\" rel=\"noopener noreferrer\">Ocean Sounds for Sleep</a></li>\n<li><a href=\"http://f2amecp9kg0\" target=\"_blank\" rel=\"noopener noreferrer\">Healing Songs of Whales and Dolphins</a></li>\n<li><a href=\"https://www.youtube.com/watch?v=KLPApSRku8Y\" target=\"_blank\" rel=\"noopener noreferrer\">Ocean Aquarium</a></li>\n</ul></p>"} {sdgColor} />

	<CustomSection title={"Performance and Discussion"} content={"<p>`\t`Once the groups have rehearsed, have them perform their short mime scenes for the class. As each group performs, ask the rest of the class to watch carefully and try to understand the story they are telling.<br>`\t`After all groups have performed, ask the class to share what they saw and felt, with guiding questions like:\n<ul>\n<li>What are some of the stories you saw being told?</li>\n<li>How did your classmates use their faces or bodies to show a feeling?</li>\n<li>What did you learn about Global Goal 14 from watching these mimes?</li>\n</ul></p>"} {sdgColor} />

	<CustomSection title={"Reflection & Summary"} content={"<p>Have students reflect on their learning experience through discussion or writing.<br>Ask guiding questions like:\n<ul>\n<li>How did the absence of words affect your understanding of the ocean’s story? Did it make the problems or the solutions feel more real?</li>\n<li>The scenes created showed problems and solutions. What is one thing you can do to help protect the ocean?</li>\n<li>How did working together as a group to create a mime scene feel lik working together to solve a big problem in the real world?</li>\n<li>What did you learn about the power of your body, dramatics, and imagination to tell a story?</li>\n<li>How can dramatic art forms like mime be tools for sharing important messages with the world?</li>\n</ul></p>"} {sdgColor} />

	<CustomSection title={"Assessment"} content={"<ul>\n<li>Consistent and enthusiastic involvement in all phases of the lesson, including the mime exercises, the group scene creation, and the class discussion.</li>\n<li>Comprehension of Global Goal 14 themes as demonstrated through the interpretations conveyed in movement and gesture and the verbal explanations during discussion.</li>\n<li>Originality and expressiveness in translating abstract concepts related to ocean health into dramatic movement. This can be seen in the unique ways bodies and faces are used to show an emotion or problem.</li>\n<li>How clearly and powerfully the mime scenes communicated understanding of Global Goal 14. Did the physical expression successfully evoke thought or emotion in the audience?</li>\n<li>Ability to work together as a group, listening to each other’s ideas, collaborating on the scenes, and performing respectfully for classmates.</li>\n<li>Nuance and depth of understanding demonstrated in reflections, particularly concerning the role of art in social change and the complexities of life below water.</li>\n</ul>"} {sdgColor} />

</div>
