<script lang="ts">
	import MaterialsList from './components/MaterialsList.svelte';
	import Introduction from './components/Introduction.svelte';
	import ReflectionQuestions from './components/ReflectionQuestions.svelte';
	import AssessmentCriteria from './components/AssessmentCriteria.svelte';
	import CustomSection from './components/CustomSection.svelte';
	import { getSdgColor } from '$lib/utils/sdg-colors';

	interface Props {
		sdgColor?: string;
	}

	let { sdgColor = getSdgColor(8) }: Props = $props();
</script>

<div class="lesson-content">

	<MaterialsList materials={[{"name":"Spacious and safe dance studio or open classroom","isOptional":false},{"name":"Music player with a selection of instrumental music (varied tempos and moods)","isOptional":false},{"name":"Whiteboard or projector","isOptional":false},{"name":"Markers or pens","isOptional":false},{"name":"Notebooks or paper","isOptional":false},{"name":"Pens/Pencils","isOptional":false}]} {sdgColor} />

	<CustomSection title={"Moving Towards Justice: Exploring Decent Work & Economic Growth Through Authentic Movement"} content={"<strong>(30-60 MINUTES)</strong>"} {sdgColor} />

	<Introduction content={"<p>Begin with a simple warm-up to get students moving and comfortable in the space. Play an upbeat song that will get students excited to participate. Then, have students walk around the room and greet each other with a movement or gesture that represents their current mood or feeling about the concept of \"work.\"<br>Example songs:<br><em> <a href=\"https://www.youtube.com/watch?v=hT_nvWreIhg\" target=\"_blank\" rel=\"noopener noreferrer\"></em>Counting Stars<em></a> by One Republic<br></em> <a href=\"https://www.youtube.com/watch?v=5y_KJAg8bHI\" target=\"_blank\" rel=\"noopener noreferrer\"><em>Wake Me Up</em></a> by Avicii<br><em> <a href=\"https://www.youtube.com/watch?v=_ovdm2yX4MA\" target=\"_blank\" rel=\"noopener noreferrer\"></em>Levels<em></a> by Avicii<br></em> <a href=\"https://www.youtube.com/watch?v=QtxeJ703w18\" target=\"_blank\" rel=\"noopener noreferrer\"><em>The Avengers Theme</em></a> by Alan Silvestri<br><em> <a href=\"https://www.youtube.com/watch?v=zvCBSSwgtg4\" target=\"_blank\" rel=\"noopener noreferrer\"></em>Ho Hey<em></a> by The Lumineers<br></em> <a href=\"https://www.youtube.com/watch?v=YkLBSLxo5LE\" target=\"_blank\" rel=\"noopener noreferrer\"><em>Caravan</em></a> by Duke Ellington<br><em> <a href=\"https://www.youtube.com/watch?v=mytLRy32Viw\" target=\"_blank\" rel=\"noopener noreferrer\"></em>Something Big<em></a> by Shawn Mendes<br></em> <a href=\"https://www.youtube.com/watch?v=K1b8AhIsSYQ\" target=\"_blank\" rel=\"noopener noreferrer\"><em>We Built This City</em></a> by Starship<br><em> <a href=\"https://www.youtube.com/watch?v=2zNSgSzhBfM\" target=\"_blank\" rel=\"noopener noreferrer\"></em>Can't Hold Us*</a> by Macklemore &amp; Ryan Lewis ft. Ray Dalton<br>Briefly introduce the UN Sustainable Development Goals and focus on Goal 8: Decent Work and Economic Growth. Highlight the importance of fair wages, safe working conditions, ending child labor, and creating opportunities for everyone to have meaningful work.</p>"} />

	<CustomSection title={"Exploring Authentic Movement (10 minutes):"} content={"<strong>Explain the Form:</strong> Define authentic movement as a form of dance improvisation that encourages deep listening to inner impulses and expressing them through movement. Emphasize that there is no \"right\" or \"wrong\" way to move, and that the focus is on honest and spontaneous expression."} {sdgColor} />

	<CustomSection title={"Connecting Movement to SDG 8"} content={"<strong>Target Focus:</strong> Divide students into smaller groups. Assign each group a specific target from SDG 8 (or allow them to choose one that resonates with them). Provide each group with the SDG 8 handout."} {sdgColor} />

	<CustomSection title={"Witnessing and Sharing (10 minutes):"} content={"<p>Witnessing: Have each group share their movement piece while the other groups act as witnesses. Explain that witnessing involves observing with focused attention and without judgment.<br>Sharing and Reflection: After each group shares, facilitate a brief discussion where students can share their experiences of both moving and witnessing. Ask questions like:<br>What did you notice in your own body as you moved?<br><em> What did you observe in the other groups' movements?<br></em> How did the movement help you connect with the SDG 8 target?</p>"} {sdgColor} />

	<ReflectionQuestions questions={["How did the experience of \"authentic movement\" \\- allowing your inner impulses to guide your body \\- connect you to the abstract concepts of decent work and economic growth?","Did moving in a spontaneous, unscripted way help you understand the challenges or hopes associated with decent work and economic growth on a deeper level?","How did witnessing other groups' movement pieces impact your understanding of Global Goal 8?","What did you learn about the unspoken struggles or triumphs related to work that can be expressed through movement?","How did exploring Global Goal 8 through movement illuminate its meaning or implications in a way that simply reading about it might not have?","What common themes or contrasting experiences related to decent work and economic growth emerged across the different movement pieces presented by the class?","Did any particular movement sequence from another group spark a new insight or question for you about Global Goal 8?","How did the focus on \"honest and spontaneous expression\" in authentic movement relate to the idea of fair and equitable conditions in the workplace?","Did this authentic movement activity connect with any of yoru own experiences or observations about work, fairness, or economic opportunity?","What role do you think non-verbal expression and movement can play in advocating for decent work and economic growth?","What role can you play in promoting decent work and economic growth in your community?"]} {sdgColor} />

	<AssessmentCriteria criteria={["Consistent and enthusiastic involvement in all phases of the lesson, including the warm-up, authentic movement exploration, witnessing, and group discussions.","Comprehension of Global Goal 8 and its targets and core concepts (e.g., fair wages, safe conditions, youth employment, sustainable growth). This will be evidenced through the symbolism and intention within the movement pieces and verbal explanations.","Originality and effectiveness in translating abstract concepts related to decent work and economic growth into meaningful and expressive movement. Look for evidence of honest and spontaneous physical responses to prompts.","How clearly and powerfully the movement pieces communicated the intended message about decent work and economic growth. Did the dance successfully evoke thought or emotion in the audience/witnessnes?","Ability to observe other groups' movement pieces with focused attention and respect, and to offer thoughtful reflections on what was noticed and hwo the movements connected to Global Goal 8 themes.","Ability to work effectively and respectfully within the groups, contributing to discussions and supporting each other during the movement explorations.","Nuance and depth of understanding demonstrated in reflections, particularly concerning the role of embodied learning in understanding the human experience of work and economic justice."]} {sdgColor} />

</div>
