<script lang="ts">
	import MaterialsList from './components/MaterialsList.svelte';
	import Introduction from './components/Introduction.svelte';
	import ReflectionQuestions from './components/ReflectionQuestions.svelte';
	import AssessmentCriteria from './components/AssessmentCriteria.svelte';
	import CustomSection from './components/CustomSection.svelte';
	import { getSdgColor } from '$lib/utils/sdg-colors';

	interface Props {
		sdgColor?: string;
	}

	let { sdgColor = getSdgColor(14) }: Props = $props();
</script>

<div class="lesson-content">

	<MaterialsList materials={[{"name":"Watercolor paper (one sheet per student)","isOptional":false},{"name":"Watercolor paints","isOptional":false},{"name":"Watercolor brushes","isOptional":false},{"name":"Containers for water","isOptional":false},{"name":"Paper towels or sponges","isOptional":false},{"name":"Palette or mixing surface (can be as simple as plastic plates or lids)","isOptional":false},{"name":"Whiteboard or large chart paper","isOptional":false},{"name":"Markers","isOptional":false},{"name":"Paper","isOptional":false},{"name":"Pens/Pencils","isOptional":false}]} {sdgColor} />

	<CustomSection title={"Ocean Story: A Watercolor Adventure"} content={"<strong>(30-60 MINUTES)</strong>"} {sdgColor} />

	<Introduction content={"<p>`\t`Begin with an engaging introduction to Global Goal 14. Explain to students that our planet is mostly covered by water, and the ocean is a home to countless amazing creatures, from tiny plankton to giant whales. However, the oceans are facing big problems, and it’s up to us to help protect them.<br>`\t`Facilitate a short discussion, asking guiding questions like:\n<ul>\n<li>What are some things you love about the ocean? Have you ever seen a sea turtle or a cool looking fish or other sea creature?</li>\n<li>How do you think our actions on land might affect the ocean?</li>\n</ul><br>`\t`Lead a guided imagery exercise to help students connect with the topic on a personal level. Ask them to close their eyes or simply soften their gaze while you guide them through a visualization.<br>`\t`Guide students through visualizations:\n<ul>\n<li>Imagine you are an observer in the ocean. The sun in shining, and you’re surrounded by the gentle movement of the waves. You see a vibrant coral reef, bustling with fish of every shape and color. A sea turtle glides by slowly, peaceful, and free.</li>\n<li>Now, as you swim deeper, you notice something that doesn’t belong. A piece of plastic is floating in the water. Maybe it’s a bottle or a bag. How does it make you feel to see trash in this beautiful place? You see a fish swimming near a discarded soda can. What emotions arise?</li>\n<li>Finally, imagine you swim toward the shore. You see people on the beach, but instead of just relaxing, they’re working together. They’re picking up trash, filling bags, and making the beach clean. What does this sight spark inside of you? What feeling do you have for these people?</li>\n</ul><br>`\t`After the guided imagery, give students a moment to joy down or reflect on the emotions and images that came to mind. This helps them connect their personal feelings to the objective of the lesson.</p>"} />

	<CustomSection title={"The Art of Watercolor"} content={"<p>`\t`Introduce students to watercolor painting. It’s important to frame this part of the lesson as an opportunity to experiment and have fun. Emphasize that watercolor is a forgiving medium that encourages spontaneity. Distribute paper for practice and introduce watercolor techniques.\n<ul>\n<li><em>Wet-on-Wet:</em> Demonstrate applying a wash of clean water to the paper and then dropping a bead of paint into the wet area. Explain how the colors bleed and blend to create soft, ethereal effects, perfect for representing water, currents, or the feeling of being underwater.</li>\n<li><em>Wet-on-Dry:</em> Show students how to paint on dry paper for sharp lines and defined shapes. Explain that this technique is ideal for details that need to stand out, like a specific fish or other animal/creature, or, perhaps, a piece of pollution or trash.</li>\n<li><em>Lifting:</em> Show students how to remove paint. While a paint wash is still wet, they can use a clean, damp brush or a paper towel to gently blot or lift paint away. This creates highlights and adds a sense of light and dimension.</li>\n<li><em>Layering:</em> Explain that colors can be built up in layers. A light color can be painted, left to dry completely, and then a darker color can be painted on top to create shadows and depth, just like in a real ocean.</li>\n</ul><br>`\t`Encourage students to play with these techniques on their paper before they begin the final artwork.</p>"} {sdgColor} />

	<CustomSection title={"Brainstorming Our Story"} content={"<p>`\t`Create a large starter mural on the whiteboard or large paper with a clear dividing line down the middle. Label one side “The Problem” and the other “The Solution.”\n<ul>\n<li><em>The Problem:</em> Ask students to share ideas about marine pollution. Instead of just saying words like “trash,” encourage them to think about specific examples/images. Ask them to come up to the board/paper and either draw or write their ideas on the Problem side.</li>\n</ul><br>Use prompts like:\n<ul>\n<li>What kinds of things pollute our oceans?</li>\n<li>What does this pollution do to marine animals and their homes?</li>\n</ul><br>Examples to encourage:\n<ul>\n<li>Plastic bags floating like jellyfish.</li>\n<li>Tangled fishing nets.</li>\n<li>A sea turtle with a straw in its nose.</li>\n<li>A bottle floating in the waves.</li>\n<li>A dark oil slick.</li>\n<li><em>The Solution:</em> Transition the conversation to a hopeful, action-oriented space. Ask students to think about what a healthy ocean looks like and what actions can get us there. Ask them to think about specific examples/images. Have them come up and draw or write their ideas on the Solution side.</li>\n</ul><br>Use prompts like:\n<ul>\n<li>What does a healthy ocean look like?</li>\n<li>What can people do to help?</li>\n</ul><br>Examples to encourage:\n<ul>\n<li>A vibrant, clean beach.</li>\n<li>People picking up trash.</li>\n<li>A scientist studying a healthy reef.</li>\n<li>A school of fish swimming freely.</li>\n<li>A sign on the beach that says “Recycle!”</li>\n</ul><br>`\t`This collaborative brainstorming mural will serve as a visual reference for students as they work on their individual paintings. It shows the cause and effect of actions and provides a clear narrative to draw from.</p>"} {sdgColor} />

	<CustomSection title={"Creating Our Watercolor Masterpieces"} content={"<p>`\t`Now, students will create their own individual watercolor paintings. Remind them to choose one powerful idea from the brainstorming mural. The goal is to use their art to tell a clear story.\n<ul>\n<li><em>Guidance:</em> Walk around the room and offer guidance. Help students with composition, color choices, and technique. Remind them that the goal is not to achieve perfect realism but to express an idea and evoke emotion.</li>\n<li><em>Encourage Emotion:</em> The most effective paintings are those that have a clear message. Encourage students to think about the emotions they want to convey. If they are painting a sad scene, suggest using darker, more muted colors. If they are painting a hopeful scene, suggest using bright, vibrant colors.</li>\n</ul></p>"} {sdgColor} />

	<CustomSection title={"Gallery Walk and Storytelling"} content={"<p>`\t`When the paintings are dry, arrange a gallery walk. Have students place their artwork on their desks or a shared table. The class will walk around, viewing each piece like they’re in a museum.<br>Then, each student will take a turn standing next to their painting and sharing its story. Ask guiding questions like:\n<ul>\n<li>What is the main message of your painting?</li>\n<li>What watercolor techniques did you use to tell your story?</li>\n<li>What emotions do you hope your art inspires in others?</li>\n<li>How does your painting connect to Global Goal 14?</li>\n</ul><br>`\t`This allows students to practice communicating their ideas and to see all the different ways the same or a similar message can be expressed through art.</p>"} {sdgColor} />

	<CustomSection title={"Reflection & Summary"} content={"<p>Have students reflect on their learning experience through discussion or writing.<br>Ask guiding questions like:\n<ul>\n<li>How did using watercolors help you understand the problem of marine pollution on a deeper level?</li>\n<li>What did you discover about your own ability to use art to make a big, complex idea feel more real?</li>\n<li>After creating your art and seeing the work of your classmates, what is one small thing you can do to help protect the ocean?</li>\n<li>How does our collective artwork show us that we can all make a difference?</li>\n<li>The art we created today is a story; how does art help us share important messages with people without using words?</li>\n<li>What did you learn about the ocean’s story through this activity?</li>\n</ul></p>"} {sdgColor} />

	<CustomSection title={"Assessment"} content={"<ul>\n<li>Consistent and enthusiastic involvement in all phases of the lesson, including the guided imagery, introduction to watercolor, brainstorming mural, individual painting, gallery walk, and class discussions.</li>\n<li>Understanding of Global Goal 14 and the concept of marine pollution. This will be shown through the symbolism in the watercolor paintings and verbal explanations during the gallery walk and class discussion.</li>\n<li>Originality and effectiveness in applying watercolor techniques to convey the message. Was there experimentation with different techniques (wet-on-wet, lifting, layering, etc.) to tell the story?</li>\n<li>How clearly and powerfully the finished artwork communicates its intended message. Did the paintings successfully convey evoke thought or emotion related to the ocean’s beauty, its challenges, or the power of taking action?</li>\n<li>Ability to articulate artistic choices and provide thoughtful feedback on classmates’ artwork, connecting it to Global Goal 14.</li>\n<li>Nuance and depth of understanding demonstrated in reflections, particularly concerning the role of art in social change and the complexities of life below water.</li>\n</ul>"} {sdgColor} />

</div>
