<script lang="ts">
	import Introduction from './components/Introduction.svelte';
	import ReflectionQuestions from './components/ReflectionQuestions.svelte';
	import AssessmentCriteria from './components/AssessmentCriteria.svelte';
	import CustomSection from './components/CustomSection.svelte';
	import { getSdgColor } from '$lib/utils/sdg-colors';

	interface Props {
		sdgColor?: string;
	}

	let { sdgColor = getSdgColor(14) }: Props = $props();
</script>

<div class="lesson-content">

	<CustomSection title={"Ocean Anthem: Life Below Water Jingles"} content={"<strong>(30-60 MINUTES)</strong>"} {sdgColor} />

	<CustomSection title={"Materials:"} content={"<p>Audio<br>Whiteboard or large chart paper<br>Markers<br>Notebooks or paper<br>Pens/Pencils<br>Body percussion (clapping, snapping, stomping, etc.)</p>"} {sdgColor} />

	<Introduction content={"<p>Begin with an engaging introduction to jingles.<br>Explain that jingles are short, catchy songs used in advertising to promote products or services.<br>Highlight key characteristics:\n<ul>\n<li>Simple melodies</li>\n<li>Repetitive lyrics</li>\n<li>Catchy hooks (the part that sticks in your head)</li>\n<li>Memorable and easy to sing</li>\n</ul><br>Play examples of well-known jingles (of different lengths):\n<ul>\n<li><em>Nationwide Insurance</em> “Nationwide is on your side”</li>\n<li><em>McDonald’s</em> “Ba da ba ba ba…I’m lovin’ it”</li>\n<li><em>State Farm Insurance</em> “Like a good neighbor, State Farm is there”</li>\n<li><em>Burger King</em> “Have it your way”</li>\n<li><em>Folgers Coffee</em> “The Best Part of Wakin’ Up Is Folgers In Your Cup”</li>\n<li><em>Kit Kat</em> “Gimme a Break”</li>\n<li><em>Doublemint Gum</em> “Double Your Pleasure”</li>\n<li><em>O’Reilly Auto Parts</em> “O-O-O-O’Reilly…”</li>\n<li><em>Chili’s</em> “Baby Back Ribs”</li>\n</ul><br>Facilitate a brief discussion:\n<ul>\n<li>What are some jingles you can remember?</li>\n<li>What makes a jingle effective?</li>\n<li>How can we use the power of jingles to promote a message?</li>\n</ul><br>Introduce or reintroduce Global Goal 14: Conserve and sustainably use the oceans, seas and marine resources for sustainable development. Emphasize the importance of the oceans for life on Earth and the urgency of protecting them. If wanted, briefly review the key targets and indicators.<br>Connect jingles and Global Goal 14 by engaging students in a thought-provoking discussion about how jingles can be used to promote ocean conservation.<br>Ask guiding questions like:\n<ul>\n<li>How can we use the catchy nature of jingles to raise awareness about ocean issues?</li>\n<li>Can we create jingles that inspire people to take action?</li>\n<li>How can we use simple melodies and lyrics to communicate complex ideas?</li>\n</ul></p>"} />

	<CustomSection title={"Jingle Structure and Brainstorming"} content={"<p>Explain the basic structure of a jingle:\n<ul>\n<li><em>Hook:</em> The main, most memorable part (often the chorus).</li>\n<li><em>Verse(s):</em> Short sections that provide information or tell a story.</li>\n<li><em>Tagline:</em> A short, memorable phrase that summarizes the message.</li>\n</ul><br>As a class, brainstorm key messages and concepts related to Global Goal 14.<br>Examples:\n<ul>\n<li>“Protect marine life”</li>\n<li>“Reduce plastic pollution”</li>\n<li>“Stop overfishing”</li>\n<li>“Keep our oceans clean”</li>\n<li>“The ocean is our future”</li>\n</ul><br>Divide students into small groups (3-4 students)<br>Assign each group a specific aspect of Global Goal 14 (e.g., pollution, overfishing, etc.) to focus on OR have groups create a jingle about Global Goal 14 as a whole, allowing for more creative freedom.<br>Have each group brainstorm ideas for their jingle, focusing on:\n<ul>\n<li>A catchy hook.</li>\n<li>Simple and informative lyrics.</li>\n<li>A memorable melody.</li>\n<li>Rhythms and sounds they can create with their bodies or simple instruments available in the classroom.</li>\n<li>A tagline that summarizes their message.</li>\n</ul></p>"} {sdgColor} />

	<CustomSection title={"Jingle Creation and Rehearsal"} content={"<p>Lyric Writing\n<ul>\n<li>Groups write the lyrics for their jingles, keeping them concise and easy to understand.</li>\n<li>Encourage the use of:</li>\n<li>Repetition</li>\n<li>Rhyme (optional, but can make it catchier).</li>\n<li>Strong verbs and imagery.</li>\n</ul><br>Melody development\n<ul>\n<li>Groups create a simple melody for their lyrics. Emphasize:</li>\n<li>A limited range of notes.</li>\n<li>A clear and memorable rhythm.</li>\n<li>A melody that fits the tone and message of the lyrics.</li>\n<li>Melodies that can be sung without instruments or with the limited instruments available in the classroom.</li>\n</ul><br>Rhythmic Accompaniment\n<ul>\n<li>Groups develop a rhythmic accompaniment using body percussion or simple percussion available in the classroom. Encourage:</li>\n<li>Simple and repetitive patterns.</li>\n<li>Variety in sounds (claps, snaps, stomps, etc.)</li>\n<li>Coordination between the vocal melody and the rhythm.</li>\n</ul><br>Rehearsal\n<ul>\n<li>Groups rehearse their jingles, focusing on:</li>\n<li>Clear pronunciation and articulation.</li>\n<li>Rhythm and timing.</li>\n<li>Energy and enthusiasm.</li>\n<li>Coordination between singers and body percussion.</li>\n</ul></p>"} {sdgColor} />

	<CustomSection title={"Jingle Performances"} content={"<p>Each group performs their jingle for the class. Encourage:\n<ul>\n<li>Clear and confident delivery.</li>\n<li>Enthusiasm and energy.</li>\n<li>Clear communication of the message.</li>\n</ul><br>Provide positive feedback and encouragement after each performance.</p>"} {sdgColor} />

	<CustomSection title={"Reflection and Summary"} content={"<p>Have students reflect on their learning experience through discussion or writing.<br>Ask guiding questions like:\n<ul>\n<li>How did using the jingle format - its catchiness, simplicity, and repetition - help you to create a memorable message about ocean conservation?</li>\n<li>What did you learn about the power of short, impactful phrases and simple melodies to communicate complex issues like marine pollution or overfishing?</li>\n<li>Did creating a jingle make you think differently about how advertising influences behavior, and how taht power could be redirected for positive change?</li>\n<li>What did you discover about the effectiveness of body percussion or simple sounds in supporting a vocal message about Global Goal 14?</li>\n<li>How can a memorable jingle cut through noise and capture public attention for an important environmental cause?</li>\n<li>What new insights did you gain about Global Goal 14 and the challenges facing the oceans through this jingle-writing activity?</li>\n<li>Did the activity make you think differently about your own impact on the ocean, or the collective human impact?</li>\n<li>What common themes or calls to action for ocean health emerged across the different jingles created by the groups?</li>\n<li>How does a direct and accessible form of music like a jingle help to spread awareness about global issues like ocean conservation?</li>\n<li>Did creating your jingle spark any personal connections or reflections on your own relationship with the ocean or its wellbeing?</li>\n<li>What emotions did you connect with during this musical activity, and how might those emotions motivate you to take action related to Global Goal 14?</li>\n<li>How has this lesson influenced your thinking about your own role in protecting life below water in your daily life or community?</li>\n</ul></p>"} {sdgColor} />

	<CustomSection title={"Assessment"} content={"<ul>\n<li>Consistent and enthusiastic involvement in all phases of the lesson, including the introduction to jingles, brainstorming, collaborative jingle creation, rehearsal, and class discussions.</li>\n<li>Comprehension of Global Goal 14, targets and core concepts. This will be evidenced through the thematic content and symbolism within the jingle lyrics and melody, and verbal explanations.</li>\n<li>Originality and effectiveness in crafting catchy and memorable jingles that adhere to the basic jingle structure (hook, verse, tagline) and rhythmic characteristics.</li>\n<li>How clearly and powerfully the finished jingle communicates its intended message about Global Goal 14. Did the jingle successfully evoke thought or emotion, or effectively encourage action related to ocean conservation?</li>\n<li>Willingness to project voices, maintain rhythm, and deliver the jingle with enthusiasm during the group performances, enhancing its communicative impact.</li>\n<li>Ability to work effectively within the groups, contributing ideas, respecting diverse interpretations, and collaborating cohesively during the songwriting and rehearsal process.</li>\n<li>Nuance and depth of understanding demonstrated in reflections, particularly concerning the role of music in advocating for environmental change and the complexities of ocean conservation.</li>\n</ul>"} {sdgColor} />

</div>
