<script lang="ts">
	import MaterialsList from './components/MaterialsList.svelte';
	import DiscussionPrompts from './components/DiscussionPrompts.svelte';
	import ReflectionQuestions from './components/ReflectionQuestions.svelte';
	import AssessmentCriteria from './components/AssessmentCriteria.svelte';
	import CustomSection from './components/CustomSection.svelte';
	import { getSdgColor } from '$lib/utils/sdg-colors';

	interface Props {
		sdgColor?: string;
	}

	let { sdgColor = getSdgColor(13) }: Props = $props();
</script>

<div class="lesson-content">

	<MaterialsList materials={[{"name":"Drawing paper or sturdy cardstock","isOptional":false},{"name":"Pencils, pens","isOptional":false},{"name":"Bold and vibrant art supplies","description":"Markers, colored pencils, crayons, paints, etc.","isOptional":false},{"name":"Collage materials","description":"old magazines, newspapers, colored paper scraps, stickers, etc.","isOptional":false},{"name":"Scissors and glue","isOptional":false},{"name":"Whiteboard or large chart paper","isOptional":false},{"name":"Markers","isOptional":false},{"name":"Notebooks or paper","isOptional":false},{"name":"Pens/Pencils","isOptional":false},{"name":"Climate Action Grid [EXAMPLE](https","description":"//drive.google.com/file/d/1_wnkPSnnXooclGWxeS5XeS6DZ5fRA_QM/view?usp=drive_link) (formatted for 17”x11”)","isOptional":false}]} {sdgColor} />

	<CustomSection title={"ART"} content={"<strong>Pop The Planet: Climate Action &amp; Pop Art</strong>"} {sdgColor} />

	<CustomSection title={"(30-60 MINUTES)"} content={"<strong>Introduction</strong><br>`\t`Welcome students to an exciting art class. Explain that they will use their imaginations and creativity to explore a really important idea: Global Goal 13, Take urgent action to combat climate change and its impacts.<br>`\t`Clarify that Global Goal 13 is like a huge promise the world has made; a promise to work together to protect our planet. Emphasize that this means:\n<ul>\n<li><em>Fighting climate change:</em> Working to keep the Earth healthy and safe.</li>\n<li><em>Finding solutions:</em> Creating new and smart ways to power our world and live our lives.</li>\n<li><em>Protecting our communities:</em> Making sure our towns and cities are strong enough to handle big storms and other weather challenges.</li>\n</ul><br>`\t`Show a diverse range of images and videos related to climate change.<br>`\t`Examples:\n<ul>\n<li><a href=\"https://c.files.bbci.co.uk/12DF7/production/_113530377_bears_kt-miller.jpg\" target=\"_blank\" rel=\"noopener noreferrer\">Polar Bear on Melting Ice</a>, BBC</li>\n<li><a href=\"https://www.ucs.org/sites/default/files/styles/large/public/images/1200-corndrought.jpg?itok=q-CCHUPS\" target=\"_blank\" rel=\"noopener noreferrer\">Drought and Climate Change</a>, Union of Concerned Scientists</li>\n<li><a href=\"https://cdn.mos.cms.futurecdn.net/Gn8CNWxEJbVvB9owEzxQPE.jpg\" target=\"_blank\" rel=\"noopener noreferrer\">Sinking US Cities</a>, Live Science</li>\n<li><a href=\"https://platform.vox.com/wp-content/uploads/sites/2/chorus/uploads/chorus_asset/file/24090029/GettyImages_1243654244.jpeg?quality=90&amp;strip=all&amp;crop=0%2C0%2C100%2C100&amp;w=1440\" target=\"_blank\" rel=\"noopener noreferrer\">Hurricane Ian</a>, Vox</li>\n<li><a href=\"https://images.newscientist.com/wp-content/uploads/2017/05/02163148/p8713477-2.jpg?width=1900\" target=\"_blank\" rel=\"noopener noreferrer\">Air Pollution</a>, New Scientist</li>\n</ul>"} {sdgColor} />

	<CustomSection title={"Warm Up: Emoji Climate Story"} content={"<strong>NOTE:</strong> If students are not familiar with emojis, just substitute with symbols!<br>`\t`Explain that the class will practice telling a story with just pictures, which is a great skill to have when creating Pop Art. Instruct all students to take a pice of paper and a pencil/pen.<br>`\t`<em>Problem Emoji</em>\n<ul>\n<li>Have students imagine a problem related to climate change (e.g. a smoky car, a hot day, a sad polar bear). What emoji can they think of to show that problem? (e.g., 😞, 🔥, 💨, ❄️). Have students quickly sketch that emoji or symbol on their paper.</li>\n</ul><br>`\t`<em>Solution Emoji</em>\n<ul>\n<li>Next, have students imagine a solution to that problem (e.g., riding a bike, planting a tree, using a bus). What emoji can they think of to show that solution? (e.g., 🚲, 🌳, ♻️, 💡, 😀). Have students quickly sketch that emoji or symbol on their paper.</li>\n</ul><br>`\t`<em>The Story</em>\n<ul>\n<li>Now, on their paper, have students review the two emojis they drew and play back the connection between them; the story about a problem and solution.</li>\n</ul><br>`\t`Have a few volunteers quickly share their emoji stories. Conclude warm up by affirming the abilikty to use simple images to tell a powerful story."} {sdgColor} />

	<CustomSection title={"The Climate Action Grid"} content={"<p>`\t`Divide students into small groups (3-4 students). Provide each group with a Climate Action Grid handout or a large sheet of paper with a pre-drawn grid. The grid can also be drawn on the board and students can follow along using that as a guide.<br>`\t`The grid should have:\n<ul>\n<li><em>Rows:</em> Labeled with simple climate ideas (e.g., air pollution, melting ice, solar power, planting trees, recycling).</li>\n<li><em>Columns:</em> Labeled with Pop Art techniques (e.g., bold colors, repetition, everyday objects)</li>\n</ul><br>`\t`Instruct groups to work together to fill in the grid. For each box, they should brainstorm how they can use that specific Pop Art technique to show the idea in that row.<br>`\t`<a href=\"https://drive.google.com/file/d/1_wnkPSnnXooclGWxeS5XeS6DZ5fRA_QM/view?usp=drive_link\" target=\"_blank\" rel=\"noopener noreferrer\">EXAMPLE</a></p>"} {sdgColor} />

	<CustomSection title={"My Climate Action Poster"} content={"<p>`\t`Give each student a large sheet of paper and access to the art materials. Explain that each student will now create their own Pop Art poster about Global Goal 13: Climate Action. Remind students to use ideas from their group’s Climate Action Grid and the Pop Art techniques they learned.<br>`\t`Encourage students to:\n<ul>\n<li><em>Use bold colors and graphics:</em> Think about how street and Pop Art artists use bright colors and strong lines to make their art stand out.</li>\n<li><em>Show a story:</em> They can show a “before and after” or a “problem and solution”.</li>\n<li><em>Use repetition:</em> They can repeat an image, a shape, or a pattern to make a message feel stronger and more important.</li>\n<li><em>Use a catchy slogan:</em> They can add a few simple, bold words or a short phrase to make their message clear.</li>\n</ul><br>`\t`Circulate, offering support and encouragement, asking guiding questions like:\n<ul>\n<li>How are you using repetition to make your message powerful?</li>\n<li>What bold colors will you use to show a feeling of hope or warning?</li>\n<li>Can you make a simple, strong symbol for your poster?</li>\n<li>What story about a climate problem and solution are you trying to tell?</li>\n<li>How can you use elements from our brainstorm to create an eye-catching design?</li>\n</ul></p>"} {sdgColor} />

	<CustomSection title={"Presentation and Discussion"} content={"<p>`\t`Explain that students will now share their art. This can be through volunteer presentations or having students work in small groups to share.<br>`\t`Facilitate a class discussion about the posters, asking guiding questions like:\n<ul>\n<li>What are some of the most powerful or impactful posters you saw? What stood out to you?</li>\n<li>How did the different posters make you think differently about Global Goal 13 and the need for action?</li>\n<li>What are some of the common themes or messages you noticed in the art?</li>\n<li>How did the use of Pop Art techniques (like bold colors, repetition, or a catchy slogan) enhance the message of the artwork?</li>\n<li>What feelings did the artwork make you feel about climate action? (e.g., determined, hopeful, worried, ready to help).</li>\n</ul></p>"} {sdgColor} />

	<CustomSection title={"Reflection & Summary"} content={"<p>Have students reflect on their learning experience through discussion or writing.<br>Ask guiding questions like:\n<ul>\n<li>How did the bold colors, graphic style, and repetition help you communicate the urgency or the scale of climate change issues in your artwork?</li>\n<li>What did you learn about the power of popular imagery and everyday objects in art to make a serious message about climate change action more accessible or impactful?</li>\n<li>What new insights did you gain about Global Goal 13 and the importance of urgent action to combat climate change through this artistic expression?</li>\n<li>What is one key takeaway about climate action and the power of creative expression that you will remember from this lesson?</li>\n<li>What’s one small action you feel inspired to take this week to support climate action?</li>\n</ul></p>"} {sdgColor} />

	<CustomSection title={"Assessment"} content={"<ul>\n<li>Consistent and enthusiastic involvement in all phases of the lesson, including the warm up, brainstorm, individual poster creation, and class discussions.</li>\n<li>Understanding of the core concept of climate action (problems and solutions), as demonstrated through the symbolism and intention within the Pop Art posters and the verbal explanations during sharing and discussion.</li>\n<li>Originality and effectiveness in applying chosen Pop Art elements (e.g., bold colors, graphic style, repetition, popular culture references, text-typography, collage), to convey the message about climate action. Look for innovative visual interpretations.</li>\n<li>How clearly and powerfully the finished posters communicate the intended message about Global Goal 13. Does the artwork successfully evoke thought or emotion related to teh goal, or effectively highlight a climate challenge/solution?</li>\n<li>Ability to articulate learning and personal connections during the reflection and summary discussion.</li>\n</ul>"} {sdgColor} />

</div>
