<script lang="ts">
	import MaterialsList from './components/MaterialsList.svelte';
	import Introduction from './components/Introduction.svelte';
	import ReflectionQuestions from './components/ReflectionQuestions.svelte';
	import AssessmentCriteria from './components/AssessmentCriteria.svelte';
	import CustomSection from './components/CustomSection.svelte';
	import { getSdgColor } from '$lib/utils/sdg-colors';

	interface Props {
		sdgColor?: string;
	}

	let { sdgColor = getSdgColor(7) }: Props = $props();
</script>

<div class="lesson-content">

	<MaterialsList materials={[{"name":"Paper or notebooks","isOptional":false},{"name":"Pens/pencils","isOptional":false},{"name":"Images or videos showcasing the impact of energy issues, both positive and negative","isOptional":false},{"name":"\\[Optional\\] examples of persuasive writing","isOptional":true},{"name":"Speeches, opinion articles, persuasive essays, ads","isOptional":false}]} {sdgColor} />

	<CustomSection title={"Power of Persuasion: Championing Clean Energy With Creative Writing"} content={"<strong>(30-60 MINUTES)</strong>"} {sdgColor} />

	<Introduction content={"<p>Begin with a thought-provoking question or quote about energy, such as:<br><em> Imagine a world where everyone has access to clean, affordable energy. What would that world look like?<br></em> Is is possible to power the world without harming it?<br><em> Can we create a future where energy is both abundant and sustainable?<br></em> How can we ensure that the benefits of clean energy reach everyone, regardless of their location or income?<br><em> “We have a choice. We can remain addicted to fossil fuels with all the consequences that brings, or we can break the habit, embrace the clean energy alternatives and the new jobs they create.” \\- Barack Obama<br></em> “Renewable energy is not only good for the environment, it’s good for the economy.” \\- Paul Krugman<br><em> “The Stone Age didn’t end for lack of stones, and the oil age will end long before the world runs out of oil.” \\- Sheikh Zaki Yamani<br></em> Over 770 million people worldwide still lack access to electricity. Source: <a href=\"https://www.iea.org/reports/recommendations-of-the-global-commission-on-people-centred-clean-energy-transitions/recommendation-5\" target=\"_blank\" rel=\"noopener noreferrer\">International Energy Agency</a><br>Re-introduce Global Goal 7 if necessary: Ensure access to affordable, reliable, sustainable and modern energy for all.<br>Connect to students’ lives by facilitating a brief discussion about how energy impacts their daily lives, asking questions like:<br><em> How do you use energy at home, school, and in your community?<br></em> Have you ever experienced a power outage or energy shortage? How did it affect you?\n<ul>\n<li>What are some of the environmental impacts of energy production and consumption that you’re aware of?</li>\n</ul></p>"} />

	<CustomSection title={"Understanding Persuasive Writing"} content={"<p>Explain the purpose and key elements of persuasive writing, emphasizing the use of<br><em> </em>Strong arguments and evidence:<em> Facts, statistics, expert opinions, and personal anecdotes.<br></em> <em>Emotional appeals:</em> Connecting with the reader’s values, beliefs, and concerns.<br><em> </em>Call to action:<em> Clearly stating what the writer wants the reader to do or believe.<br>Examine examples of persuasive writing related to energy or other social issues. Identify the techniques used and discuss their effectiveness.<br>Examples:<br></em> <a href=\"https://www.npr.org/2019/09/23/763452863/transcript-greta-thunbergs-speech-at-the-u-n-climate-action-summit\" target=\"_blank\" rel=\"noopener noreferrer\">How Dare You</a>, Greta Thunberg<br><em> Thunberg uses powerful language and repetition to express her anger and frustration, directly addressing world leaders and accusing them of inaction.<br></em> Thunberg establishes her credibility by citing scientific evidence and highlighting the urgency of the climate crisis.<br><em> Thunberg demands immediate and drastic action to reduce greenhouse gas emissions.<br></em> <a href=\"https://www.storyofstuff.org/movies/story-of-bottled-water/\" target=\"_blank\" rel=\"noopener noreferrer\">The Story of Bottled Water,</a> The Story of Stuff Project<br><em> The video uses facts and statistics to debunk the myth that bottled water is safer or healthier than tap water.<br></em> The video reveals the environmental impact of bottled water production and the tactics used by corporations to create demand.<br><em> The video encourages viewers to reduce their reliance on bottled water and switch to reusable containers.<br></em> <a href=\"https://www.nrdc.org/bio/noah-long/renewable-energy-key-fighting-climate-change#:~:text=Mike%20Linenberger%20/%20NREL,no%20signs%20of%20slowing%20down.\" target=\"_blank\" rel=\"noopener noreferrer\">Renewable Energy is Key to Fighting Climate Change</a>, Noah Long &amp; Kevin Steinberger\n<ul>\n<li>This written piece uses clear explanations and examples to make the case for renewable energy as an impactful climate solution.</li>\n</ul></p>"} {sdgColor} />

	<CustomSection title={"Goal/Target Deep Dive and Brainstorming"} content={"<p>Distribute a <a href=\"https://docs.google.com/document/d/16ZmQ8CJovHgLOcGflCS6xQ97bObbU3utcuoiq6-GqKI/edit?usp=drive_link\" target=\"_blank\" rel=\"noopener noreferrer\">concise fact sheet</a> about Global Goal 7, highlighting key statistics, challenges, and potential solutions.<br>Explain that students can either choose the overall goal of Affordable and Clean Energy or focus on one specific target that resonates with them.<br>Encourage each student to reflect on the information presented and brainstorm potential arguments, evidence, and emotional appeals they could use int heir persuasive piece.<br>Ask students guiding questions to help them brainstorm:<br><em> What specific aspects of the goal or target do you find most compelling or important?<br></em> What facts or statistics from the fact sheet stand out to you?<br><em> Can you think of any personal stories or experiences that connect to this issue?<br></em> What emotions do you want to evoke in your readers?<br><em> What specific actions do you want your readers to take after reading your piece?<br>Example prompts<br></em> <em>Overall Global Goal 7</em><br><em> Why is affordable and clean energy essential for a sustainable future?<br></em> How does lack of access to energy impact individuals and communities?<br><em> What are the environmental and economic benefits of transitioning to clean energy sources?<br></em> <em>Target 7.1 \\- Access to Energy</em><br><em> How can we make energy more affordable and accessible for everyone, especially in developing countries?<br></em> What are the benefits of universal access to energy for education, healthcare, and economic opportunities?<br><em> </em>Target 7.2 \\- Renewable Energy<em><br></em> Why should we transition to renewable energy sources like solar and wind power?<br><em> How can we overcome the challenges associated with renewable energy adoption, such as cost and intermittency?<br></em> <em>Target 7.3 \\- Energy Efficiency</em><br><em> What are some simple and effective ways individuals and communities can reduce energy waste?<br></em> How can energy efficiency contribute to a more sustainable future and reduce our carbon footprint?<br><em> </em>Target 7.a \\- International Cooperation<em><br></em> Why is international collaboration essential for achieving clean energy goals?<br><em> How can developed countries support developing countries in their transition to clean energy?<br></em> <em>Target 7.b \\- Infrastructure and Technology</em><br><em> What are the key infrastructure and technology needs for expanding access to modern and sustainable energy services?<br></em> How can investments in clean energy infrastructure benefit both the environment and the economy?</p>"} {sdgColor} />

	<CustomSection title={"Persuasive Writing Workshop"} content={"<p>Briefly review the different persuasive writing formats and encourage students to choose one that best suits their interests and strengths.\n<ul>\n<li>Speech, letter, article, etc.</li>\n</ul><br>Remind students to consider their intended audience and tailor their language and tone accordingly.<br>Guide students in creating a simple outline to organize their main arguments, supporting evidence, and any emotional appeals they plan to use.<br>Briefly discuss the importance of a strong introduction, clear body paragraphs, and compelling conclusion.<br>Set a timer or watch the clock for 10 minutes, and allow students to focus on drafting their persuasive pieces.<br>Circulate the room, offering support and answering questions. Encourage students to use the fact sheet for reference and inspiration, and remind them to focus on clarity and persuasion.</p>"} {sdgColor} />

	<CustomSection title={"Power in Pairs: Peer Review"} content={"<p>Have students pair up (by choice or by assignment) and exchange their drafts with a partner.<br>Guide the peer review process with specific questions such as:<br><em> Are the arguments clear and well-supported by evidence?<br></em> Does the writing evoke emotions and connect with the reader?<br><em> Is there a clear call to action?<br></em> Are there any areas where the writing could be improved for clarity or impact?<br>If time permits, allow a few minutes for students to make quick revisions based on their partner’s feedback.</p>"} {sdgColor} />

	<ReflectionQuestions questions={["What new persuasive writing techniques did you learn or practice during this activity?","How did the process of researching and brainstorming help you develop your arguments?","What challenges did you encounter during the writing process, and how did you overcome them?","How did you feel about using your writing to advocate for a cause you care about?","Did this experience change your perspective on the power of individual voices and collective action?","In what other areas of your life could you apply persuasive writing skills?","What new insights did you gain about Global Goal 7 and the importance of affordable and clean energy?","How has this activity impacted your understanding of the challenges and opportunities related to energy access and sustainability?","What specific actions or changes are you inspired to make in your own life or community as a result of this project?"]} {sdgColor} />

	<AssessmentCriteria criteria={["Consistent and enthusiastic involvement in all phases of the lesson, including the initial energy discussion, understanding persuasive writing, brainstorming arguments, the individual writing process, and active participation in discussions (including peer review).","Comprehension of Global Goal 7 and its targets and core concepts (e.g., energy access, renewable energy, energy efficiency). This will be evidenced through the strength and accuracy of arguments within the persuasive writing and verbal explanations.","Originality and effectiveness in crafting persuasive writing that utilizes strong arguments, compelling evidence (even if fictionalized), emotional appeals, and a clear call to action to champion clean energy.","How clearly and powerfully the finished persuasive piece communicates its intended message about Global Goal 7\\. Did the writing successfully evoke thought, emotion, or a desire for action in the reader?","Quality of the writing craft, including strong verbs, vivid imagery, logical organization, and appropriate tone, demonstrating attention to persuasive language.","Ability to articulate persuasive choices adn to interpret and provide thoughtful feedback on classmates’ writing, connecting it to Global Goal 7 themes.","Nuance and depth of understanding demonstrated in reflections, particularly concerning the role of individual voices and persuasive writing in advocating for clean energy."]} {sdgColor} />

</div>
