<script lang="ts">
	import MaterialsList from './components/MaterialsList.svelte';
	import Introduction from './components/Introduction.svelte';
	import DiscussionPrompts from './components/DiscussionPrompts.svelte';
	import ReflectionQuestions from './components/ReflectionQuestions.svelte';
	import AssessmentCriteria from './components/AssessmentCriteria.svelte';
	import CustomSection from './components/CustomSection.svelte';
	import { getSdgColor } from '$lib/utils/sdg-colors';

	interface Props {
		sdgColor?: string;
	}

	let { sdgColor = getSdgColor(10) }: Props = $props();
</script>

<div class="lesson-content">

	<MaterialsList materials={[{"name":"Simple printmaking supplies","isOptional":false},{"name":"Recycled foam sheets (e.g., craft foam, foam trays","description":"clean, flat pieces), or thin, sturdy cardboard/cardstock for students to cut/carve. One piece per student (e.g., 4x6 inches or 5x7 inches)","isOptional":false},{"name":"\"Carving\" tools (pens, blunt pencils, etc., something with a hard, slightly pointed tip for pressing into foam)","isOptional":false},{"name":"Brayers, rollers, sponges, paintbrushes, or even fingers to spread ink.","isOptional":false},{"name":"Printing ink (tempera is a good option)","isOptional":false},{"name":"Paper for printing","isOptional":false},{"name":"Scissors (or other cutting tools), glue, other collage materials if wanted","isOptional":false},{"name":"Whiteboard or large chart paper","isOptional":false},{"name":"Markers","isOptional":false},{"name":"Notebooks or paper","isOptional":false},{"name":"Pens/Pencils","isOptional":false},{"name":"Scrap paper","isOptional":false}]} {sdgColor} />

	<CustomSection title={"Printing Our Future: Art for a Fairer World"} content={"<strong>(30-60 MINUTES)</strong>"} {sdgColor} />

	<Introduction content={"<p>Welcome students to an exciting art class. Explain that they will use their imaginations and creativity to explore a really important idea: Global Goal 10, Reduced Inequalities.<br>Clarify that Global Goal 10 is like a huge promise the world has made: a promise to make sure everyone, everywhere, has fair and equal chances. Emphasize that this means treating all people with respect, no matter their age, gender, background, abilities, or what they look like. It's about making sure everyone has the same opportunities to learn, grow, and succeed.<br>Show image examples of compelling printmaking examples from various artists and cultures. Explain that printmaking is a cool way to make art by creating an image on one surfact (like a foam block) and then pressing it onto paper to make many copies. Clarify that artists use printmaking to tell stories, share messages, and even make statements about fairness.<br>Examples:<br><em> <a href=\"https://www.artic.edu/artworks/117319/sharecropper\" target=\"_blank\" rel=\"noopener noreferrer\"></em>Sharecropper<em></a>, Elizabeth Catlett (Focus on how the bold lines show the strength and dignity of the subject, even through hardship. Explain she made art to show people's strength and fairness.)<br></em> <a href=\"https://www.metmuseum.org/art/collection/search/45434\" target=\"_blank\" rel=\"noopener noreferrer\"><em>The Great Wave off Kanagawa</em></a>, Hokusai (Focus on how the strong lines and bold, flat colors make a powerful image, and that many copies could be made.)<br><em> <a href=\"https://en.wikipedia.org/wiki/Barack_Obama_%22Hope%22_poster#/media/File:Barack_Obama_Hope_poster.jpg\" target=\"_blank\" rel=\"noopener noreferrer\"></em>Hope<em></a> or <a href=\"https://store.obeygiant.com/products/obey-offset-poster?srsltid=AfmBOor_zH-sZOPYDi-13aLKzBL5lqBsmF4cGE_OZ3LDHrVA9Wi1BR6n\" target=\"_blank\" rel=\"noopener noreferrer\"></em>Obey Giant<em></a>, Shepard Fairey<br>Facilitate a discussion about the characteristics of printmaking, asking guiding questions like:<br></em> What do you notice about these artworks? Do they have strong lines? Bold shapes? What are the colors like?<br><em> What messages or ideas do you think they are trying to convey? Do they make you think about important topics like fairness?<br></em> How do these artworks make you feel? Do they feel strong, thoughtful, or inspiring?<br><em> Why do you think artists like to make copies of their art? How can making many copies help share a message with more people?<br></em> How can printmaking be used to tell stories or raise awareness about being fair to everyone?</p>"} />

	<CustomSection title={"Pattern of Fairness"} content={"<p>Have all students prepare with a piece of scrap paper and a writing utensil.<br><em>Basic Fairness Pattern</em><br><em> Say: Imagine the idea of fairness. What simple shape or line pattern repeats and makes you think of fairness, equality, or everyone being included? (e.g., a circle repeating, alternating stripes, interlocking shapes, a hand repeated).<br></em> Have students quickly draw that simple pattern on their paper.<br><em>Unfairness Pattern</em><br><em> Say: Now, imagine unfairness. What kind of pattern would show things not being equal, or feeling stuck or left out? (e.g., a broken line repeating, one shape much bigger/smaller than others in a patter, a zig-zag that doesn't connect).<br></em> Have students quickly draw an unfairness pattern on their paper next to the first pattern.<br><em>Building a Solution Pattern</em><br><em> Say: Finally, how would a repeating pattern show building a solution or making things equal? It could start small and grow, or connect broken parts. (e.g., repeating arrows pointing forward, interlocking hands, a pattern of smiling faces, a pattern where broken lines come together).<br></em> Have students quickly draw a solution pattern on their paper.<br>Conclude this warm up by affirming creating pattern thinking, explaining that these patterns will help inspire their prints for Global Goal 10\\.</p>"} {sdgColor} />

	<CustomSection title={"Exploring Printmaking Techniques"} content={"<p>Explain that the class will focus on two main printingmaking techniques: Relief Printing (making a stamp) and Stenciling (cutting holes to paint through). Clarify that both are great for making bold, clear images that can be repeated. Note: If best for your class, focus on only one technique.<br><em>Relief Printing (Foam)</em><br><em> Demonstrate the process: Imagine you're making a stamp. You'll use a pencil to draw a picture into a soft foam sheet. The parts you press down will <strong>not</strong> rint, and the parts that stick up <strong>will</strong> print. Then you'll roll ink onto the raised parts and press it onto paper.<br></em> Show a simple example.<br><em> Ask guiding questions like:<br></em> What kinds of lines or shapes would be easy to press into foam for a print?<br><em> How can you make a bold picture that tells a clear story on your stamp?<br></em>Stenciling<em><br></em> Demonstrate the process: Stenciling is like cutting a cookie cutter. You'll cut a shape <strong>out</strong> of paper or cardboard/cardstock. Then you'll place the paper with the hole over another paper, and paint through the hole. When you lift the stencil, the shape is left behind.<br><em> Show a simple example.<br></em> Ask guiding questions like:<br><em> What kind of simple shapes would be good for a stencil?<br></em> How can you use a stencil to repeat a message or a symbol about fairness?</p>"} {sdgColor} />

	<CustomSection title={"Equality Symbol Sketch"} content={"<p>Divide students into small groups (3-4 students). Provide each student with a piece of paper for sketching and a range of colorful writing utensils.<br>For the next few minutes, have students quickly sketch as many visual symbols or simple drawings as they can that represent the following ideas for Global Goal 10: Reduced Inequalities. These ideas can be written on the board if you'd like students to draw based on all the ideas at once, or you can call out the ideas one at a time.<br>Ideas to Sketch:<br><em> </em>Fairness<em> (e.g., equal signs, a balanced scale, two hands shaking, a heart, a circle of diverse figures, two people the same height, a check mark for right).<br></em> <em>Inclusion/Everyone Belongs</em> (e.g., many different shapes/colors together, hands holding, a puzzle piece fitting in, open doors, a welcoming smile, people linking arms).<br><em> </em>Challenges/Unfairness<em> (e.g., a broken chain, a fence, one person outside a group, a tilted scale, a sad face, an X mark, a barrier, a question mark, someone pointing unfairly).<br></em> <em>Strength/Empowerment</em> (e.g., a strong fist, a star, a crown, a person standing tall, a lightbulb, an arrow pointing up, a lightning bolt).<br><em> </em>Working Together<em> (gears turning, people pulling a rope, hand building, interlocking shapes).<br>Instruct students to make their sketches simple and clear, suitable for a print or stencil.<br>Circulate, offering guidance and asking guiding questions like:<br></em> How can you draw a simple symbol for equal chances?<br><em> What does feeling left out look like as a simple drawing?<br></em> How could you show everyone belongs?<br>After the sketching time, instruct groups to quickly share their favorite symbols with each other, explaining what they mean.</p>"} {sdgColor} />

	<CustomSection title={"My Equality Print"} content={"<p>Explain that each student will now create their own print, using either the relief printing (foam stamp) or stenciling technique (or just giving one option if preferred). The prints will be inspired by the ideas and symbols from the brainstorming and Global Goal 10\\.<br>Remind students of the chosen technique:<br><em> </em>For Relief Printing (Foam):<em> Draw the design directly onto the foam with pencil, etc. Remember that the parts pressed down will be the white parts of the print, and the raised will be the color. Lines should be bold.<br></em> <em>For Stenciling:</em> Draw the design onto paper/cardboard/cardstock, then carefully cut out the parts that should be printed. The holes are where the color will go.<br>Emphasize:<br><em> </em>Clear Message:<em> What big ideas about fairness or equality to they want their print to show?<br></em> <em>Bold and Simple:</em> Keep the design clear and strong.<br><em> </em>Expressive Color:<em> Choose colors that help express the feeling of their message (e.g., bright for hope, strong for fairness, contrasting for a problem).<br>Circulate, offering support and encouragement. Ask guiding questions like:<br></em> How will your chosen symbol look clear on your print?<br><em> What colors will make your message about \\[fairness/inclusion/a challenge\\] stand out?<br></em> Are you thinking about how your print will help others understand Global Goal 10?</p>"} {sdgColor} />

	<DiscussionPrompts prompts={["What symbol or image did you see in this print?","What colors or lines made it stand out?","What big idea about fairness or equality (Global Goal 10\\) did this print make you think about?"]} {sdgColor} />

	<ReflectionQuestions questions={["How did creating prints with bold messages help you understand Global Goal 10: Reduced Inequalities in a new way?","What did you learn about the importance of everyone having fair chances and being treated with respect?","Which prints or ideas from your classmates made you think or feel the most about fairness and inclusion, and why?","What did these activities tell us about how we can all work towards Global Goal 10?","What's one small action you feel inspired to take this week to promote fairness and equality?"]} {sdgColor} />

	<AssessmentCriteria criteria={["Consistent and enthusiastic involvement in all phases of the lesson, including the warm up, brainstorm, individual print creation, and class discussions.","Understanding of the core concept of reduced inequalities (fairness, equal opportunity, inclusion, respect for all), as demonstrated through the symbolism and message in the print and verbal explanations.","Originality and effectiveness in creating the Equality Print. Look for evidence of connection to Global Goal 10 (does the print clearly represent an idea related to fairness, inclusion, or a challenge/solution?), use of printmaking techniques (are there attempts to use the chosen technique to create a clear, bold image?), and clarity of message (is the message about equality or fairness visually apparent?).","Ability to articulate learning and personal connections during the reflection and summary discussion."]} {sdgColor} />

</div>
