<script lang="ts">
	import MaterialsList from './components/MaterialsList.svelte';
	import Introduction from './components/Introduction.svelte';
	import ReflectionQuestions from './components/ReflectionQuestions.svelte';
	import AssessmentCriteria from './components/AssessmentCriteria.svelte';
	import CustomSection from './components/CustomSection.svelte';
	import { getSdgColor } from '$lib/utils/sdg-colors';

	interface Props {
		sdgColor?: string;
	}

	let { sdgColor = getSdgColor(6) }: Props = $props();
</script>

<div class="lesson-content">

	<MaterialsList materials={[{"name":"Selection of scripts or short plays centered around water and sanitation themes, tailored to age group","isOptional":false},{"name":"Copies of [scripts](https","description":"//docs.google.com/document/d/1J8cX34olrxxkvtpTjVBINUVmnFX7DkPyu4ibg00cmCM/edit?usp=drive_link) for each student, ideally with roles clearly marked","isOptional":false},{"name":"Space for performance","isOptional":false},{"name":"Whiteboard or large chart paper","isOptional":false},{"name":"Markers","isOptional":false},{"name":"Paper or notebooks","isOptional":false},{"name":"Pens/pencils","isOptional":false},{"name":"Simple props","isOptional":true}]} {sdgColor} />

	<CustomSection title={"Readers Theater for a Global Goal 6"} content={"<strong>(30-60 MINUTES)</strong>"} {sdgColor} />

	<Introduction content={"<p>**\\<br>`\t`Begin with a brief, impactful video clip showcasing either\n<ul>\n<li>The beauty of pristine water environments.</li>\n<li><a href=\"https://www.youtube.com/watch?v=KkhGT997hjs\" target=\"_blank\" rel=\"noopener noreferrer\">Planet Earth II - Islands: The Great Blue</a></li>\n<li><a href=\"https://www.youtube.com/watch?v=C_9D3LeKlsg\" target=\"_blank\" rel=\"noopener noreferrer\">Crystal Clear Blue Waters At Crater Lake National Park</a></li>\n<li><a href=\"https://www.youtube.com/watch?v=wIiri4wePAY\" target=\"_blank\" rel=\"noopener noreferrer\">Most Beautiful Waterfalls on Earth</a></li>\n<li>The stark reality of water scarcity or pollution.</li>\n<li><a href=\"https://www.youtube.com/watch?v=WRYRopQIotE\" target=\"_blank\" rel=\"noopener noreferrer\">Pollution Endangers Bangladesh's Rivers</a></li>\n<li><a href=\"https://www.youtube.com/watch?v=lDPkFykvZjc\" target=\"_blank\" rel=\"noopener noreferrer\">Water Doesn't Come from a Tap</a></li>\n<li><a href=\"https://www.pbs.org/video/water-crisis-1709500629/\" target=\"_blank\" rel=\"noopener noreferrer\">Mexico City residents struggle with worsening water crisis</a></li>\n<li>A success story of a community gaining access to clean water/sanitation.</li>\n<li><a href=\"https://www.youtube.com/watch?v=MVjwIaik3qg\" target=\"_blank\" rel=\"noopener noreferrer\">Plateau state gets a solar-driven motorized water facility and WASH facilities</a></li>\n<li><a href=\"https://www.youtube.com/watch?v=cQCsUDyGfP0\" target=\"_blank\" rel=\"noopener noreferrer\">Young African Girl Finally Gets Clean Water</a></li>\n<li><a href=\"https://www.youtube.com/watch?v=vfhgkRPXUqU\" target=\"_blank\" rel=\"noopener noreferrer\">Water is Life: Rural Empowerment Success Story</a></li>\n</ul><br>`\t`Re-introduce Global Goal 6 if needed: Ensure availability and sustainable management of water and sanitation for all.<br>`\t`Start an interactive Q&amp;A with students, asking questions like:\n<ul>\n<li>Why do YOU think clean water is important?</li>\n<li>Challenge students to think beyond just drinking, hygiene, health, etc.)</li>\n<li>Have you ever experienced a time when water WASN'T readily available?</li>\n<li>Travel, camping, even brief outages at home</li>\n<li>What's the grossest thing you can imagine about NOT having proper sanitation?</li>\n<li>Gets students thinking about the 'ick' factor, but keep it appropriate.</li>\n</ul></p>"} />

	<CustomSection title={"Script and Role Assignment"} content={"<p>**\\<br>`\t`Pre-select scripts aligned with Global Goal 6.\n<ul>\n<li>See <a href=\"https://docs.google.com/document/d/1J8cX34olrxxkvtpTjVBINUVmnFX7DkPyu4ibg00cmCM/edit?usp=sharing\" target=\"_blank\" rel=\"noopener noreferrer\">pre-written scripts</a> for reference, or source your own</li>\n</ul><br>`\t`Choose scripts based on the number of students in the class, and try to assign one role per student.\n<ul>\n<li>If there are fewer roles than students, consider doubling up on some minor roles or creating additional \"ensemble\" roles that contribute to the overall atmosphere or provide sound effects.</li>\n</ul><br>`\t`Students can also be assigned the role of \"directors,\" responsible for providing constructive feedback to the performers. This can include observations about clarity of speech, emotional expression, characterization, and overall effectiveness of the scene.<br>`\t`Potential challenges and how to address them:\n<ul>\n<li><em>Shy Students:</em> Offer alternative roles like narrator, ensemble, or stage manager if students are less comfortable with acting.</li>\n<li><em>Large Cast Scripts:</em> For scripts with many roles, consider adapting the script or creating additional ensemble roles to ensure everyone has a part.</li>\n</ul><br>`\t`Clearly mark the roles on the scripts, highlighting or underlining each character's lines to facilitate reading and avoid confusion during rehearsal time.<br>`\t`Encourage students to discuss their characters' motivations, emotions, and relationships to other characters before performing.<br>`\t`Emphasize the importance of teamwork and collaboration, and remind students to offer constructive feedback and encouragement to their peers.</p>"} {sdgColor} />

	<CustomSection title={"Rehearsal and Performance"} content={"<p>**\\<br>`\t`Begin by allowing students a short amount of time to read through their scripts, either individually or within their groups.<br>`\t`Encourage them to highlight/underline their lines, make short notes about their character's emotions and motivations, and identify any challenging vocabulary or phrases.<br>Depending on the complexity, length of scripts, and time constraints, decide if students get time to practice beforehand, or if the spontaneity of a cold read is more fitting.<br>Emphasize that the focus of Reader's Theater is on the power of the spoken word and the actors' ability to bring the characters and story to life through their voices and expressions.<br>`\t`Arrange chairs or create a designated performance area in the classroom. You can use a music stand or podium for scripts if available.<br>`\t`If desired, provide simple props like hats, scarves, or glasses to help differentiate characters and add a visual element to the performance.<br>`\t`Encourage students to experiment with different vocal tones, pitches, and volumes to convey their character's emotions and personalities.<br>`\t`Remind them to project their voices clearly so the audience can hear and understand the dialogue.<br>`\t`While the focus is on vocal delivery, encourage students to use subtle gestures and facial expressions to enhance their characterization and bring the scene to life.</p>"} {sdgColor} />

	<CustomSection title={"Post-Performance Analysis"} content={"<p>**\\<br>`\t`After all groups have performed, gather the class together for a comprehensive discussion that connects the individual performances to the broader themes of Global Goal 6. Ask questions such as:\n<ul>\n<li>Across all the scenes, which character or situation resonated with you the most?</li>\n<li>Were there any moments in the performances that particularly moved you or made you think differently about a certain issue?</li>\n<li>What common challenges or obstacles did you notice across the different scenes?</li>\n<li>How did the characters' actions or words reflect the broader challenges related to clean water and sanitation on a global scale?</li>\n<li>Did any of the conflicts presented resonate with your own experiences or observations?</li>\n<li>Were there any scenes that offered a sense of hope or presented potential solutions to the challenges portrayed?</li>\n<li>What were some of the actions or approaches suggested in the scripts that could contribute to achieving Global Goal 6?</li>\n<li>Even though these were fictional stories, can you identify any real-world parallels or examples of similar challenges and solutions?</li>\n</ul></p>"} {sdgColor} />

	<CustomSection title={"Reflection and Summary"} content={"<p>Have students reflect on their learning experience through discussion or writing.<br>Ask guiding questions like:\n<ul>\n<li>How did watching the Reader's Theater performances impact your understanding of the importance of clean water and sanitation?</li>\n<li>Which character or situation across all the scenes resonated with you the most, and why?</li>\n<li>Were there any moments in the performances that particularly moved you or made you think differently about a certain issue related to Global Goal 6?</li>\n<li>How did the actors' vocal delivery and emotional expression bring the characters and their struggles to life?</li>\n<li>What common challenges or obstacles related to clean water and sanitation did you notice across the different scenes?</li>\n<li>How did the characters' actions or words reflect the broader challenges related to clean water and sanitation on a global scale?</li>\n<li>Did any of the conflicts presented in the performances resonate with your own experiences or observations?</li>\n<li>Were there any scenes that offered a sense of hope or presented potential solutions to the challenges portrayed?</li>\n<li>How did the performances help you connect with the human element of the clean water and sanitation crisis?</li>\n<li>Did any of the scenes challenge your assumptions or make you think about the issue in a new way?</li>\n<li>What are some of the key takeaways from the performances that you think are important for others to understand about clean water and sanitation?</li>\n</ul></p>"} {sdgColor} />

	<CustomSection title={"Assessment"} content={"<ul>\n<li>Consistent and enthusiastic involvement in all phases of the lesson, including the initial video/discussion, script reading, rehearsal, and class discussion.</li>\n<li>Comprehension of Global Goal 6 and its targets and core concepts (e.g., water scarcity, pollution, sanitation access, ecosystem health). This will be evidenced through the thematic content and character portrayal within the Reader's Theater scenes and the verbal explanations.</li>\n<li>How clearly and powerfully students' vocal delivery and emotional expression communicated the message of the scene. Did the reading successfully evoke thought or empathy in the audience regarding water issues?</li>\n<li>Ability to use vocal tone, pacing, and subtle gestures to effectively differentiate between characters and bring them to life during the reading.</li>\n<li>Ability to work effectively within groups, demonstrating active listening, responsive reading, and a cohesive ensemble effort during the Reader's Theater performance.</li>\n<li>Nuance and depth of understanding demonstrated in reflections, particularly concerning the role of storytelling in understanding global water challenges and inspiring action.</li>\n<li>Ability to identify and articulate parallels between the fictional scenarios and real-world challenges related to clean water and sanitation during discussions.</li>\n</ul>"} {sdgColor} />

</div>
