<script lang="ts">
	import MaterialsList from './components/MaterialsList.svelte';
	import Introduction from './components/Introduction.svelte';
	import ReflectionQuestions from './components/ReflectionQuestions.svelte';
	import AssessmentCriteria from './components/AssessmentCriteria.svelte';
	import CustomSection from './components/CustomSection.svelte';
	import { getSdgColor } from '$lib/utils/sdg-colors';

	interface Props {
		sdgColor?: string;
	}

	let { sdgColor = getSdgColor(1) }: Props = $props();
</script>

<div class="lesson-content">

	<MaterialsList materials={[{"name":"Simple percussion instruments (e.g., drums, shakers, tambourines, rhythm sticks, or improvised instruments like buckets, pots, and pans) If instruments are limited, encourage students to find improvised instruments safely from the classroom (e.g., clapping hands, stomping feet, tapping pencils on desks, plastic containers as shakers, snapping fingers).","isOptional":false},{"name":"Audio","isOptional":false},{"name":"Whiteboard or large chart paper","isOptional":false},{"name":"Markers","isOptional":false},{"name":"Notebooks or Paper","isOptional":false},{"name":"Pens/Pencils","isOptional":false},{"name":"\\[Optional\\] lyrics or summaries of \"Songs of Hope and Change\"","isOptional":true}]} {sdgColor} />

	<CustomSection title={"Rhythms of Hope: Making Music for Global Goal 1"} content={"<strong>(15-45 MINUTES)</strong>"} {sdgColor} />

	<Introduction content={"<p>Welcome students to an exciting musical exercise. Begin with an introduction to exploring the important idea of Global Goal 1 through the power of rhythm and sound.<br><em> Explain that Global Goal 1 is like a commitment to ensure everyone, everywhere, has what they need to live a healthy, happy life. This means having enough food, a safe home, clean water, clothes, and a chance to go to school and feel healthy and happy. It's all about fairness and making sure no one is left behind.<br></em> Explain that music can make us feel strong, happy, determined, or even help us understand big challenges.\n<ul>\n<li>Today, the class will use rhythm and our voices to create \"Rhythms of Hope\", sounds that show what a world without poverty looks like and how we can all help make it happen.</li>\n</ul><br>Begin by discussing the United Nations' Global Goal 1: No Poverty, emphasizing its importance and urgency.<br>Share personal stories or examples of poverty's impact from students' own communities or from global events.<br>Briefly introduce the concept of music as a powerful tool for social change and empowerment.</p>"} />

	<CustomSection title={"Creating Our Own Rhythms of Resilience"} content={"<p>Divide students into smaller groups and provide them with large paper or a whiteboard.<br>Instruct each group to brainstorm and write down words or phrases associated with resilience, empowerment, and the fight against poverty.<br>Examples of words:<br><em> </em>Resilience:<em> Strength, courage, overcome, endure, persist, bounce back, stand tall, unyielding, spirit, grit, fortitude, survival, adapting, thriving.<br></em> <em>Empowerment:</em> Voice, power, agency, rights, justice, equality, uplift, support, enable, freedom, dignity, potential, self-worth, strength within.<br><em> </em>Fight Against Poverty:<em> Struggle, challenge, overcome, break free, resist, demand, change, advocate, solidarity, power, unite, hope, future, basic needs (food, water, shelter), opportunity, access.<br>Have each group create short rhythmic chant or song using their chosen words and phrases, incorporating elements from the protest songs they heard.<br>Perform and share the newly created rhythms with the whole class.<br>After each group performs their rhythm ask them to explain their creative choices using guiding questions like:<br></em> What words or phrases did your group choose to incorporate into your rhythm, and why did you select those specific words?<br><em> How did you use rhythm, repetition, and dynamics to emphasize certain words or ideas in your chant/song? What were you trying to highlight?<br></em> Did you incorporate any elements that reminded you of the protest songs we listened to? If so, how did those elements contribute to the feelign or message of your piece?<br><em> How does your group's rhythm, as a whole, represent the concept of resilience, empowerment, or the fight against poverty? What story or feeling were you trying to convey?<br></em> If you rhythm had a title, what would it be and why?</p>"} {sdgColor} />

	<ReflectionQuestions questions={["How did the process of creating your own rhythms and chants help you connect with the concepts of resilience and empowerment in the face of poverty?","What musical elements, like tempo, rhythm, and dynamics, did you find most effective in conveying the emotions and messages associated with the fight against poverty?","How did listening to and discussing protest songs influence your group's approach to creating your own rhythm?","What did you learn about the power of music to give voice to struggles and inspire hope, as seen in the protest songs and in your own creation?","How can the collective rhythm and shared musical experiences of the rhythm circle and group work mirror the idea of community solidarity in addressing poverty?","What personal feelings or thoughts about poverty arose for you during this musical exploration?","Did any specific lyrics or rhythms from the protest songs resonate with you on a personal level?","How did actively creating a rhythmic piece about resilience and empowerment make the concepts of \"No Poverty\" more tangible or impactful for you?","What did you learn about your own ability to express and connect with social issues through music and rhythm?","How might the experience of creating and sharing these \"rhythms of resilience\" influence your understanding of the human spirit in the face of adversity?","What role do you think music can play in creating social change and advocating for those experiencing poverty?","What is one key takeaway about the connection between music and the fight against poverty that you will remember from this lesson?"]} {sdgColor} />

	<AssessmentCriteria criteria={["Consistent and enthusiastic involvement in all phases of the lesson, including the rhythm circle, protest song exploration, collaborative rhythmic chant/song creation, and class discussions.","Comprehension of Global Goal 1, targets and concepts (e.g., economic hardship, social exclusion, resilience) as demonstrated through the words, phrases, and rhythmic choices within the chants/songs and verbal explanations.","Originality and effectiveness in crafting rhythmic chants or songs, incorporating chosen words/phrases and elements from protest songs, to convey messages about poverty and resilience.","How clearly and powerfully the finished rhythmic pieces communicated the intended message about poverty and resilience. Did the music successfully evoke thought or emotion in the audience?","Ability to work effectively within the small groups, contributing ideas, respecting diverse interpretations, and collaborating cohesively during the brainstorming and creation process.","Willingness and ability to maintain a steady beat, execute rhythmic patterns with reasonable precision, and blend sounds/voices effectively within the group, demonstrating musical awareness.","Nuance and depth of understanding demonstrated in reflections, particularly concerning the role of music in addressing social issues and the human experience of poverty."]} {sdgColor} />

</div>
