<script lang="ts">
	import MaterialsList from './components/MaterialsList.svelte';
	import Introduction from './components/Introduction.svelte';
	import ReflectionQuestions from './components/ReflectionQuestions.svelte';
	import AssessmentCriteria from './components/AssessmentCriteria.svelte';
	import CustomSection from './components/CustomSection.svelte';
	import { getSdgColor } from '$lib/utils/sdg-colors';

	interface Props {
		sdgColor?: string;
	}

	let { sdgColor = getSdgColor(8) }: Props = $props();
</script>

<div class="lesson-content">

	<MaterialsList materials={[{"name":"Classroom space suitable for acting and movement","isOptional":false},{"name":"Whiteboard or projector","isOptional":false},{"name":"Markers or pens","isOptional":false},{"name":"Whiteboard or large chart paper","isOptional":false},{"name":"Markers","isOptional":false},{"name":"Notebooks or paper","isOptional":false},{"name":"Pens/Pencils","isOptional":false},{"name":"Costumes and props (optional, but encouraged for enhanced immersion)","isOptional":true},{"name":"Scripts or scenarios based on SDG 8 targets (see examples below)","isOptional":false},{"name":"Character profiles and background information for role","description":"playing","isOptional":false}]} {sdgColor} />

	<CustomSection title={"Staging Change: Exploring Decent Work and Economic Growth Through Drama"} content={"<strong>(30-60 MINUTES)</strong>"} {sdgColor} />

	<Introduction content={"<p>Setting the Stage: Begin by asking students to share their dream jobs or career aspirations. Discuss the importance of work in their lives and in society.<br>Introducing SDG 8: Introduce the UN Sustainable Development Goals and focus on Goal 8: Decent Work and Economic Growth. Briefly explain the core idea of ensuring fair and sustainable working conditions for everyone while promoting global economic progress.</p>"} />

	<CustomSection title={"Exploring Drama Techniques"} content={"<p>Warm-up Activities: Engage students in warm-up activities like vocal exercises, improvisation games, and physical warm-ups to build confidence and encourage creative expression.<br>Introducing Key Concepts: Discuss key drama techniques like role-playing, character development, improvisation, and creating believable scenes. Explain how these techniques can be used to explore complex issues and perspectives.</p>"} {sdgColor} />

	<CustomSection title={"Drama and Global Goal 8"} content={"<p>Target Focus: Divide students into smaller groups. Assign each group a specific target from SDG 8 (or allow them to choose one that interests them). Provide each group with the SDG 8 handout and any relevant character profiles or background information.<br>Scenario Development: Provide each group with a script or scenario based on their target.<br><a href=\"https://docs.google.com/document/d/1khvolqMm3Hr_Ko9vSFwiVxMKhps5WKolFsfZ9KjvSNA/edit?usp=sharing\" target=\"_blank\" rel=\"noopener noreferrer\">Scripts</a><br>Rehearsing and Performing: Allow time for groups to rehearse their scenes, develop their characters, and plan their performances. Encourage them to use costumes, props, and creative staging to enhance their presentations.<br>Performances and Discussion: Have each group perform their scene for the class. After each performance, facilitate a discussion about the issues raised in the scene, the characters' perspectives, and potential solutions or actions.</p>"} {sdgColor} />

	<ReflectionQuestions questions={["How did stepping into different roles and performing a scene about Global Goal 8 help you understand the complexities of decent work and economic growth on a deeper level?","What emotions did you connect with while portraying your character's experiences, and how did those emotions relate to the challenges or opportunities of work?","Did the act of physically embodying a situation related to fair wages, child labor, or safe conditions change your perspective on these issues?","What did you learn about the unspoken struggles or triumphs related to work that can be conveyed through dramatic expression?","How did the interaction with your scene partners (or the audience in a forum theater setting) deepen your understanding of diverse perspectives on work?","What did you learn about the power of storytelling and theatrical representation in raising awareness about social issues like decent work?","How can drama highlight the human impact of ecnomic systems or policy decisions?","What role did creativity and collaboration play in developing and performing your scene, and how does that relate to addressing global challenges?","Did the themes explored in your scene, or in others' scenes, resonate with any of your own observations or experiences related to work, fairness, or economic opportunity?","What key messages about decent work and economic growth do you think the scenes conveyed most powerfully?","How has this lesson influenced your thinking about your own future work or how you might contribute to a more just and equitable economy?","How can drama continue to be a tool for you, personally, to engage with and advocate for social change?"]} {sdgColor} />

	<AssessmentCriteria criteria={["Consistent and enthusiastic involvement in all phases of the lesson, including the warm-up activities, scenario development, scene rehearsals, performances, and class discussions.","Comprehension of Global Goal 8 and its targets and core concepts (e.g., fair wages, safe working conditions, ending child labor). This will be evidenced through the relevance and accuracy of the scenarios and verbal explanations.","Originality and effectiveness in utilizing key drama techniques such as role-playing, character development (vocal and physical), improvisation, and basic staging to explore and communicate themes related to decent work.","How clearly and powerfully the improvised or rehearsed scenes communicated the intended message about Global Goal 8 and any chosen themes/concepts. Did the performance successfully evoke thought or empathy in the audience?","How well students stepped into the shoes of different characters affected by work-related issues (e.g., a struggling farmer, a factory worker, a policy maker), conveying their motications and challenges authentically.","Ability to work effectively and respectfully within the small groups, contributing ideas, sharing responsibilities, and collaborating cohesively during scene development and performance.","Creativity, realism, and potential impact of the solutions or actions presented within the scenes or discussed during the post-performance analysis.","Nuance and insight demonstrated in reflections, particularly concerning the human experience of work and economic justice, and the role of drama in addressing social issues."]} {sdgColor} />

</div>
