<script lang="ts">
	import Introduction from './components/Introduction.svelte';
	import DiscussionPrompts from './components/DiscussionPrompts.svelte';
	import ReflectionQuestions from './components/ReflectionQuestions.svelte';
	import AssessmentCriteria from './components/AssessmentCriteria.svelte';
	import CustomSection from './components/CustomSection.svelte';
	import { getSdgColor } from '$lib/utils/sdg-colors';

	interface Props {
		sdgColor?: string;
	}

	let { sdgColor = getSdgColor(12) }: Props = $props();
</script>

<div class="lesson-content">

	<CustomSection title={"The Sound of Sustainability: Creating a Circular Rhythm Piece"} content={"<strong>(30-60 MINUTES)</strong>"} {sdgColor} />

	<CustomSection title={"Materials:"} content={"<p>A variety of percussion instruments (drums, shakers, woodblocks, etc.)<br>Recycled materials that can be used as instruments (buckets, bottles, cans, cardboard boxes, etc.)<br>Audio<br>Whiteboard or large chart paper<br>Markers<br>Notebooks or paper<br>Pens/Pencils<br>Large drawing paper</p>"} {sdgColor} />

	<Introduction content={"<p>`\t`Welcome students to an exciting music class. Explain that they will use the power of rhythm and sound to explore a really important idea: Global Goal 12, Responsible Consumption and Production.<br>`\t`Clarify that Global Goal 12 is like a huge promise the world has made: a promise to be smarter about the things we use and make. Emphasize that this means:\n<ul>\n<li><em>Being mindful:</em> Thinking about what we buy and if we really need it.</li>\n<li><em>Reducing waste:</em> Using less, and throwing away less.</li>\n<li><em>Reusing and recycling:</em> Finding new lives for old things.</li>\n</ul><br>`\t`It’s about making things in a way that’s good for the planet and making sure we don’t use up all our planet’s resources, so there’s enough for a long time.<br>`\t`Introduce the concept of a circular rhythm. Explain that a circular rhythm is a pattern that repeats and then comes back to its starting point, like a circle.<br>`\t`Clarify that in music, a circular rhythm can be used to show the idea of a circular economy—the idea that old materials can be reused and recycled over and over, so they don’t get thrown away as waste. Explain that today, the students will become rhythm composers, creating a musical story about the life of an object, from when it is brand new to when it is used, but gets a new life.<br>`\t`Introduce basic rhythm concepts:\n<ul>\n<li><em>Beat:</em> The steady pulse of the music.</li>\n<li><em>Rhythm:</em> A pattern of sounds and silences.</li>\n<li><em>Ostinato:</em> A repeated musical pattern.</li>\n</ul><br>`\t`Demonstrate simple circular rhythms using percussion instruments and/or recycled materials. Example:\n<ul>\n<li>Play a steady beat on a drum, a short rhythmic pattern on a shaker, and a different pattern on a woodblock, explaining how they can be layered and combined to create a more complex musical piece.</li>\n</ul></p>"} />

	<CustomSection title={"Warm Up: The Recycled Beat"} content={"<p>`\t`Explain that the class will explore how recycled items can be used to make music. Instruct the class to take a recycled item (e.g., plastic bottle, cardboard box, a can, etc.) and use it as an instrument.\n<ul>\n<li><em>Your Beat:</em> Instruct students to create a simple, repetitive rhythmic beat on their recycled instruments.</li>\n<li><em>The Sound:</em> Instruct students to make a sound that represents their recycled instrument (e.g., a tapping sound for a can, a shaking sound for a bottle).</li>\n<li><em>The Story:</em> Instruct students to say a word or short phrase that represents the recycled theme (e.g., “I am a can!” “I used to carry water for people to drink!” etc.)</li>\n</ul><br>`\t`Have students think about these three prompts to themselves, and practice quietly. Then, ask for volunteers to share their Beat/Sound/Story with the class.<br>`\t`Conclude warm up by affirming the creativity, explaining that the students will continue to use the recycled materials and their imaginations in this way to create music for Global Goal 12.</p>"} {sdgColor} />

	<CustomSection title={"The Transformation Circle"} content={"<p>`\t`Divide students into small groups (3-4 students). Provide each group with a large piece of paper and markers/writing utensils.\n<ul>\n<li><em>Draw the Circle of Life:</em> Instruct groups to draw a large circle on their paper and divide it into three sections, like slices of a pie. The circle represents the whole life of an object. Instruct students to draw arrows around the circle to show the flow of the cycle.</li>\n<li><em>The Beginning (New Object):</em> In the first section, instruct groups to draw a simple picture or write a few words that show an object being used for the first time. Instruct them to think about what sounds or rhythms would represent this part of the story.</li>\n</ul><br>Examples: A person happily using a new cup (light, cheerful taps or gulps), a factory making a plastic bottle (fast, repetitive clicks), a family eating a meal from a takeout box (happy, clinking sounds, chewing).\n<ul>\n<li><em>The Problem (Waste):</em> In the next section, instruct groups to draw or write about what happens when the object is finished with its first job. This is where the problem or challenge of waste happens. Instruct students to think about what sounds or rhythms would represent this part of the story.</li>\n</ul><br>Examples: A bottle is thrown in the trash (heavy, dull thud), the takeout box is left on the street (a quiet, lonely rhythm), a pen is out of ink (a frustrated, tapping sound).\n<ul>\n<li><em>The Solution (Reuse/Recycle):</em> In the third section, instruct groups to draw or write how that object gets a second life or is used in a responsible way. This is where the solution happens. Instruct them to think about what sounds or rhythms would represent this part of the story.</li>\n</ul><br>Examples: The bottle is put in a recycling bin (a clear, bright clink), the takeout box is composted and helps a garden grow (a gentle, earthy rhythm), a broken toy is fixed and can be played with again (a happy, joyful beat).<br>`\t`Circulate, offering guidance and asking guiding questions like:\n<ul>\n<li>How does your drawing show the problem with the object?</li>\n<li>What sounds would you hear in the solution part?</li>\n<li>Are you thinking about how the rhythm can tell a story in a circle?</li>\n</ul><br>`\t`This brainstorm helps to create a narrative for the upcoming rhythmic pieces.</p>"} {sdgColor} />

	<CustomSection title={"Group Exploration and Composition"} content={"<p>`\t`Explain that each group will create a short circular rhythm piece (about 45-60 seconds long) based on the storyboard they just made. The piece should tell the object’s story using rhythm, repetition, and a sense of coming back to the beginning.<br>`\t`Instruct groups to:\n<ul>\n<li><em>Choose instruments:</em> Select instruments (including recycled materials) to create their rhythms.</li>\n<li><em>Compose a short phrase:</em> Compose a short musical phrase or ostinao (a repeated pattern) that represents each step of their storyboard (e.g., one simple pattern for “use,” one for “waste,” and one for “reuse/recycle”).</li>\n<li><em>Create a cohesive piece:</em> Put the rhythms together in a way that tells the story in a loop (e.g. use rhythm → waste rhythm → reuse rhythm → back to use rhythm).</li>\n<li><em>Practice:</em> Rehearse the rhythm, ensuring everyone in the group knows their part.</li>\n</ul><br>`\t`Provide a simple rhythmic pulse for all groups to use as a foundation.<br>`\t`Examples:\n<ul>\n<li><a href=\"https://www.youtube.com/watch?v=xpiVrEET-YQ\" target=\"_blank\" rel=\"noopener noreferrer\">120 BPM - Metronome</a></li>\n<li><a href=\"https://www.youtube.com/watch?v=v900d5tVw6E\" target=\"_blank\" rel=\"noopener noreferrer\">80 BPM - Metronome</a></li>\n<li><a href=\"https://www.youtube.com/watch?v=jYCppV1bhy4\" target=\"_blank\" rel=\"noopener noreferrer\">50 BPM - Metronome</a></li>\n</ul><br>`\t`Circulate, offering guidance and encouraging creative choices with guiding questions like:\n<ul>\n<li>How are you using your instruments to show the change from waste to reuse?</li>\n<li>What rhythm makes your piece feel like a full circle?</li>\n</ul></p>"} {sdgColor} />

	<CustomSection title={"Circular Rhythm Performance"} content={"<p>`\t`Have each group perform their rhythm for the class. Instruct the audience to listen carefully to the repeating pattern of each group’s rhythm, paying attention to its sound and story. If helpful, continue to play the steady beat in the background.<br>`\t`After all groups have performed, open a discussion with guiding questions like:\n<ul>\n<li>What did you notice about the rhythms? What part of the objects’ stories did you hear?</li>\n<li>How did the other groups’ rhythms sound different than yours? What were unique about the rhythms you heard?</li>\n</ul></p>"} {sdgColor} />

	<CustomSection title={"Layered Jam (Building Harmony)"} content={"<p>`\t`Select two or three groups and have them perform their rhythms together at the same time, or in a round format. This will allow the class to listen to how different rhythmic patterns can combine to create a new, shared, and more complex sound.<br>`\t`After a few groups have performed the layered rhythms, ask guiding questions like:\n<ul>\n<li>What did you notice about how the rhythms blended together? Did it sound like a happy, harmonious rhythm or a chaotic, noisy one?</li>\n<li>What did the combined rhythms sound like? Did it sound like a busy factory, a happy community, or something else?</li>\n</ul></p>"} {sdgColor} />

	<CustomSection title={"Collective Discussion"} content={"<p>`\t`Conclude the performance session with a brief discussion on how the individual rhythms came together, with guiding questions like:\n<ul>\n<li>How did hearing each rhythm on its own help you understand its unique story?</li>\n<li>How did hearing the rhythms layered together feel different? What did that tell you about how all of our individual choices (about wate, recycling, etc.) connect to create one big, collective result?</li>\n</ul></p>"} {sdgColor} />

	<CustomSection title={"Reflection & Summary"} content={"<p>Have students reflect on their learning experience through discussion or writing.<br>Ask guiding questions like:\n<ul>\n<li>How did creating a circular rhythm piece help you to understand the concept of a circular economy and its connection to responsible consumption and production?</li>\n<li>What did you learn about how different sounds and rhythms can represent various aspects of sustainability, like resource use, waste reduction, or renewable energy?</li>\n<li>Did using recycled materials as instruments change your perspective on waste or the potential for reuse?</li>\n<li>What did you discover about the power of music to communicate complex ideas in a way that is both engaging and thought provoking?</li>\n<li>What new insights did you gain about Global Goal 12 and the importance of sustainable consumption and production patterns through this musical exploration?</li>\n<li>Did the lesson make you think differently about your own relationship with consumption and its impact on the environment? How?</li>\n<li>How can music help us to imagine and create a more sustainable future?</li>\n<li>What emotions did you connect with during this musical activity, and how might those emotions motivate you to take action related to Global Goal 12?</li>\n<li>What is one key takeaway about responsible consumption and the power of creative expression that you will remember from this lesson?</li>\n</ul></p>"} {sdgColor} />

	<CustomSection title={"Assessment"} content={"<ul>\n<li>Consistent and enthusiastic involvement in all phases of the lesson, including warm up, rhythm exploration, brainstorm, collaborative composition, and class discussions.</li>\n<li>Comprehension of Global Goal 12 and its core concepts. This will be evidenced through the symbolism and intention within the rhythmic patterns and verbal explanations during sharing and discussion.</li>\n<li>Originality and effectiveness in crafting rhythmic phrases or ostinatos, using recycled objects to convey messages about responsible consumption and production.</li>\n<li>Clarity and power of the collective rhythmic piece, and communication of its intended message about Global Goal 12. Did the combined sounds successfully evoke thought or emotion related to the goal?</li>\n<li>Ability to work effectively within the groups, contributing ideas, listening to others’ musical contributions, and collaborating cohesively to create the layered rhythm.</li>\n<li>Ability to maintain a steady beat, execute rhythmic patterns with reasonable precision, and blend sounds effectively within the ensemble, demonstrating musical awareness.</li>\n<li>Nuance and depth of understanding demonstrated in reflections, particularly concerning the role of music in advocating for sustainable development and the complexities of consumption patterns.</li>\n</ul>"} {sdgColor} />

</div>
