<script lang="ts">
	import Introduction from './components/Introduction.svelte';
	import DiscussionPrompts from './components/DiscussionPrompts.svelte';
	import ReflectionQuestions from './components/ReflectionQuestions.svelte';
	import AssessmentCriteria from './components/AssessmentCriteria.svelte';
	import CustomSection from './components/CustomSection.svelte';
	import { getSdgColor } from '$lib/utils/sdg-colors';

	interface Props {
		sdgColor?: string;
	}

	let { sdgColor = getSdgColor(13) }: Props = $props();
</script>

<div class="lesson-content">

	<CustomSection title={"DRAMA"} content={"<strong>The Climate Call: Immersive Drama and a Resilient World</strong>"} {sdgColor} />

	<CustomSection title={"(30-60 MINUTES)"} content={"<strong>Materials:</strong><br>Scripts<br>Chairs arranged in a circle or an open space to create a “community meeting” setting<br>Audio<br>Sound effects: wind, rain, sirens, crackling fire (can be downloaded or created by students)<br>[Optional] Simple props to represent different elements (e.g., blue fabric for water, brown paper for soil, green cloth for a plant, a plastic bottle, a thermometer, etc.)<br>Whiteboard or large chart paper<br>Markers<br>Notebooks or paper<br>Pens/Pencils"} {sdgColor} />

	<Introduction content={"<p>Begin with an introduction to Immersive theater. Explain that it’s a form of theater designed to break down the traditional barrier between performers and audience.<br>Highlight its key characteristics:\n<ul>\n<li>Audience members are active participants, not just passive observers.</li>\n<li>The performance often takes place in a non-traditional theater space.</li>\n<li>The audience may be able to move freely, interact with the performers, and influence the story.</li>\n<li>It aims to create a more visceral and engaging experience.</li>\n</ul><br>Give examples of Immersive theater productions:\n<ul>\n<li>“Sleep No More” by “Punchdrunk” Productions, probably the most well-known example.</li>\n<li><em>The Setting:</em> Takes place in a large, multi-story building transformed into a stylized version of the Macbeth story.</li>\n<li><em>Audience Experience:</em></li>\n<li>Audience members wear masks, emphasizing their role as observers.</li>\n<li>They are free to roam the space, choosing where to go and what to watch.</li>\n<li>The story unfolds simultaneously in different rooms, so each audience member has a unique experience.</li>\n<li>Performers can interact with audience members directly, leading them to secret locations or engaging them in brief encounters.</li>\n<li><em>Key Features:</em></li>\n<li><em>Non-linear storytelling:</em> The narrative is fragmented and relies on the audience to piece it together.</li>\n<li><em>Sensory immersion:</em> The production engages all the senses through detailed sets, lighting, sound, and even smells.</li>\n<li><em>Active participation:</em> The audience is not passive but actively explores and interprets the performance.</li>\n</ul><br>Facilitate a brief discussion, asking open ended questions like:\n<ul>\n<li>What are your initial ideas about what Immersive theater might be like?</li>\n<li>How does it differ from traditional plays?</li>\n<li>What are the potential benefits of making the audience more involved?</li>\n</ul><br>Introduce or reintroduce Global Goal 13: Take urgent action to combat climate change and its impacts.<br>Emphasize the urgency of the climate crisis and the need for immediate action. Briefly review any key targets and indicators.<br>Engage students in a thought-provoking discussion about how Immersive Theare can be used to explore climate change. Ask questions like:\n<ul>\n<li>How can immersive techniques make the audience feel more directly impacted by the climate crisis?</li>\n<li>Can audience participation encourage a sense of agency and responsibility?</li>\n<li>How can immersive theater create a space for dialogue and reflection on climate action?</li>\n</ul></p>"} />

	<CustomSection title={"Immersive theater Performance"} content={"<p>Arrange chairs or space and any other setting materials to create a “community meeting” atmosphere.<br>Briefly explain to the audience that they are participants in the meeting.<br>Choose 4-8 students to be the actors (or let students volunteer).<br>Assign roles in the script.<br>Remind student actors that they can read their lines, but also try their best to engage with the audience and create a realistic interaction.<br>The student actors perform the immersive theater script. Encourage them to:\n<ul>\n<li>Move around the space and interact with the audience.</li>\n<li>Use their voices and bodies to convey emotion and urgency.</li>\n<li>Create a believable and engaging scenario.</li>\n</ul><br>The audience members:\n<ul>\n<li>Are encouraged to react as they would in a real community meeting (e.g., ask questions, express concerns, offer suggestions).</li>\n<li>Should be respectful of the actors and the performance.</li>\n<li>Can take notes or write down their thoughts during the performance.</li>\n</ul><br>[Optional] Use sound effects and lighting to enhance the immersive experience.</p>"} {sdgColor} />

	<CustomSection title={"Post-Performance Discussion"} content={"<p>Facilitate a discussion to reflect on the performance and its connection to Global Goal 13.<br>Post questions like:\n<ul>\n<li>How did the immersive nature of the performance affect your understanding of the climate crisis?</li>\n<li>What emotions or ideas were evoked by the experience?</li>\n<li>Which aspects of Global Goal 13 were addressed in the play?</li>\n<li>What did you learn about the importance of community involvement and decision-making?</li>\n<li>How can immersive theater be a tool for raising awareness and inspiring action on climate change?</li>\n</ul></p>"} {sdgColor} />

	<CustomSection title={"Reflection and Summary"} content={"<p>Have students reflect on their learning experience through discussion or writing.<br>Ask guiding questions like:\n<ul>\n<li>How did the immersive nature of the theater experience - being part of the “community meeting” - affect your emotional and intellectual understanding of the climate crisis?</li>\n<li>What sensations or feelings did you experience during the performance that made the issue of climate change feel more immediate or real to you?</li>\n<li>Did actively participating or having the opportunity to intervene change your perspective on the agency and responsibility individuals and communities have in addressing climate action?</li>\n<li>How did hearing different perspectives from the characters (e.g., mayor, scientist, fearful resident, resilient resident) illuminate the complexities of making decisions about climate adaptations?</li>\n<li>What did you learn about the human element of climate change that might not come across in a news report or scientific paper?</li>\n<li>What new insights did you gain about Global Goal 13 and the importance of urgent action to combat climate change and its impacts through this immersive exploration?</li>\n<li>How did the play highlight specific challenges or opportunities related to Global Goal 13 concepts, such as strengthening resilience (13.1 or integrating climate measures (13.2)?</li>\n<li>Did the activity make you think differently about the role of community involvement and decision-making in climate action?</li>\n<li>What common themes or powerful messages about climate resilience and adaptation emerged from the performance and subsequent discussion?</li>\n<li>How can experiencing a scenario firsthand, even in a theatrical setting, help us to understand the urgency of Global Goal 13?</li>\n<li>Did any specific moment or character in the immersive experience resonate with you personally, sparking a stronger connection to the climate crisis?</li>\n<li>What emotions did you connect with during this lesson, and how might those emotions motivate you to contribute to climate solutions?</li>\n<li>How has this lesson influenced your thinking about your own role in advocating for a more sustainable future in your daily life or community?</li>\n</ul></p>"} {sdgColor} />

	<CustomSection title={"Assessment"} content={"<ul>\n<li>Consistent and enthusiastic involvement in all phases of the lesson, including the introduction to immersive theater, participation in the performance (as actors or active audience members), and engagement in class discussions.</li>\n<li>Comprehension of Global Goal 13 concepts and their connection to climate change impacts, adaptation, and resilience, as demonstrated through character portrayal (if acting), audience interventions, and verbal explanations during discussion.</li>\n<li>Originality and effectiveness of student actors in portraying the roles within the immersive context, including the ability to convey emotion, interact with the audience, and improvise responses to interventions.</li>\n<li>Audience members’ ability to observe the scenario critically, identify moments for intervention, and propose thoughtful and relevant alternative actions or solutions during the forum theater segments.</li>\n<li>Quality of suggested solutions and interventions, considering creativity, feasibility, and potential to address the climate challenges presented in the scenario. This demonstrates an understanding of individual and collective agency.</li>\n<li>Nuance and insight demonstrated in reflections, particularly concerning the emotional impact of immersive experience, the role of theater in addressing global challenges, and the complexities of climate action.</li>\n</ul>"} {sdgColor} />

</div>
