<script lang="ts">
	import Introduction from './components/Introduction.svelte';
	import DiscussionPrompts from './components/DiscussionPrompts.svelte';
	import ReflectionQuestions from './components/ReflectionQuestions.svelte';
	import AssessmentCriteria from './components/AssessmentCriteria.svelte';
	import CustomSection from './components/CustomSection.svelte';
	import { getSdgColor } from '$lib/utils/sdg-colors';

	interface Props {
		sdgColor?: string;
	}

	let { sdgColor = getSdgColor(12) }: Props = $props();
</script>

<div class="lesson-content">

	<CustomSection title={"The Rhythm of Re-use"} content={"<strong>(30-60 MINUTES)</strong>"} {sdgColor} />

	<CustomSection title={"Materials:"} content={"<p>A variety of percussion instruments (drums, shakers, woodblocks, etc.)<br>Recycled materials that can be used as instruments (buckets, bottles, cans, cardboard boxes)<br>Audio<br>Whiteboard or large chart paper<br>Markers<br>Notebooks or paper<br>Pens/Pencils</p>"} {sdgColor} />

	<Introduction content={"<p>Introduce or reintroduce Global Goal 12: Responsible Consumption and Production. Emphasize its importance in achieving a sustainable future. Briefly review and explain some of the key targets.<br>Facilitate a class discussion.\n<ul>\n<li>What are some of the sounds you might associate with consumption? (e.g., packaging being opened, machines running, vehicles)?</li>\n<li>What are some of the sounds you associate with sustainability? (e.g., nature sounds, renewable energy sources, recycling processes)?</li>\n<li>How can music and sound be used to represent these different aspects of consumption and production?</li>\n</ul><br>Introduce musical concepts and explain the concept of a “circular rhythm” as a metaphor for the circular economy.\n<ul>\n<li>In music, a circular rhythm is a pattern that repeats and returns to its starting point. It can represent the idea of materials flowing in a closed floop, rather than being discarded as waste.</li>\n</ul><br>Introduce basic rhythmic concepts\n<ul>\n<li><em>Beat:</em> The steady pulse of the music.</li>\n<li><em>Rhythm:</em> The arrangement of sounds and silences.</li>\n<li><em>Ostinato:</em> A repeated musical pattern.</li>\n</ul><br>Demonstrate simple circular rhythms using percussion instruments.<br>Example:\n<ul>\n<li><em>Instrument 1:</em> Plays a steady beat on a drum.</li>\n<li><em>Instrument 2:</em> Plays a short rhythmic pattern on a shaker that repeats.</li>\n<li><em>Instrument 3:</em> Adds a different pattern on a woodblock, also repeating.</li>\n</ul><br>Explain how these rhythms can be layered and combined to create a more complex musical piece.</p>"} />

	<CustomSection title={"Group Exploration and Composition"} content={"<p>Divide students into small groups (4-5 students)<br>Assign each group a specific target or aspect of Global Goal 12 to focus on, or let groups focus on the Goal as a whole. Examples:\n<ul>\n<li><em>Group 1:</em> Sustainable Use of Natural Resources (Target 12.2)</li>\n<li><em>Group 2:</em> Food Waste Reduction (Target 12.3)</li>\n<li><em>Group 3:</em> Sustainable Product Design (Connecting to Targets 12.5 and 12.6)</li>\n<li><em>Group 4:</em> Consumer Awareness (Target 12.8)</li>\n<li><em>Group 5:</em> Renewable Energy (Connecting to Targets 12.a and 12.c)</li>\n</ul><br>Each group will:<br>Discuss and lightly research their assigned aspect of Goal 12.<br>Brainstorm sounds and rhythms that represent their topic.<br>Examples:\n<ul>\n<li><em>Group 1 (Natural Resources):</em> Sounds of flowing water, wind, deforestation, mining.</li>\n<li><em>Group 2 (Food Waste):</em> Sounds of chopping, eating, discarding, composting.</li>\n<li><em>Group 3 (Sustainable Design):</em> Rhythms using recycled materials, representing durability and reuse.</li>\n<li><em>Group 4 (Consumer Awareness):</em> Rhythms that reflect the influence of advertising, the power of choice.</li>\n<li><em>Group 5 (Renewable Energy):</em> Sounds of wind turbines, solar panels, flowing electricity.</li>\n</ul><br>Select instruments (including recycled materials) to create their rhythms.<br>Compose a short musical phrase or ostinato (4-8 beats) that represents their topic.<br>Consider how their rhythm could be layered and combined with the rhythms of other groups.</p>"} {sdgColor} />

	<CustomSection title={"Circular Rhythm Performance"} content={"<p>Each group performs their rhythm for the class.<br>Guide the class in gradually layering the rhythms, creating a “circular rhythm piece”.\n<ul>\n<li>Start with one group’s rhythm, then add another, and another, building up the complexity.</li>\n<li>Encourage students to listen carefully to how the different rhythms interact.</li>\n<li>Explore variations in tempo, dynamics (loudness/softness), and texture (timbre), to create musical interest.</li>\n</ul><br>The piece can end with all groups playing together, representing the interconnectedness of all aspects of sustainable consumption and production.</p>"} {sdgColor} />

	<CustomSection title={"Reflection and Discussion"} content={"<p>Facilitate a discussion about the musical experience. Ask questions like:\n<ul>\n<li>How did the different rhythms represent the various aspects of Global Goal 12?</li>\n<li>How did the “circular rhythm” concept relate to the idea of a circular economy?</li>\n<li>What did you learn about the power of music to communicate complex ideas?</li>\n<li>How can music inspire action for a more sustainable future?</li>\n</ul><br>Connect the musical experience to Global Goal 12.<br>Example:\n<ul>\n<li>The layered rhythms can represent the interconnectedness of production and consumption. The use of recycled materials as instruments can highlight the importance of reducing waste.</li>\n</ul></p>"} {sdgColor} />

	<CustomSection title={"Reflection and Summary"} content={"<p>Have students reflect on their learning experience through discussion or writing.<br>Ask guiding questions like:\n<ul>\n<li>How did creating a “circular rhythm piece” help you to understand the concept of a circular economy and its connection to responsible consumption and production?</li>\n<li>What did you learn about how different sounds and rhythms can represent various aspects of sustainability, like resource use, waste reduction, or renewable energy?</li>\n<li>Did using recycled materials as instruments change your perspective on waste or the potential for reuse?</li>\n<li>How did the layering of different rhythms within the piece reflect the interconnectedness of the various targets within Global Goal 12?</li>\n<li>What did you discover about the power of music to communicate complex ideas in a way that is both engaging and thought-provoking?</li>\n<li>What new insights did you gain about Global Goal 12 and the importance of sustainable consumption and production patterns through this musical exploration?</li>\n<li>How did focusing on specific concepts within Global Goal 12 help you to translate abstract concepts into concrete sounds and rhythms?</li>\n<li>Did the activity make you think differently about your own relationship with consumption and its impact on the environment?</li>\n<li>How can music help us to imagine and create a more sustainable future?</li>\n<li>Did creating and performing your rhythmic piece spark any personal connections or reflections on your own experiences with consumption or waste?</li>\n<li>What emotions did you connect with during this musical activity, and how might those emotions motivate you to take action related to Global Goal 12?</li>\n<li>What is one key takeaway about responsible consumption and the power of creative expression that you will remember from this lesson?</li>\n</ul></p>"} {sdgColor} />

	<CustomSection title={"Assessment"} content={"<ul>\n<li>Consistent and enthusiastic involvement in all phases of the lesson, including the initial brainstorming, rhythm exploration, collaborative composition, and class discussions.</li>\n<li>Comprehension of Global Goal 12, targets and core concepts. This will be evidenced through the symbolism and intention within their rhythmic patterns and their verbal explanations during sharing and discussion.</li>\n<li>Originality and effectiveness in crafting rhythmic phrases or ostinatos, using body percussion or improvised instruments to convey messages about responsible consumption and production.</li>\n<li>How clearly and powerfully the collective rhythmic piece communicated its intended message about Global Goal 12. Did the combined sounds successfully evoke thought or emotion related to the goal?</li>\n<li>Ability to work effectively within the groups, contributing ideas, listening to others’ musical contributions, and collaborating cohesively to create the layered rhythm.</li>\n<li>Ability to maintain a steady beat, execute rhythmic patterns with reasonable precision, and blend sounds effectively within the ensemble, demonstrating musical awareness.</li>\n<li>Nuance and depth of understanding demonstrated in reflections, particularly concerning the role of music in advocating for sustainable development and the complexities of consumption patterns.</li>\n</ul>"} {sdgColor} />

</div>
