<script lang="ts">
	import MaterialsList from './components/MaterialsList.svelte';
	import Introduction from './components/Introduction.svelte';
	import ReflectionQuestions from './components/ReflectionQuestions.svelte';
	import AssessmentCriteria from './components/AssessmentCriteria.svelte';
	import CustomSection from './components/CustomSection.svelte';
	import { getSdgColor } from '$lib/utils/sdg-colors';

	interface Props {
		sdgColor?: string;
	}

	let { sdgColor = getSdgColor(7) }: Props = $props();
</script>

<div class="lesson-content">

	<MaterialsList materials={[{"name":"Paper or notebooks","isOptional":false},{"name":"Pens/pencils","isOptional":false},{"name":"Whiteboard or large chart paper","isOptional":false},{"name":"Energy Cards","description":"Small slips of paper or index cards with words, phrases, or short scenarios related to energy. You will need one set per group.","isOptional":false}]} {sdgColor} />

	<CustomSection title={"The Power of Words: Convincing for Clean Energy"} content={"<strong>(30-60 MINUTES)</strong>"} {sdgColor} />

	<Introduction content={"<p>Welcome students to an exciting creative writing class. Explain that they will use their words and imagination to explore a really important idea: Global Goal 7, Affordable and Clean Energy.<br>This goal focuses on making sure everyone, everywhere, has access to energy that is affordable (not too expensive), reliable (always there when you need it), and clean (good for the planet). Emphasize that this means lights for homes and schools, clean ways to cook food, and power for our devices, all without harming the Earth.<br>Explain to students that today, they will become “persuasive writers.” Clarify that persuasive writing is all about trying to convince someone of think, feel, or do something, using strong words and good reasons. Tell students that persuasive writing is like being a detective for ideas — you gather clues (reasons) to prove your point.<br>Explain that persuasive writing is actually everywhere: in ads for toys and electronics, in letters to congress people, or even when you convince a friend to play a certain game (just not written down\\!). Today, they will use persuasive writing to convince others about the importance of clean energy.</p>"} />

	<CustomSection title={"Warm Up"} content={"<p>Explain that the class will play a quick warm up game, where you will give students a simple topic, and they will then quickly think of one “claim” (something they believe is true about the topic). They will then give one “spark” for that same topic (a short reason or idea that makes their claim convincing or exciting).<br>Examples<br><em> </em>Topic: Recess<em><br></em> Ask: Make a claim about recess. What do you think about it?<br><em> Students share: Recess is the best part of the day or recess helps us focus in class, etc. Have a few students share their claims.<br></em> Then ask: Now, give it a spark. What’s one quick reason or exciting idea that supports your claim?<br><em> Students share: Because we get to run and play or because it gives our brains a break, etc. Have a few students share their claims with sparks.<br></em> <em>Topic: Reading</em><br><em> Ask: Make a claim about reading. What do you think about it?<br></em> Students share: Reading is so fun or reading helps you learn amazing things, etc.<br><em> Then ask: Now, give it a spark. What’s one quick reason or exciting idea that supports your claim?<br></em> Students share: Because you can visit other worlds or because it gives you so much new information.<br><em> </em>Topic: Saving Energy<em><br></em> Ask: Make a claim about saving energy. What do you think about it?<br><em> Students share: Saving energy is important or saving energy helps everyone, etc.<br></em> Then ask: Now, give it a spark. What’s one quick reason or exciting idea that supports your claim?\n<ul>\n<li>Students share: Because it helps the earth or because it means more power for others, etc.</li>\n</ul><br>Conclude the warm up activity by affirming the quick thinking about claims and reasons, explaining that these are the building blocks of persuasive writing.</p>"} {sdgColor} />

	<CustomSection title={"Writing Our Energy Messages"} content={"<p>Divide students into small groups (3-4 groups per class). Provide each group with a set of Energy Fact/Feeling Cards (each group should have about 20 cards total).<br>Instruct groups to look at their cards and explain the categories.<br><em> </em>Energy Problems:<em> Cards that describe challenges or negative impacts of energy.<br></em> <a href=\"https://docs.google.com/document/d/1hvun20-VHd1Z2p5mc5dTjvA7npPbV8GyB2zvn4IkyVM/edit?usp=drive_link\" target=\"_blank\" rel=\"noopener noreferrer\">Examples</a><br><em> </em>Clean Energy Powers:<em> Cards that describe benefits of clean energy or how it works.<br></em> <a href=\"https://docs.google.com/document/d/17q-qIiA6sjbcj4sI1Hnkci2k7sdDg46u0zIfMsHgnxI/edit?usp=drive_link\" target=\"_blank\" rel=\"noopener noreferrer\">Examples</a><br>Instruct students to sort their cards into these categories.<br>Encourage groups to discuss why each card fits into a particular pile.<br>Circulate, offering guidance and asking guiding questions like:<br><em> Why did you put this card in Energy Problems?<br></em> What’s one card in Clean Energy Powers that makes your feel positive?<br><em> Which idea sparks your interest the most?<br>After sorting, instruct each individual student to choose one idea from a card that they find particularly interesting or important. This will be the main idea they focus on for their persuasive writing piece. Students can choose a card from Energy Problems OR Clean Energy Powers.<br></em> If an Energy Problems idea is chosen, the persuasive writing will focus on convincing others why this problem is bad and why it needs to be solved through clean energy.\n<ul>\n<li>If a Clean Energy Powers idea is chosen, the persuasive writing will focuson convincing others why this clean energy solution is good and why we should support it.</li>\n</ul></p>"} {sdgColor} />

	<CustomSection title={"My Energy Message"} content={"<p>Make sure each student has paper/journal and pen/pencil.<br>Explain: You will now write a short persuasive piece (about 1-2 paragraphs) to convince someone about Global Goal 7: Affordable and Clean Energy.<br>Instruct students to choose one of the following formats:<br><em> </em>Persuasive Paragraph:<em> Write a short persuasive pice trying to convince a friend, family member, or classmate to save energy or use clean energy, using the idea from the chosen card.<br></em> <em>Community Announcement:</em> Write a short announcement (like for morning announcements or a school newspaper, speaking to many instead of one) trying to convince people to support clean energy, using the idea from the chosen card.<br>Emphasize the key parts of persuasive writing:<br><em> </em>Start strong:<em> Grab attention\\! (e.g., Did you know…? Imagine a a world where…).<br></em> <em>Give reasons:</em> Use solid ideas to support your point (e.g., Clean air is better for our lungs. Solar power is always on\\!).<br><em> </em>Use convincing words:<em> Use strong verbs and words that show why your idea is important (e.g., vital, amazing, harmful, important, terrible, sparkling, powerful).<br></em> <em>Tell the audience what to do:</em> A clear “call to action” (e.g., So turn off the lights\\! Join the clean energy team\\!).<br>Circulate, offering guidance as the class writes. Ask guiding questions like:<br><em> Whats the one most important reason you want to share from your chosen card?<br></em> How can you make your opening sentence grab the reader’s attention?<br><em> Can you use a word you remember from your Clean Energy Powers cards to make your reason sound even better?<br></em> What would you like your reader to do after reading your message?\n<ul>\n<li>Does your message make someone feel hopeful, worried, or ready to act?</li>\n</ul></p>"} {sdgColor} />

	<CustomSection title={"Peer Review and Sharing"} content={"<p>Have students pair up or divide them into pairs. Instruct them to exchange their persuasive pieces with their partner.<br>Guide the peer review process with guiding questions, focusing on the persuasive elements.<br>Examples:<br><em> What did your partners message want you to do or think? Were you convinced? Why or why not?<br></em> What were the strongest reasons your partner used? Which ideas from our brainstormed cards did they use well?<br><em> Did their message make you feel something? What emotions did it create?<br></em> What is one positive comment you can give them about their writing?\n<ul>\n<li>What is one suggestion to make their message even more convincing?</li>\n</ul><br>If time permits and if desired, allow a few minutes for students to make quick revisions based on their partner’s feedback. Volunteers can then share their persuasive piece with the whole class.</p>"} {sdgColor} />

	<ReflectionQuestions questions={["How did trying to convince someone with your writing help you understand Global Goal 7: Affordable and Clean Energy in a new way?","What did you learn about the power of using strong reasons and exciting words to persuade people?","Which messages from your classmates made you think, “Wow, that’s a powerful way to talk about energy\\!” and why?","What does this activity tell us about how we can all work towards Global Goal 7?","What’s one small action you feel inspired to take this week to save energy or promote clean energy, perhaps because you feel more convinced now?"]} {sdgColor} />

	<AssessmentCriteria criteria={["Consistent and enthusiastic involvement in all phases of the lesson, including the warm up, brainstorm, individual writing process, and class discussions.","Understanding of the core concept of affordable and clean energy (benefits, problems, solutions), as demonstrated through the content and message of the persuasive piece and the verbal explanations.","Originality and effort in crafting the persuasive piece. Look for evidence of a clear claim and message (does the writing clearly state what it wants to convince the reader of, based on the chosen card?), reasons and evidence (are ideas from the cards used to support the message?), call to action (is there a clear suggestion for what the reader should think or do?), and engaging language (are strong verbs and descriptive words used to make it convincing?).","Ability to provide thoughtful, specific, and supportive feedback to peers, focusing on persuasive effectiveness.","Ability to articulate learning and personal connections during the reflection and summary discussion."]} {sdgColor} />

</div>
