<script lang="ts">
	import Introduction from './components/Introduction.svelte';
	import ReflectionQuestions from './components/ReflectionQuestions.svelte';
	import AssessmentCriteria from './components/AssessmentCriteria.svelte';
	import CustomSection from './components/CustomSection.svelte';
	import { getSdgColor } from '$lib/utils/sdg-colors';

	interface Props {
		sdgColor?: string;
	}

	let { sdgColor = getSdgColor(11) }: Props = $props();
</script>

<div class="lesson-content">

	<CustomSection title={"Urban Echoes: Drama for Sustainable Cities with Playback Theater"} content={"<strong>(30-60 MINUTES)</strong>"} {sdgColor} />

	<CustomSection title={"Materials:"} content={"<p>Large open space<br>Simple props (scarves, chairs, hats, etc.)<br>Whiteboard or large chart paper<br>Markers<br>Notebooks or paper<br>Pens/Pencils</p>"} {sdgColor} />

	<Introduction content={"<p>Begin by introducing Playback theater.<br>Explain that it is a form of improvisational theater where audience members share personal stories, and actors “play them back” using various theatrical forms.<br>Emphasize the importance of active listening, empathy, and respect in Playback theater.<br>Introduce or reintroduce Global Goal 11. Explain the goal’s focus on creating inclusive, safe, resilient, and sustainable cities and communities.<br>Connect Playback theater and Global Goal 11. Example:\n<ul>\n<li>Today we will be using Playback theater as a powerful tool to explore the human stories behind the statistics and targets of Global Goal 11. theater allows us to connect with the lived experiences of individuals within our communities, revealing the impact of urban challenges and potential solutions on a personal level.</li>\n<li>By sharing and enacting these stories, we can deepen our understanding of Global Goal 11, fostering empathy and inspiring action to create more inclusive and sustainable cities. Playback theater gives us a way to show the emotional side of these issues, and to show how these issues impact real people in real ways. This emotional connection is a powerful tool to inspire change. We will use the power of theater to give a voice to the people who are impacted by these issues, and help create momentum for positive change.</li>\n</ul></p>"} />

	<CustomSection title={"Story Gathering and Sharing"} content={"<p>Guide students in a story-gathering process related to their assigned targets.<br>Facilitate a discussion with questions that encourage personal stories and reflections:\n<ul>\n<li>Have you ever experienced or witnessed a situation related to inadequate housing in our community? (Target 11.1)</li>\n<li>What are your experiences with public transportation, and how accessible is it for everyone? (Target 11.2)</li>\n<li>Can you share a story about a time you felt excluded from a community decision or planning process? (Target 11.3)</li>\n<li>What places of local cultural or natural heritage are important to you, and how are they being protected? (Target 11.4)</li>\n<li>Have you or anyone you know been affected by a local disaster or environmental issue? (Target 11.5)</li>\n<li>What are you experiences with waste management in your city? (Target 11.6)</li>\n<li>Where are you favorite public green spaces, and how accessible are they? (Target 11.7)</li>\n<li>How does your city connect with surrounding rural areas? (Target 11.a)</li>\n<li>What are some local actions that help reduce disaster risk? (Target 11.b)</li>\n<li>What examples of sustainable buildings can you find in your area? (Target 11.c)</li>\n</ul></p>"} {sdgColor} />

	<CustomSection title={"Playback Performance"} content={"<p>Using the stories shared, the rest of the class will use Playback theater techniques to perform the stories.<br>Guide the actors/students in choosing the appropriate Playback forms for each story, and choosing who will participate based on your specific class. Examples:\n<ul>\n<li><em>Stories:</em> A straightforward retelling of the narrative, the actor(s) tell the story back to the audience, capturing the emotion of the original storyteller.</li>\n<li><em>Fluid Sculptures:</em> Actors use their bodies to create a moving tableau that captures the essence of the story.</li>\n<li><em>Pairs:</em> Actors perform a short scene based on a key interaction from the story.</li>\n<li><em>Sound and Movement:</em> Actors use sounds and movements to express the emotions and atmosphere of the story.</li>\n</ul><br>Encourage students to use creative expression, symbolism, and emotional depth in their performances.<br>Facilitate a brief discussion after each performance, allowing the storyteller and audience to reflect on the experience.</p>"} {sdgColor} />

	<CustomSection title={"Reflection and Summary"} content={"<p>Have students reflect on their learning experience through discussion or writing.<br>Ask guiding questions like:\n<ul>\n<li>How did the experience of hearing and seeing personal stories played back in real-time deepen your understanding of the human impact of urban challenges related to Global Goal 11?</li>\n<li>What emotions or insights did you gain from witnessing your classmates’ stories (or your own) being brought to life through Playback theater?</li>\n<li>Did the act of observing or performing these “urban echoes” make you feel more connected to the experiences of others in your community?</li>\n<li>How did focusing on individual stories help to humanize the statistics or abstract targets of Global Goal 11?</li>\n<li>What did you learn about the power of improvisational theater, specifically Playback theater, as a tool for communication and understanding?</li>\n<li>How did the different Playback forms (e.g., stories, fluid sculptures, sound and movement) effectively capture the essence of the shared narratives?</li>\n<li>What were the strengths of using theater to explore issues like sustainable transportation, waste management, or green spaces, compared to just discussing them?</li>\n<li>How might Playback theater be used in wider community settings to foster dialogue and inspire action for sustainable cities?</li>\n<li>What new insights did you gain about Global Goal 11 and the importance of creating inclusive, safe, resilient, and sustainable cities and communities?</li>\n<li>Did hearing the stories from different targets of Global Goal 11 highlight the interconnectedness of urban challenges?</li>\n<li>What is one key takeaway about sustainable cities and the power of the individual and collective action that you will remember from this lesson?</li>\n<li>What specific action, big or small, are you inspired to take after this lesson to contribute to achieving Global Goal 11?</li>\n</ul></p>"} {sdgColor} />

	<CustomSection title={"Assessment"} content={"<ul>\n<li>Consistent and attentive involvement in all phases of the lesson, including story gathering, participation as storytellers or actors (if applicable), and active listening during discussions.</li>\n<li>Ability to listen attentively and respond empathetically to shared personal stories, both as a participant and as an observer in the Playback performances.</li>\n<li>Comprehension of Global Goal 11, targets and core concepts, and their connection to urban challenges, as demonstrated through story contributions, Playback interpretations, and verbal explanations during discussions.</li>\n<li>Originality and effectiveness of Playback performances, including use of specific forms (e.g., stories, fluid sculptures, sound and movement) (if applicable) to capture the essence and emotion of the shared narratives.</li>\n<li>How clearly and powerfully the Playback renditions communicated the human impact of issues related to sustainable cities. Did the performance successfully evoke thought or emotion?</li>\n<li>Ability to work effectively and respectfully with fellow actors, responding spontaneously and collaboratively to the storyteller’s narrative (if applicable).</li>\n<li>Nuance and insight demonstrated in reflections, particularly concerning the role of personal storytelling and theater in advocating for sustainable development and understanding urban challenges.</li>\n</ul>"} {sdgColor} />

</div>
