<script lang="ts">
	import MaterialsList from './components/MaterialsList.svelte';
	import ReflectionQuestions from './components/ReflectionQuestions.svelte';
	import AssessmentCriteria from './components/AssessmentCriteria.svelte';
	import CustomSection from './components/CustomSection.svelte';
	import { getSdgColor } from '$lib/utils/sdg-colors';

	interface Props {
		sdgColor?: string;
	}

	let { sdgColor = getSdgColor(1) }: Props = $props();
</script>

<div class="lesson-content">

	<MaterialsList materials={[{"name":"Whiteboard or large chart paper","isOptional":false},{"name":"Markers","isOptional":false},{"name":"Notebooks or Paper","isOptional":false},{"name":"Pens/Pencils","isOptional":false}]} {sdgColor} />

	<CustomSection title={"Words of Hope: Creating Stories for No Poverty"} content={"<strong>Introduction</strong><br>Welcome students to an exciting creative writing adventure. Tell them that today, they will use the power of their words to explore a very important idea, Global Goal 1: No Poverty.<br>This goal is a global commitment to ensure everyone, regardless of where they live, has what they need to live a happy, healthy life. This includes having enough food, a safe home, clean water, clothes, and a chnace to learn and grow. It's about fairness and making sure no one is left behind.<br>Connect Global Goal 1 to writing, explaining that writing can paint pictures in people's minds, make them feel emotions, and even inspire them to make the world a better place. Tell students that today, they will harness that power, using their creative writing skills to think about a world where everyone has enough and how they can help make that a reality."} {sdgColor} />

	<CustomSection title={"Story Sparks for a Better World"} content={"<p>Begin by asking students:<br><em> What are some of the most important things every person needs to be happy and healthy?<br></em> Encourage students to think about basic necessities beyond just toys or electronics.<br><em> Examples: Food to eat, clean water to drink, a safe and warm home to sleep in, clothes to wear, doctors and medicine when they're sick, schools and books to learn, kind friends and family, a chance to play and have fun, feeling safe, someone to listen to them, a way to learn new skills, a sense of belonging.<br>On the whiteboard or large paper, create two columns. Label one \"When Everyone has Enough\" and the other \"When People Need Help.\"<br>Guide the discussion by asking students to describe what it looks, sounds, or feels like in both situations. Use the senses to make it more concrete.<br></em> \"<em>When People Need Help\"</em>:<br><em> What might it look like if someone doesn't have enough food?<br></em> What might a neighborhood sound like if kids can't go to school?<br><em> How might a person feel if they don't hae a warm coat in the winter?<br></em> Answer Examples:<br><em> An empty fridge<br></em> A quiet playground<br><em> A person shivering in the cold<br></em> Someone looking sad or worried<br><em> A leaky roof<br></em> Children working instead of playing<br><em> A family sharing very little food<br></em> <em>\"When Everyone Has Enough\"</em><br><em> What sights would you see in a community where everyone helps each other?<br></em> What sounds would you hear?<br><em> How would people feel?<br></em> Answer examples:<br><em> A family sharing a yummy meal<br></em> Laughter echoing from a full playground<br><em> Warm clothes on everyone<br></em> A doctor helping someone feel better<br><em> Kids reading together<br></em> Big smiles\n<ul>\n<li>A sense of belonging</li>\n</ul><br>Record student responses in the appropriate columns. This creates a shared word bank for their writing.</p>"} {sdgColor} />

	<CustomSection title={"Creative Writing Exercise"} content={"<p>Explain that it is now time to choose a \"story spark\" and create their own piece of writing. They can write either a short story or a poem (or, educator can require one if desired).<br>Offer the following writing prompts, or a prompt of your own. Encourage students to use the words and ides from the brainstorming session to make their writing come alive with details and feelings.<br><em> </em>Prompt 1: The Day We All Shared<em><br></em> Write a story or poem about a time (real or imagined) when people in a family, a school, or a neighborhood came together to share what they had so that everyone had enough. What happened? Who helped? How did it make everyone feel?<br><em> </em>Prompt 2: A Day in a World Without Poverty<em><br></em> Imagine a world where Global Goal 1 has come true, and no one lives in poverty. Write a story or poem about a normal day for a child in that world. What do they see, hear, feel? What are they doing? How do they know everyone has what they need?<br><em> </em>Prompt 3: The Helping Hand<em><br></em> Write a story or poem from the point of view of someone who receives a helping hand when they really need it (like a warm coat, a healthy meal, or a new book for school). How does that help change their day or their feelings? Or, write from the point of view of someone giving the helping hand.<br>Encourage students to use vivid imagery (what you see, hear, smell, touch, taste) and emotional language to make their stories and poems powerful. Remind them to think about the feelings people experience.</p>"} {sdgColor} />

	<CustomSection title={"Sharing Words of Hope"} content={"<p>Organize students into pairs or small groups (3-4 students).<br>Instruct students to take turns reading their writing aloud to their partner/group.<br>As they listen, encourage students to offer positive and constructive feedback. Focus on questions like:<br><em> What did you see or feel when you heard this story/poem?<br></em> What was your favorite part, and why?<br><em> How did this story/poem connect to Global Goal 1: No Poverty?<br></em> Did any words or phrases stand out to you?<br>After group sharing, invite a few volunteers to share their writing with the whole class. Facilitate a supportive live discussion about the different ideas and feelings expressed in the writing.</p>"} {sdgColor} />

	<ReflectionQuestions questions={["What was the most important thing you learned about Global Goal 1: No Poverty today, through our writing?","Did writing a story or poem about these ideas change how you think or feel about poverty?","What did you discover about how powerful our words can be to share ideas and feelings?","How did using details about what you see, hear, and feel help make your writing stronger?","Think about the stories we read and heard today. What's one small think you can do in your own life to help make sure everyone has what they need?"]} {sdgColor} />

	<AssessmentCriteria criteria={["Consistent and thoughtful involvement in all phase of the lesson, including the initial brainstorm, individual creative writing, partner sharing, and active participation in class discussions.","Comprehension of the core concept of Global Goal 1 (\"No Poverty\" and what it means for basic needs and community support), as demonstrated through the content and message of the creative writing pieces and verbal contributions during discussions.","Originality and effort put into the story or poem. Look for evidence of the writing clearly relating to the idea of people needing help or people helping each other to meet basic needs, and attempts to use sensory details (what you see, hear, feel, etc.), descriptive words to make the writing vivid. Does the writing try to convey feelings like hope, kindness, challenge, or happiness?","Ability to respectfully share writing with peers and offer constructive feedback during the sharing sessions.","Ability to articulate learning and personal connections during the reflection and summary discussion."]} {sdgColor} />

</div>
